### ISSUE TITLE
Prettier inserts whitespace between inline HTML tags 

### ISSUE THREAD

**Issue by harmenjanssen** [sveltejs/language-tools#503] opened 2020-08-30 13:19 UTC
**Describe the bug**
Prettier will move all HTML tags to new lines, effectively inserting whitespace between them, which gets rendered by the browser.

**To Reproduce**
Create `Example.svelte` and include the following:

```
<p>Lucky number: <span>4</span><span>2</span></p>
```

Prettier will format this like:

```
<p>
  Lucky number:
  <span>4</span>
  <span>2</span>
</p>
```

Whereas it leaves an HTML file with the same contents alone.

**Expected behavior**

I would expect the inline elements to be left alone, and whitespace preserved.

**System (please complete the following information):**
 - OS: MacOS Catalina
 - IDE: VSCode 1.48.2
 - Plugin/Package: Svelte for VS Code v101.11.1

**Comment by dummdidumm** [comment] 2020-08-30 13:20
Duplicate of #323

**Closed by dummdidumm** 2020-08-30 13:20 UTC
Labels: bug
