### ISSUE TITLE
TypeScript control flow analysis for #if blocks possible?

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#833] opened 2021-02-21 09:32 UTC
**Describe the bug**
When using TypeScript, errors may be reported in component code due to type mismatches which would be resolved in regular TypeScript due to control flow analysis.

I suspect that this could be difficult to fix. If there is nothing that can be done, it would be nice if strict null checks could be disabled just for the HTML part of the component or if special comments could be added to ignore errors, similar to [`@ts-ignore`][ts-ignore] and [`@ts-expect-error`][ts-expect-error].

**To Reproduce**

With `strictNullChecks`:

```svelte
<script type="text/typescript">
	export let params: { guid?: string } = {}
	function find(guid: string) { /*...*/ }
</script>

{#if params.guid != null}
	{#await find(params.guid)} <!-- Error here -->
		[Loading]
	{:then document}
		...
	{/await}
{:else}
	Document not found.
{/if}
```

> Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
>   Type 'undefined' is not assignable to type 'string'. ts(2345)

**Expected behavior**
No error, as the type should be narrowed from `string | undefined` to just `string` by the `#if` block.

E.g. this works in regular TypeScript:

```ts
function find(guid: string) { /*...*/ }
let params: { guid?: string } = {};

if (params.guid != null)
{
	find(params.guid);
}
```

**System (please complete the following information):**
 - OS: Windows 10 64bit
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

[ts-ignore]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments
[ts-expect-error]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments

**Comment by dummdidumm** [comment] 2021-02-21 10:04
Duplicate of #619

**Closed by dummdidumm** 2021-02-21 10:04 UTC
Labels: bug
