### ISSUE TITLE
The href here is string | undefined but is not recognized as such

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#1978] opened 2023-04-08 20:28 UTC
### Describe the bug

Given the code:

```svelte
<script lang="ts">
	export let href: string | undefined = undefined;
</script>

<button on:click={href ? () => goto(href) : undefined}>
  Hello!
</button>
```

this error throws:

```
Argument of type 'string | undefined' is not assignable to parameter of type 'string | URL'.
  Type 'undefined' is not assignable to type 'string | URL'.ts (2345)
  let href: string | undefined
```

### Expected behaviour

I expect no error given the `href ?` part.

### System Info

`"typescript": "5.0.4"`

**Comment by jasonlyu123** [comment] 2023-04-09 02:08
This is because of the callback function. Inside a function, TypeScript would invalidate the control flow narrowing. 

https://www.typescriptlang.org/play?ssl=11&ssc=2&pln=1&pc=1#code/DYUwLgBAFgTiBmAuCBnMMCWA7A5hAPhAK5YAmC2IpA3ALABQDAFAJQQC8AfBAN4MQCIpAPYBjIgFsQWMADpRcAIZgQAUVBSZTAOQAjImDDCs2lrMWlSqgG7SwAGQxppIGE36DP20cAyiA1toANBAengKwCKH04bEQAPwQrBzcosYowqCywMI4TJHwLGFxJaWeAPTlEAB68cUlyMlcvAC+xUX0LUA

This is essentially a duplicate of #876. But from the generated code, svelte will check the condition before calling the handler. So this might never happen. In contrast, #876 does happen but very rarely. So I am leaving this open as a feature request.

**Comment by frederikhors** [comment] 2023-04-09 11:05
I do not understand.

**Comment by jasonlyu123** [comment] 2023-04-09 11:09
Meaning it is not a bug. It's how TypeScript control flow analysis works. But since this specific case won't happen in runtime. We could have special handling. No guarantee though.

**Closed** 2023-05-04 12:48 UTC
Labels: enhancement
