### ISSUE TITLE
Svelte-check complex index signatures

### ISSUE THREAD

**Issue by AndreasHald** [sveltejs/language-tools#1179] opened 2021-09-16 12:04 UTC
**Describe the bug**

If I have a component that exports a variable using the following type
```ts

export let prop: {[key: `data-${string}`]: string | number;} = {}
```

And consume the component like this
```svelte
<MyComponent prop={{'data-someValue':'someValue'}} />
```

Everything works as expected, however when I run svelte-check I get the following error

```
Error: An index signature parameter type must be either 'string' or 'number'. (ts)
```

It appears that svelte-check does not understand that syntax.

**To Reproduce**
- export prop with the following type in a component
```{[key: `data-${string}`]: any;}```

- consume that prop anywhere else
- run svelte-check

**Expected behavior**
I expected svelte-check to check that all keys in the object is a string that is prefixed with 'data-'

**System (please complete the following information):**
 - OS: OsX
 - IDE: VSCode
 - Plugin/Package: svelte-check

**Comment by dummdidumm** [comment] 2021-09-16 12:13
Which version of TypeScript is installed in your project? `svelte-check` uses that version to run the checks, and that version might be too outdated for these recent type checking features.

**Comment by dummdidumm** [comment] 2021-10-19 16:35
Closing due to lack of reproduction, can't reproduce this. Likely an outdated TS version project dependency.

**Closed by dummdidumm** 2021-10-19 16:35 UTC
Labels: bug

**Comment by AndreasHald** [comment] 2021-11-12 09:33
This was indeed caused by an outdated typescript version, for anyone who should hit the same issue
