### ISSUE TITLE
Discriminating union doesn't work in template

### ISSUE THREAD

**Issue by erezarnon** [sveltejs/language-tools#1831] opened 2023-01-13 00:22 UTC
### Describe the bug

`Column` can be either a `string`, `number`, or `object`. However, svelte sees only the string part. Also, ts-ignore doesn't work (see #1026) which means there's no workaround.

![image](https://user-images.githubusercontent.com/11790423/212208086-1fd1fddc-4857-4c58-805f-96bd61c0d3cb.png)

```
<script lang="ts" context="module">
  import type {ComponentType} from 'svelte';

  export type ColumnComponent = {
    Component: ComponentType;
    props?: Record<string, unknown>;
  }
  export type Column = string | number | ColumnComponent;
</script>

<script lang="ts">
  export let columns: string[];
  export let items: Record<string, Column>[];
</script>

<table>
  <thead>
    <tr>
      {#each columns as column}
        <td>
          {column}
        </td>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each items as item}
      <tr>
        {#each columns as column}
          <td>
            {#if typeof item[column] === 'string' || typeof item[column] === 'number'}
              {item[column]}
            {:else}
              <!-- @ts-ignore -->
              <svelte:component this={item[column].Component} {...item[column].props} /> <!-- @ts-ignore -->
            {/if}
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>
``` 

### Reproduction

See code snippet above. Looks like repl doesn't support typescript.

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 954.14 MB / 15.33 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
```

### Severity

blocking all usage of svelte

**Comment by jasonlyu123** [comment] 2023-01-13 01:08
Duplicate of #1541. This is a limitation of TypeScript's control flow analysis on an array index. The same error happens in a ts file. See [ts playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAwhcEB2K+MAKsmgL5wBmUucARAM4BuKANjCgwNwCwAKEEoAHpFgJy2COwCuIfDjyFicALwZBcbdOVEYALl2QVpcvwE64YOmCYB+IwCUUAY2gATADxMYUYPgA5gA0cLL4ANb4EADu+AB8FhQWouLwSKjScgrqcL7+QXAAPnD48gBGKFDFWfKKuCb6FoLsKPDu2fhMRvkBgQDaALq5Qxat8MBcIN1wLu5Q3r1BoTid8UMjg80C1NBwABTuXRNTcBDUcJMo0wCUmpY6u9WHBL5wHXVnFx8KTHfoWisOmAF32GRQ50uU36P3wwzUCLgAHIloEkcUSuDIVcQDCZHV4YikWUQJUoEj-oCgUCcXjOoMqUCqBwmGgAQ9qVZabDBgA6JSNYiMqwURmigQUIA). In your case, you can workaround with `{#const }`


```svelte
{#each columns as column}
  {@const value = item[column]}
  <td>
    {#if typeof value === "string" || typeof value === "number"}
      {item[column]}
    {:else}
      <svelte:component this={value.Component} {...value.props} />
    {/if}
  </td>
{/each}
```

**Closed by jasonlyu123** 2023-01-13 01:08 UTC
