### ISSUE TITLE
Deleting or pasting code sometimes causes messed-up highlighting and broken rename until reloading window

### ISSUE THREAD

**Issue by CherryDT** [sveltejs/language-tools#2534] opened 2024-10-12 14:25 UTC
### Describe the bug

Sometimes when deleting or pasting code, all the syntax highlighting gets messed up (things get highlighted with different colors in the middle of a word, etc.), the "rename" operation doesn't work correctly anymore and overwrites random other things in the file with the new name instead of changing the places where the original name was used. This state gets fixed only by reloading the window.

It started only recently, maybe a week or so ago.

### Reproduction

Don't know - it randomly happens when pasting code.

### Expected behaviour

Normal syntax highlighting, normal "rename" behavior

### System Info

- OS: Windows with remote WSL1
- IDE: VSCode 1.94.1

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![image](https://github.com/user-attachments/assets/e83cb51c-8050-476b-907b-028188b93deb)

**Comment by jasonlyu123** [comment] 2024-10-12 14:46
We'll need an actual reproduction to investigate. So please at least try to narrow down what the issue might be. Does this happen in a specific file? If so, does copying this file to any empty svelteKit project reproduce the problem? Is there a file in the directory with a similar name? Or maybe there is anything you did before you pasted any code? Like renaming the file?

**Comment by CherryDT** [comment] 2024-10-12 15:36
I realized it actually happens more frequently when _deleting_ code rather than pasting.

It's very hard for me reproduce reliably. It happens randomly on various files and various different areas of code, in different projects, approximately 1-2 times per hour. I was not renaming or creating or deleting files, just working on existing files.

I looked into the output pane a bit and I found two things that seemed relevant:

1: Under Svelte, there was this error:
```
Error: Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 3, !entry: false
    at getDocumentRegistryEntry (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:140976:11)
    at releaseDocumentWithKey (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:141070:19)
    at registry.releaseDocumentWithKey (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/svelte-language-server/dist/src/plugins/typescript/service.js:989:13)
    at getOrCreateSourceFileByPath (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:149935:30)
    at Object.getOrCreateSourceFile (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:149919:14)
    at /home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:149840:42
    at Object.getSourceFileWithCache [as getSourceFile] (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:124075:24)
    at findSourceFileWorker (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:126536:23)
    at findSourceFile (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:126452:20)
    at processImportedModules (/home/david/.vscode-server/extensions/svelte.svelte-vscode-109.1.0/node_modules/typescript/lib/typescript.js:126852:11)
```
2: Under Window, there was this warning:
```
2024-10-12 17:30:21.267 [warning] Overlapping semantic tokens detected at lineNumber 52, column 73
```

**Comment by jasonlyu123** [comment] 2024-10-13 04:16
The error sounds like you added `lang="ts"` to a svelte file that wasn't included in your tsconfig but was loaded because it was imported. But I can't reproduce the error. Can you reproduce it reliably with the information? If you can reliably reproduce it, please try to create a reproduction repository with the info. Else at least with your tsconfig/jsconfig and project structure.

**Comment by jasonlyu123** [comment] 2024-10-19 04:18
Let's track the error in #2538 since there is a reproduction for it. I currently can only reproduce the error but not the out-of-sync issue here. We'll see if it is also fixed once #2538 is fixed.

**Comment by jasonlyu123** [comment] 2024-10-20 07:08
I can reproduce the out-of-sync now with the reproduction of #2538, so I'm closing in favour of it.

**Closed by jasonlyu123** 2024-10-20 07:08 UTC
Labels: bug, awaiting submitter

**Comment by CherryDT** [comment] 2024-10-30 07:03
Thank you - I was not able to create a reproduction without keeping significant parts of the projects intact that I couldn't share.
