### ISSUE TITLE
Self closing textarea throws unexpected token

### ISSUE THREAD

**Issue by ignatiusmb** [sveltejs/language-tools#425] opened 2020-08-05 10:12 UTC
**Describe the bug**
Using a self-closing `<textarea />` throws unexpected token for code after it, specifically in `<style>`

**To Reproduce**
1. Add `<textarea></textarea>` to a Svelte file
2. Autoformats to `<textarea />`

**Expected behavior**
Expected to work like any other self closing tag.

**Screenshots**
- Not working in self-closing tag
![image](https://user-images.githubusercontent.com/8156777/89400521-37a92e80-d73e-11ea-990b-596143b6be58.png)

- Works with closing tag but needs to have text content inside to not autoformat it back to a self-closing tag
![image](https://user-images.githubusercontent.com/8156777/89400694-74752580-d73e-11ea-8381-7ef5a238a7d4.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**
A temporary workaround is to replace `textarea` with `<div contenteditable />`
![image](https://user-images.githubusercontent.com/8156777/89400965-ccac2780-d73e-11ea-8c2f-cc0f4e92d78c.png)

**Comment by dummdidumm** [comment] 2020-08-05 11:36
Duplicate of #300

**Closed by dummdidumm** 2020-08-05 11:36 UTC
Labels: bug

**Comment by ignatiusmb** [comment] 2020-08-05 13:04
I didn't realize there's an issue with the _exact_ same title, sorry my bad

**Comment by dummdidumm** [comment] 2020-08-05 13:08
Not your fault at all, I changed the title to your new title after you opened this issue because it is way better than that of the old one 😄

**Comment by ignatiusmb** [comment] 2020-08-05 13:11
Oh yeah you're right, I was worried that I missed an existing issue before opening a new one 😅
