### ISSUE TITLE
support selecting files to check

### ISSUE THREAD

**Issue by Tal500** [sveltejs/language-tools#1584] opened 2022-08-12 15:14 UTC
### Description

I would like to have the ability to run `svelte-check` on specific file.
WAIT WAIT WAIT I read the [FAQ in the `svelte-check` README.md](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check#why-is-there-no-option-to-only-check-specific-files-for-example-only-staged-files):

> Why is there no option to only check specific files (for example only staged files)?
>
> svelte-check needs to know the whole project to do valid checks. Imagine you alter a component property export let foo to export let bar, but you don't update any of the component usages. They all have errors now but you would not catch them if you only run checks on changed files.

So I get it, you typically need to scan more files then the one given in the argument.
But why do `svelte-check` need to scan the whole directory?

It is important for me because I would like to have static analysis before git commit only to the files I'm changing (in a similar fashion, but not identical, to [lint-staged](https://www.npmjs.com/package/lint-staged)), without scan the whole big project.
I can accept scanning more necessary files, but force the user to scan non-imported files?

### Proposed solution

The logic I see is to load the necessary Svelte and resources files in a greedy manner - start with the one the user specify, and load more files whenever you hit static/dynamic `import` file.

For the problem that a file you change might break other Svelte files using it - `svelte-check` can do some 'quick-analysis' to the other files in the project to see which files are being imported.

**Comment by dummdidumm** [comment] 2022-08-14 07:51
Closing as duplicate of #1538, which boils down to the same problem/possible solution as this issue. I'm not aware of a "give me all files that transitively depend on file X" command from the typescript language server, and implementing that ourselves _might_ be just as slow as running diagnostics on all files.

**Closed by dummdidumm** 2022-08-14 07:51 UTC
