### ISSUE TITLE
`compilerOptions.plugins` of `tsconfig.json` ignored? 

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/language-tools#1826] opened 2023-01-10 00:36 UTC
### Describe the bug

I'm using SvelteKit and trying to use [Vite's CSS Module feature](https://vitejs.dev/guide/features.html#css-modules), and it works pretty well; the only thing that's lacking that would make it ideal is type-safety.

For that, I tried to use ["typescript-plugin-css-modules"](https://github.com/mrmckeb/typescript-plugin-css-modules), which requires you to add a `compilerOptions.plugins` to your `tsconfig.json` file. Here's what mine looks like (it's the default `tsconfig.json` file in SvelteKit templates + a `plugins` array pointing to "typescript-plugin-css-modules"):
```json
{
    "extends": "./.svelte-kit/tsconfig.json",
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "plugins": [{ "name": "typescript-plugin-css-modules" }]
    }
}
```

Now, this seems to work perfectly in `.ts` files, and I get the right typing:

![image](https://user-images.githubusercontent.com/26527405/211435412-3ad275b4-a08e-475e-bae3-fc3d142cbf4a.png)

In `.svelte` files, however, it doesn't — it seems to be ignoring `tsconfig.json`'s `plugins`, and just falling back to the types declared by Vite.

![image](https://user-images.githubusercontent.com/26527405/211435980-9622d09f-e671-485b-aa2f-9f27c0cfab63.png)

Another possible explanation is that the Svelte language server is using VS Code's TypeScript version, as opposed to the workspace's TypeScript version — which is what "typescript-plugin-css-modules" needs (see [this](https://github.com/mrmckeb/typescript-plugin-css-modules#visual-studio-code)). The extension could provide an option to change that, like Volar does.
But I'm not familiar with the inner workings of the codebase to be able to tell. So, I'd appreciate some help. Thanks.

### System Info

- OS: Ubuntu 22.04
- IDE: VSCode

### Which package is the issue about?

svelte-language-server

**Comment by aradalvand** [comment] 2023-01-10 00:48
@jasonlyu123 What is the right label for this issue? Could you provide an explanation as to why it isn't "bug"?

**Comment by jasonlyu123** [comment] 2023-01-10 00:51
I am closing as a duplicate of #905. The typescript plugin feature is only available in the `tsserver` but we're using a lower-level `languageService` API.  And the plugin creation option also requires some `tsserver` specific APIs so we can't load the plugin by ourselves either. 

 We could maybe create a 3rd party interface for loading the plugin but the existing plugins still need to adopt for that to work.

**Closed by jasonlyu123** 2023-01-10 00:51 UTC

**Comment by aradalvand** [comment] 2023-01-10 00:54
> The typescript plugin feature is only available in the tsserver but we're using a lower-level languageService API.

Is there a specific reason why?
