### ISSUE TITLE
svelte-check false positive: Property is used before its initialization.

### ISSUE THREAD

**Issue by Bilge** [sveltejs/language-tools#2133] opened 2023-08-20 22:46 UTC
### Describe the bug

`svelte-check` believes fields are initialized before constructor arguments. This is false.

### Reproduction

```ts
export default class Foo {
    private readonly tags = <HTMLSelectElement>this.form.querySelector('[name=tags]');

    constructor(private readonly form: HTMLFormElement) {}
}
```

>Error: Property 'form' is used before its initialization.

```ts
export default class Foo {
    private readonly tags = <HTMLSelectElement>this.form.querySelector('[name=tags]');     
// -------------------------------------------------^^^^
```

### Expected behaviour

Passes check successfully.

### System Info

- OS: Windows
- IDE: PhpStorm

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

The code compiles to the following in TypeScript 4 & 5.

```js
class Foo {
    constructor(form) {
        this.form = form;
        this.tags = this.form.querySelector('[name=tags]');
    }
}
```

QED.

**Comment by jasonlyu123** [comment] 2023-08-21 01:16
This is the intended behaviour according to https://github.com/microsoft/TypeScript/issues/44298. If your target is set to "ES2022" onward and didn't turn off  `useDefineForClassFields`. TypeScript will transpile it into a javascript field, resulting in a runtime error. 

https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&jsx=0#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAYhBHAN4BQcdcYUAlgG6ozBxTCoIQB2mAJ5wYqAObEAvHAA8ACQAqAWQAyAZWCZgOGAFFtAW2D8YAPhgALJgQB0yaIdsBHdMChDN23dAAUAcgBtflRjKTFJAF1-AEoAbmpaehwBAhgodB8oX0ZWdk5uXgFhOAcoQwAuOCU1MnKDYGNTGKoAX2pWoA

**Comment by Bilge** [comment] 2023-08-21 08:45
OK, but I'm not using `ES2022`, I'm using `ES2018`. Shouldn't the checker be aware of the difference?

**Comment by jasonlyu123** [comment] 2023-08-21 09:08
Right, I forgot about https://github.com/sveltejs/language-tools/issues/1976. This is because we force ES2022. You can explicitly set `"useDefineForClassFields": false` until we fix #1976, which will probably be in the next major release. But you might as just adopt the new way. It's not a TypeScript bug. The error is because TypeScript will transpile it to the javascript class field in "ES2022" onward instead of `this.foo = ...`, Which changes the semantics of the output code.

**Comment by Bilge** [comment] 2023-08-21 09:12
>The error is because TypeScript will transpile it to the javascript class field in "ES2022" onward instead of this.foo = ..., Which changes the semantics of the output code.

I have seen no evidence of this. When I set my target to either `ES2022` or `esnext`, the output is unchanged. I do not use `useDefineForClassFields`, so it is whatever the default is. Moreover, the compilation example of `Object.defineProperty` seen in microsoft/TypeScript#44298 incorrectly claims the initialization order has been reversed, yet it has not. As far as I can see, this is still a TypeScript bug.

**Comment by jasonlyu123** [comment] 2023-08-21 09:23
> https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&jsx=0#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAYhBHAN4BQcdcYUAlgG6ozBxTCoIQB2mAJ5wYqAObEAvHAA8ACQAqAWQAyAZWCZgOGAFFtAW2D8YAPhgALJgQB0yaIdsBHdMChDN23dAAUAcgBtflRjKTFJAF1-AEoAbmpaehwBAhgodB8oX0ZWdk5uXgFhOAcoQwAuOCU1MnKDYGNTGKoAX2pWoA

The code sample is transformed into class fields in this typescript playground. 
 
```ts
export default class Foo {
    form;
    tags = this.form.querySelector('[name=tags]');
    constructor(form) {
        this.form = form;
    }
}
```
The default for `useDefineForClassFields` is true in "ES2022" or higher. https://www.typescriptlang.org/tsconfig#useDefineForClassFields. Not sure about the `Object.defineProperty` order in that issue. Maybe the decision has been reversed at some point. But it isn't related to the conversation.

**Comment by Bilge** [comment] 2023-08-21 09:42
OK, I'll just set `"useDefineForClassFields": false` in lieu of #1976, as suggested.

**Comment by dummdidumm** [comment] 2024-07-31 12:47
Closing in favor of  #1976

**Closed by dummdidumm** 2024-07-31 12:47 UTC
