### ISSUE TITLE
CSS container gives up warning

### ISSUE THREAD

**Issue by andirady** [sveltejs/language-tools#2103] opened 2023-07-20 03:54 UTC
### Describe the bug

All browsers listed in MDN now supports CSS container. When I use it in svelte, it gives warning in the language server & svelte-check.

### Reproduction

```svelte
<main>
   <div>Content</div>
</main>

<style>
  main {
    container-type: inline-size; /* this gives warning */
  }
  
  div {
    background: var(--bg);
    color: white;
    --bg: red;
  }
  
  @container (width > 728px) { /* this also gives warning */
    div {
      --bg: blue;
    }
  }
</style>
```

### Expected behaviour

No warning.

### System Info

- OS: [e.g. Windows]
- IDE: [e.g. VSCode, Atom]

### Which package is the issue about?

svelte-language-server, svelte-check

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/385785/5f1486de-da3c-4201-a3dd-4ac9b62669f7)

**Comment by jasonlyu123** [comment] 2023-07-20 04:00
Closing as duplicate of #1888. Let's keep all the container-related stuff in that issue.

**Closed by jasonlyu123** 2023-07-20 04:00 UTC
Labels: bug
