### ISSUE TITLE
Nested types returned via `let:` can not be properly narrowed for callbacks

### ISSUE THREAD

**Issue by hgiesel** [sveltejs/language-tools#1937] opened 2023-03-13 19:12 UTC
### Describe the bug

We have component `List.svelte`, that accepts a list of a type of a generic type, e.g. `Entry<T>[]`.

`List.svelte`, then iterates over the list, decorates a little bit, and returns `Entry<T>` back to us via a `let:` in a slot.

However the `T` we passed in is a union type, e.g. `type T = File | Folder`, which can be distinguished via a common prop, e.g. `.type`.

In the provided slot, we try to narrow the type. We see, that it works fine, if we access it directly, however not if we try to use it in a callback.

### Reproduction

I recreated the issue in a minimal repro:

https://github.com/hgiesel/svelte-issue-repro

That's the most interesting part:

https://github.com/hgiesel/svelte-issue-repro/blob/master/src/App.svelte#L28

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 66.95 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.2
  npmPackages:
    rollup: ^3.15.0 => 3.19.1 
    svelte: ^3.55.0 => 3.56.0
```

### Severity

annoyance

**Comment by jasonlyu123** [comment] 2023-03-14 06:06
Duplicate of #876

**Closed by jasonlyu123** 2023-03-14 06:06 UTC
