### ISSUE TITLE
`source.organizeImports` removes code between duplicate/unused imports

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1729] opened 2022-11-23 07:32 UTC
### Describe the bug

when there's code between duplicated imports, it deletes the code between them as well

### Reproduction

before:
```svelte
<script lang="ts">
import a from 'lodash'
console.log(1)
import b from 'lodash'
</script> 
```
after:
```svelte
<script lang="ts">
</script>
```

### Expected behaviour

```svelte
<script lang="ts">
console.log(1)
</script>
```

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2022-11-23 07:36
Duplicate of #1590

**Closed by jasonlyu123** 2022-11-23 07:36 UTC
Labels: bug
