### ISSUE TITLE
Make foldingImportsByDefault work in svelte files

### ISSUE THREAD

**Issue by Xeronic** [sveltejs/language-tools#2165] opened 2023-09-21 19:09 UTC
### Description

In ts and normal js files if this setting is turned on all imports are collapsed when opening a file. It would be great if this could be the case for Svelte files as well.

### Proposed solution

That the Svelte extension should respect this setting: `foldingImportsByDefault`

**Comment by jasonlyu123** [comment] 2023-09-22 01:55
Duplicate of #2037 and #1704.

**Closed by jasonlyu123** 2023-09-22 01:55 UTC

**Comment by Xeronic** [comment] 2023-09-22 07:16
Will there be a fix for this. I read this _The current folding is indentation based provided by VSCode. This should work as expected once we provide a more "semantic" folding range support._ . When will that be in place? I've files that have 20+ imports and it's annoying to not be able to collapse them without wrapping them in a region.

**Comment by jasonlyu123** [comment] 2023-09-22 07:56
Yes. It's on the way. It's nearly finished.
