### ISSUE TITLE
the generics of creatEeventDispatcher will lose the type constraint by using the imported interface 

### ISSUE THREAD

**Issue by cscxj** [sveltejs/language-tools#1570] opened 2022-07-28 03:37 UTC
### Describe the bug

First, I directly define the generics of createeventdispatcher. The performance of the editor is normal, identify the event type of the component.
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/44057776/181411826-90ed0223-6487-4597-93b5-c6d359951764.png">
If the generic definition is extracted, the event type cannot be deduced. As shown below.
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/44057776/181412400-9d56785e-b31f-4f0b-857d-67da423c58b1.png">

### Reproduction

[https://github.com/cscxj/svelte-events-type/blob/master/src/Container.svelte](https://github.com/cscxj/svelte-events-type/blob/master/src/Container.svelte)

### System Info

```shell
OS: Darwin arm64 21.3.0
vscode: 1.69.2 (Universal)
Svelte for VS Code v105.20.0 
svelte v3.49.0
vite 3.0.0
```

### Severity

annoyance

**Comment by DetachHead** [comment] 2023-03-24 03:02
duplicate of #1388?

**Comment by dummdidumm** [comment] 2023-03-24 10:11
Yes, thanks.

**Closed by dummdidumm** 2023-03-24 10:11 UTC
Labels: limitation
