### ISSUE TITLE
Error on "on:customevent" directive in VSCode

### ISSUE THREAD

**Issue by hare0319** [sveltejs/language-tools#1762] opened 2022-12-07 12:09 UTC
### Describe the bug

Follow the tutorial on local machine. When forwarded to _**Action**_ section, which refers to ```use``` directive to bind an action function to a node and ```on:customEvent``` directive to handle a custom event. It works fine with svelte/svelteKit and behaviour correct in a browser.

However, vscode complains about that ```on:customEvent``` is not one of known attribute of an HTMLElement. For a svelte component, it works.

### Reproduction

Download the package from [Svelte REPL](https://svelte.dev/repl/502b2344e1ed4a2ea73470740beed34c?version=3.54.0) and open it with vscode. In ```Modal.svelte``` file, Ln~21, vscode issue an error.

### Expected behaviour

No error promote related to this ```on:xxx``` directive staffs.

### System Info

- OS: Windows 11
- IDE: VSCode 1.73.1
Detailed VSCode version info included below
```
  Version: 1.73.1 (user setup)
  Commit: 6261075646f055b99068d3688932416f2346dd3b
  Date: 2022-11-09T04:27:29.066Z
  Electron: 19.0.17
  Chromium: 102.0.5005.167
  Node.js: 16.14.2
  V8: 10.2.154.15-electron.0
  OS: Windows_NT x64 10.0.22621
  Sandboxed: No
```

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2022-12-08 01:39
Duplicate of #431. See the [docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error) on how to enhance the default typing.

**Closed by jasonlyu123** 2022-12-08 01:39 UTC
Labels: bug
