### ISSUE TITLE
Syntax highlighting breaks inside script `context="module"` when the last line is `export type`

### ISSUE THREAD

**Issue by minht11** [sveltejs/language-tools#1776] opened 2022-12-15 01:18 UTC
### Describe the bug

Syntax highlighting breaks inside script `context="module"` when the last line is `export type`

### Reproduction

Take following component and observe incorrect color highlighting. Adding semicolon or new line fixes it.
```svelte
<script lang="ts" context="module">
	import { ICON_PATHS } from './icon-paths'

	export type IconKind = keyof typeof ICON_PATHS // This line breaks
</script>

<script lang="ts">
	export let kind: IconKind
</script>

<svg viewBox="0 0 24 24" class="fill-current">
	<path d={ICON_PATHS[kind]} />
</svg>

```

### Expected behaviour

Correct syntax highlighting when exporting type 

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="696" alt="image" src="https://user-images.githubusercontent.com/8914032/207749127-e0dfc83c-9905-4724-a1e7-5557d8ab023c.png">

With semicolon 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/8914032/207749253-005c73a8-31a7-443a-afcb-98c1a5f4616f.png">

**Comment by jasonlyu123** [comment] 2022-12-15 01:28
Duplicate of #1110. This is an upstream issue in the syntax highlight of typescript.

**Closed by jasonlyu123** 2022-12-15 01:28 UTC
Labels: bug
