### ISSUE TITLE
v102.5.0 Breaks TS support in .svelte files

### ISSUE THREAD

**Issue by ConnorJamesLow** [sveltejs/language-tools#655] opened 2020-11-05 18:05 UTC
**Describe the bug**
Imports and markup-interop type-hints break in .svelte files for version 102.5.0. 
 - Hovering over js variables in markup (e.g. `<div>{obj.value}</div>`) provides no type hints.
 - No property suggestions when trying to autocomplete in markup.
 - False positives with ts errors in `<script lang="ts">`.
 - False positives with component import errors (in some cases).

Reverting back to v102.4.0 fixes these issues: `code --install-extension svelte.svelte-vscode@102.4.0`.

**To Reproduce**
Install ` svelte.svelte-vscode@102.5.0`. Compare to `svelte.svelte-vscode@102.4.0`.

**Expected behavior**

**Screenshots**
 - No property suggestions when trying to autocomplete:
![image](https://user-images.githubusercontent.com/37132524/98278366-58576f00-1f4d-11eb-9782-90926fd735ad.png)
 - False positives with ts errors:
![image](https://user-images.githubusercontent.com/37132524/98278452-7624d400-1f4d-11eb-9ce5-d5139c917f7f.png)
 - False positives with component imports (in some cases):
![image](https://user-images.githubusercontent.com/37132524/98278001-d6674600-1f4c-11eb-80e0-26063e49b1ad.png)  

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode 1.50.1, x64
 - Plugin/Package: Svelte for VSCode

**Additional context**
To be clear, my app runs as expected, it looks to be entirely a tooling issue.

**Comment by dummdidumm** [comment] 2020-11-05 18:17
Do you have a minmum code snippet that reproduce this for you? I cannot reproduce it given your description.

**Comment by bradak1** [comment] 2020-11-05 18:45
With svelte-check 1.1.8
```
> svelte-check --output=machine
1604601599943 START "<my-path>"
1604601605719 COMPLETED 36 FILES 0 ERRORS 0 WARNINGS 10 HINTS
```
With svelte-check 1.1.9
```
> svelte-check --output=machine
1604601792022 START "<my-path>"
1604601797435 ERROR "src/components/employee/Employees.svelte" 10:18 "Unexpected token"
1604601797435 COMPLETED 36 FILES 1 ERRORS 0 WARNINGS 9 HINTS
```
The line in question just defines a variable with a type:
` let newEmployee: EmployeeDto;`

**Comment by MichealPearce** [comment] 2020-11-05 19:14
I too am receiving unexpected typescript errors with the latest update. So far, it has been only with imports. All have the same error, but are usually not the same lines between files. You can see here it marks the `*` as the error, other files mark `{` or other parts in the import line. 
   
![image](https://user-images.githubusercontent.com/8726457/98285644-dc6f1e00-1f70-11eb-95bc-1b2a43591b0c.png)

**Comment by MichealPearce** [comment] 2020-11-05 19:18
If someone is looking for a work-around:
* `ctrl+,`
* Search `extensions.autoUpdate` and disable it
* Open the terminal and revert the plugin to v102.4.0 with `code --install-extension svelte.svelte-vscode@102.4.0`
* Wait for it to install & reload

Don't forget to re-enable auto-updates later

**Comment by dimfeld** [comment] 2020-11-05 19:19
Looks like a PR just came in but in case it still helps, here's the smallest example I could get to reproduce reliably:

```svelte
<script context="module" lang="typescript">
  export class Control {
    el: string;
  }
</script>

<script lang="typescript">
</script>
```

**Comment by dummdidumm** [comment] 2020-11-05 20:08
This should be fixed with 102.5.1

**Closed by dummdidumm** 2020-11-05 20:08 UTC
Labels: bug

**Comment by jankalfus** [comment] 2020-11-06 06:33
Could we add a test for this to prevent stuff like this in the future? I'd love to do it, but I couldn't find any tests in this repo, maybe you can give me a hint.

Just some background: I'm new to Svelte and I've spent about 2-3 hours trying to figure out what was going on. First, the svelte extension broke after I reloaded vs code (which I didn't realize at that time), and then svelte-check stopped working after I reinstalled all the packages (which I also didn't realize at that time). I couldn't google anything or find anything in the troubleshooting guide for svelte-check, since this is apparently the first time something like this happened. Not a great experience. For somebody coming from React, a great typescript experience is a must. I was about to ditch Svelte for good :(

**Comment by dummdidumm** [comment] 2020-11-06 07:32
I added a test with the fix which you can see in the commit. Threatening to leave is not helping.

**Comment by jankalfus** [comment] 2020-11-06 13:36
Awesome, I missed that it's already included in the commit :)

BTW I'm not "threatening", I was merely trying to describe a situation it got me into and how it made me feel, that's all.
