### ISSUE TITLE
Default SCSS improper highlighting

### ISSUE THREAD

**Issue by Zettexe** [sveltejs/language-tools#959] opened 2021-04-22 14:56 UTC
I have set scss as default in both rollup and svelte.config.js and it seems to compile properly its just not highlighting correctly for nested elements unless the lang="scss" is there

![Screenshot_7](https://user-images.githubusercontent.com/53223513/115736535-e4821500-a37a-11eb-8fda-8d2427d379c3.png)![Screenshot_8](https://user-images.githubusercontent.com/53223513/115736537-e4821500-a37a-11eb-8e85-af338a544c9c.png)

**Comment by dummdidumm** [comment] 2021-04-22 15:09
Duplicate of #747

**Closed by dummdidumm** 2021-04-22 15:09 UTC
