### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by uc-prk** [sveltejs/language-tools#1098] opened 2021-07-15 01:09 UTC
- Issue Type: `Performance`
- Extension Name: `svelte-vscode`
- Extension Version: `105.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Prabhat\AppData\Local\Temp\svelte.svelte-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dummdidumm** [comment] 2021-07-15 06:04
You need to attach that file or else we can't investigate this

**Comment by dummdidumm** [comment] 2021-08-24 08:28
Closing due to lack of reproduction.

**Closed by dummdidumm** 2021-08-24 08:28 UTC
