### ISSUE TITLE
Extension causes issues with Go to definition 

### ISSUE THREAD

**Issue by Jovan12345** [sveltejs/language-tools#2051] opened 2023-06-11 11:38 UTC
Type: <b>Bug</b>

Cannot Go to any definition, by clicking Ctrl + (click on definition ex: function, interface, etc.)

Extension version: 107.5.1
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.71GB free)|
|Process Argv|D:\\upwork\\GesimiFrontendProject\\GesmiFrontend --crash-reporter-id 0349c5a9-8db4-431e-af79-6ee337d368ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by jasonlyu123** [comment] 2023-06-11 11:49
I'll close this because this issue description is unactionable, and most people submitting the issue with VSCode UI never replies. If you have more detailed information, please open another issue with Github, follow our issue template, and provide a reproduction.

**Closed by jasonlyu123** 2023-06-11 11:49 UTC
