### ISSUE TITLE
vscode does not recognize `.svelte` files imported in `.ts` files

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1725] opened 2022-11-21 08:46 UTC
### Describe the bug

i'm not quite sure it's even supposed to be allowed, but i stumbled across a project that has lots of `.ts` files importing `.svelte` files that seem to work at runtime, but not in vscode.

i suspect it's because it's using the typescript language server instead of the svelte one?

### Reproduction

```svelte
<!-- +page.svelte -->
<script lang="ts">
    export const a = 1
</script>
```
```ts
import { a } from './+page.svelte'
```

### Expected behaviour

no error

### System Info

- OS: [e.g. Windows]
- IDE: [e.g. VSCode, Atom]

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/57028336/203005312-ccdf46f0-1242-4e53-bb54-aef0adfed238.png)

**Comment by dummdidumm** [comment] 2022-11-21 09:44
Did you enable the Svelte TypeScript plugin? The vs code setting is called `svelte.enable-ts-plugin`

**Comment by DetachHead** [comment] 2022-11-21 23:38
yeah that's set to `true`

**Comment by ngmunyong** [comment] 2022-11-22 11:32
I had the same issue until I realised I didn't add that vs code setting json in the project.

1) create .vscode folder at project root
2) add the line mentioned above

![Screen Shot 2022-11-22 at 10 29 54 pm](https://user-images.githubusercontent.com/61854006/203303634-c9f80ac2-0841-4034-892d-fdf9fe40cebf.png)

Hope this works for you.

**Comment by hangilc** [comment] 2022-12-18 11:52
I have encountered the same problem, and changing the TypeScript version through Cmd-Shift-P "TypeScript: Select TypeScript version..." to version 4.9.3 ('Use Workspace version' in my case) solved the problem. Before changing it has been set to 5.0.0-dev20221217 ('Use VS Code's Version').

**Comment by DetachHead** [comment] 2022-12-19 02:42
@hangilc doesn't fix it for me

**Comment by jasonlyu123** [comment] 2022-12-19 05:28
I can reproduce what @hangilc is seeing. One of the TypeScript APIs we used in the TypeScript plugin no longer works in ts 5.0. @DetachHead if you follow what @hangilc said, what's the version you're seeing in the "Use VS Code's Version" option? If it's not TypeScript 5.x. We'll need a reproduction repository. I can't reproduce it with your steps.

**Comment by DetachHead** [comment] 2022-12-19 06:57
hmm, now i can't get it to happen anymore. i'll close this issue for now and will re-open and try to provide a repro repo if it happens again. thanks

**Comment by dummdidumm** [comment] 2022-12-19 10:08
@jasonlyu123 would you open a PR to fix the plugin for upcoming TS 5.x? Is it possible to do this in a backwards-compatible way?

**Comment by DetachHead** [comment] 2023-01-04 03:47
if it doesn't work in 5.x, i'll reopen this

**Comment by dummdidumm** [comment] 2024-08-29 21:42
I assume this was fixed, therefore closing.

**Closed by dummdidumm** 2024-08-29 21:42 UTC
Labels: bug
