### ISSUE TITLE
svelte-check: Bound prop that only is re-assigned falsely reports as "declared but never read"

### ISSUE THREAD

**Issue by AndersRobstad** [sveltejs/language-tools#2642] opened 2024-12-30 08:54 UTC
### Describe the bug

When only re-assigning a bound prop (i.e. never reading it or using it as a prop for another component) `svelte-check` throws the following error: `Error: 'propName' is declared but its value is never read. (ts)`

### Reproduction

The code below shows an example component and the output provided by `svelte-check`

![Skjermbilde 2024-12-23 kl  09 07 50](https://github.com/user-attachments/assets/1d0f6936-b913-4b54-b342-369d07dfbb40)

<img width="947" alt="Skjermbilde 2024-12-23 kl  09 09 54" src="https://github.com/user-attachments/assets/14d2bdf9-1c33-48f5-add2-09f1b61f4abc" />

### Expected behaviour

This should be possible to do since the prop is re-assigned and thus should not be reported as unused. 

### System Info

- OS: Mac
- IDE: VSCode

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

Package versions: 

* svelte: "^5.16.0",
* svelte-check: "^4.1.1",

**Comment by jasonlyu123** [comment] 2024-12-30 09:16
I already tried the code you posted at https://github.com/sveltejs/language-tools/issues/2268 and can't reproduce it. That is why I think it's more possible to be an outdated or conflicting dependency.  Please try to copy your code to an empty project and see if you can reproduce the error. Or maybe try deleting your node_modules and the lock file (ex: package-lock.json and pnpm-lock.yaml) and reinstall again.

**Comment by AndersRobstad** [comment] 2024-12-30 10:07
> I already tried the code you posted at #2268 and can't reproduce it. That is why I think it's more possible to be an outdated or conflicting dependency. Please try to copy your code to an empty project and see if you can reproduce the error. Or maybe try deleting your node_modules and the lock file (ex: package-lock.json and pnpm-lock.yaml) and reinstall again.

@jasonlyu123 Ahh, found the root cause now doing a bit more investigation on a newly created project. The issue appears when having the `noUnusedLocals` option set to `true` in your tsconfig.json. 

But to make it consistent with how ts works it should not be reported as unread since its re-assigned. It's possible to for example define a function with a parameter, re-assign the parameters value and never read it. This does not report any error

**Comment by jasonlyu123** [comment] 2024-12-31 01:27
Oh, thanks. I didn't notice that the unused variable hint and the error in `noUnusedLocals` have different criteria. Then I think we can merge this back to #2268 because the problem isn't just "no visible reassignment".

**Closed** 2024-12-31 01:27 UTC
Labels: bug
