### ISSUE TITLE
Formatter not functioning as expected in latest version (extensions-108.0.0)

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/language-tools#2210] opened 2023-11-22 13:44 UTC
### Describe the bug

The formatter in vscode no longer works

### Reproduction

Using the latest version

https://github.com/sveltejs/language-tools/releases/tag/extensions-108.0.0

### Expected behaviour

formatting should works

### System Info

- OS: Mac
- IDE: VScode

### Which package is the issue about?

https://github.com/sveltejs/language-tools/releases/tag/extensions-108.0.0

**Comment by dummdidumm** [comment] 2023-11-22 14:48
`svelte-check` isn't used for formatting.
Please provide a reproduction repository so we can properly investigate this.

**Comment by yassinrais** [comment] 2023-11-22 14:56
My bad it was the wrong release tag 😄 

The version that no longer works is this one (the most recent):
https://github.com/sveltejs/language-tools/releases/tag/extensions-108.0.0

Reproduction:
I have a basic svelte component file, and when I switch to the latest version 108.0.0 there's no formatting, but when I switch back to the previous version it works and the file is formatted like always.

**Comment by yassinrais** [comment] 2023-11-22 14:59
Log:

```ts
{
    "type": "Script",
    "start": 0,
    "end": 14003,
    "context": "default",
    "content": {
        "type": "Program",
        "start": 13992,
        "end": 13994,
        "loc": {
            "start": {
                "line": 1,
                "column": 0
            },
            "end": {
                "line": 1,
                "column": 13994
            }
        },
        "body": [
            {
                "type": "BlockStatement",
                "start": 13992,
                "end": 13994,
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 13992
                    },
                    "end": {
                        "line": 1,
                        "column": 13994
                    }
                },
                "body": []
            }
        ],
        "sourceType": "module"
    }
}
Error: unknown node type: Script
    at Object.print (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:1450:11)
    at callPluginPrintFunction (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8537:18)
    at AstPath.call (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8359:24)
    at printTopLevelParts (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:1491:33)
    at Object.print (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:901:16)
    at callPluginPrintFunction (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8537:18)
```

**Comment by yassinrais** [comment] 2023-11-22 14:59
Log:

```ts
{
    "type": "Script",
    "start": 0,
    "end": 14003,
    "context": "default",
    "content": {
        "type": "Program",
        "start": 13992,
        "end": 13994,
        "loc": {
            "start": {
                "line": 1,
                "column": 0
            },
            "end": {
                "line": 1,
                "column": 13994
            }
        },
        "body": [
            {
                "type": "BlockStatement",
                "start": 13992,
                "end": 13994,
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 13992
                    },
                    "end": {
                        "line": 1,
                        "column": 13994
                    }
                },
                "body": []
            }
        ],
        "sourceType": "module"
    }
}
Error: unknown node type: Script
    at Object.print (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:1450:11)
    at callPluginPrintFunction (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8537:18)
    at AstPath.call (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8359:24)
    at printTopLevelParts (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:1491:33)
    at Object.print (/Users/username/.vscode/extensions/svelte.svelte-vscode-108.0.0/node_modules/prettier-plugin-svelte/plugin.js:901:16)
    at callPluginPrintFunction (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/username/Documents/Project/svelte-project/node_modules/prettier/index.js:8537:18)
```

**Comment by yassinrais** [comment] 2023-11-22 15:00
```svelte
<script lang="ts">
// ... some basic code
</script>

<div>
  <!-- basic html -->
</div>

<style lang="scss">
// some basic style here
</style>

**Comment by dummdidumm** [comment] 2023-11-22 19:06
I can't reproduce this. Please provide a github repository that reproduces this issue.

**Comment by yadoga** [comment] 2023-11-23 13:50
Experiencing the same bug since yesterday (latest release). Just opened a very basic empty .svelte file. Auto-formatting does currently not work.

**Comment by dummdidumm** [comment] 2023-11-23 13:52
Can someone please provide an actual reproduction instead of just saying it doesn't work? As I said I can't reproduce this.

It has to do with the bump to using prettier version 3 by default now, I'm pretty sure about that, but I need a reproducible to get to the bottom of this

**Comment by yassinrais** [comment] 2023-11-23 13:53
im working on it :) sorry for late

**Comment by yassinrais** [comment] 2023-11-23 14:11
Here an exmaple:

https://github.com/yassinrais/svelte-language-tools-formatter-testing

**Comment by triskel78** [comment] 2023-11-23 16:14
@yassinrais if it helps you : I had the same issue with prettier version 2, updating to version 3 solved the problem

**Comment by dummdidumm** [comment] 2023-11-24 16:45
Should be fixed in the latest version of the VS Code extension

**Closed by dummdidumm** 2023-11-24 16:45 UTC
Labels: bug, Fixed
