### ISSUE TITLE
Duplicate Suggestion After Autocomplete

### ISSUE THREAD

**Issue by sophisticatedOscillator** [sveltejs/language-tools#1844] opened 2023-01-24 17:49 UTC
### Describe the bug

When typing out HTML elements in neovim.  I will be provided an autocomplete closing tag.  Upon selecting it, I am prompted by the autocomplete to create an erroneous, duplicate closing tag.

### Reproduction

https://github.com/ThePrimeagen/init.lua/
I used the following setup for my Neovim config
Then used Mason to install the svelte language server 0.15.3

This does not occur when writing in standard html files.

### Expected behaviour

When I create an html tag and its closing element, i should not be prompted to create another closing tag element

### System Info

Neovim 0.8.2
Ubuntu 22.04

### Which package is the issue about?

None

### Additional Information, eg. Screenshots

![Screenshot from 2023-01-23 20-57-43](https://user-images.githubusercontent.com/31316609/214369177-070c3a81-4405-4228-9195-3ae5eeaa5296.png)

I'm not a neovim guru.  Though I'm happy to dive through my config files to try to figure out how to toggle this off.

**Comment by jasonlyu123** [comment] 2023-01-30 01:52
As far as I remembered some completion plugins in neovim trigger completion on every keystroke rather than triggers on predefined trigger characters and alphabets like VSCode. You can see if your completion plugin has any config to disable this behaviour. 

On the other hand, What plugin or LSP server do you use for HTML files? This completion is coming from `vscode-html-languageservice` so it should happen in other LSP server that uses this package. We can see if the package you're using uses that package and if they have special handling to filter the completion.

**Comment by cpt-n3mo** [comment] 2023-02-28 10:36
> As far as I remembered some completion plugins in neovim trigger completion on every keystroke rather than triggers on predefined trigger characters and alphabets like VSCode. You can see if your completion plugin has any config to disable this behaviour.
> 
> On the other hand, What plugin or LSP server do you use for HTML files? This completion is coming from `vscode-html-languageservice` so it should happen in other LSP server that uses this package. We can see if the package you're using uses that package and if they have special handling to filter the completion.

from my neovim config

``` lua
 use { -- Autocompletion
    'hrsh7th/nvim-cmp',
    requires = { 'hrsh7th/cmp-nvim-lsp', 'L3MON4D3/LuaSnip', 'saadparwaiz1/cmp_luasnip' },
  }

```

**Comment by jasonlyu123** [comment] 2023-03-01 07:32
You can filter it out according to this issue https://github.com/hrsh7th/nvim-cmp/issues/1055#issuecomment-1214413360. 

About "vue-lang-server", I guess you meant by [vls](https://www.npmjs.com/package/vls) by vetur? Their HTML features were forked from `vscode-html-language-service` a long time ago. So they don't have a close tag suggestion after `<div>`. Volar, however, uses `vscode-html-language-service`  and probably has the same issue.

**Comment by cpt-n3mo** [comment] 2023-03-01 09:17
> You can filter it out according to this issue [hrsh7th/nvim-cmp#1055 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/1055#issuecomment-1214413360).
> 
> About "vue-lang-server", I guess you meant by [vls](https://www.npmjs.com/package/vls) by vetur? Their HTML features were forked from `vscode-html-language-service` a long time ago. So they don't have a close tag suggestion after `<div>`. Volar, however, uses `vscode-html-language-service` and probably has the same issue.

your my hero!
that worked like a charm!

**Comment by jasonlyu123** [comment] 2023-03-03 03:39
The problem is that https://github.com/hrsh7th/nvim-cmp use the last character before the cursor as a trigger character. I misremember it. 

@dummdidumm I found that vetur, volar and HTML all don't have `>` as a trigger character. So one solution is to skip HTML completion in case of `>` as the trigger character. The downside is that `<div>` won't trigger end tag completion. That will be a problem in VSCode if you disable `html.autoClosingTags`. But is in line with the behaviour of the HTML extension. 

Or we can skip the end tag suggestion when the previous tag is closed. It will be a bit different from the html but it's probably rare that you want the duplicate close tag completion. Which do you prefer?

**Comment by dummdidumm** [comment] 2023-03-03 07:50
I guess if someone disables `html.autoClosingTags` then they don't want the auto closing behavior anyway, so it would make sense to me to be in line with VS Code here. Do you remember why we made `>` a trigger character besides for this feature? If it was the only reason, then there's also the nice side effect that it will trigger less auto completions.

**Comment by jasonlyu123** [comment] 2023-03-03 08:05
`>` is for emmet. It existed before the language-tools days.  So we can skip HTML and only return the emmet result.

**Closed** 2023-03-10 02:38 UTC
Labels: bug, Fixed, upstream
