### ISSUE TITLE
Error using beforeunload and popstate on <svelte:window>

### ISSUE THREAD

**Issue by caroso1222** [sveltejs/language-tools#391] opened 2020-07-30 23:09 UTC
**Describe the bug**
`beforeunload` and `popstate` are valid events that can be listened on the `window`. However, there's no TS support when using it on `<svelte:window>`.

**To Reproduce**
```
<script lang="ts">
    function beforeunload(event: BeforeUnloadEvent) {
        event.preventDefault();
        return event.returnValue = '';
    }
</script>
<svelte:window on:beforeunload={beforeunload}/>
```

The snippet above marks `on:beforeunload` as an invalid prop and throws the following error:

```
Property 'onbeforeunload' does not exist on type 'HTMLProps<Window> & SvelteWindowProps'
```

**Expected behavior**
No error should show up as these props are valid window events.

**System (please complete the following information):**
 - OS: macOS Catalina v10.15.4
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by dummdidumm** [comment] 2020-07-31 10:48
Duplicate of #393

**Closed by dummdidumm** 2020-07-31 10:48 UTC
Labels: bug
