### ISSUE TITLE
No warning or error on missing prop

### ISSUE THREAD

**Issue by LexRiver** [sveltejs/language-tools#948] opened 2021-04-17 17:01 UTC
**Describe the bug**
No warning or error when missing prop

**To Reproduce**
https://svelte.dev/examples#declaring-props

App.svelte
```svelte
<script>
	import Nested from './Nested.svelte';
</script>

<Nested />
```

Nested.svelte
```svelte
<script>
	export let answer;
</script>

<p>The answer is {answer}</p>
```
So using `<Nested />` without property `answer` is not highlighted as an error.
I think it should be warning or error here especially if no default value for `export let answer;`

I'm using https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by dummdidumm** [comment] 2021-04-17 17:07
Are you using TypeScript? If so:

Duplicate of #847 . Quoting the relevant bit: 

> This is a decision from the early days that bites us now. Essentially, we decided to make props optional if the strict compilerOption is not set. I'd very much like to revisit this decision and change it so that properties that have no initializer are treated as being required, which would make this work as expected for you (no | undefined).

If not: JS projects aren't type checked by default, that's the same behavior as for normal JS. I do get though that it would be nice to have at least a warning

**Comment by LexRiver** [comment] 2021-04-17 18:22
@dummdidumm `strict` mode helps, thank you.
So maybe that should be default `compilerOptions` when converting by `scripts/setupTypeScript.js`?

**Comment by dummdidumm** [comment] 2021-04-17 18:32
Ok so you are using TypeScript. I'm going to close this as a duplicate then. The linked issue will track the change in behavior, not sure when it will land though.

**Closed by dummdidumm** 2021-04-17 18:32 UTC
Labels: bug
