### ISSUE TITLE
Types from non svelte files don't update - Neovim

### ISSUE THREAD

**Issue by NiloDrumond** [sveltejs/language-tools#2124] opened 2023-08-10 19:27 UTC
### Describe the bug

I have a .svelte file importing an instance of a class from a .ts file. Any changes I make to that class are not reflected on the .svelte file unless I restart the language server.

### Reproduction

Using Neovim with built-in LSP and Mason to install svelte-language-server.
1. Export something from a .ts file
2. Import it on a .svelte file
3. Change this something from the .ts file
4. The type of that something on the .svelte file does not update

### Expected behaviour

It is expected that changing an export from a file should reflect on the files that are importing it.

### System Info

- OS: Linux
- IDE: Neovim
- Node: v16.15.1

### Which package is the issue about?

svelte-language-server

### Additional Information, eg. Screenshots

From the image, you can see that I added another field to this function's arguments (and saved the changes, of course). The svelte file however does not recognize this change until I restart the language server.
![image](https://github.com/sveltejs/language-tools/assets/48765760/cd7e5a45-995b-4f2d-b063-ec32038f6d83)

**Comment by jasonlyu123** [comment] 2023-08-10 22:58
Duplicate of #2008. You can try updating the language server to the latest version and neovim to the latest nightly version.

**Closed** 2023-08-10 22:59 UTC
Labels: bug
