### ISSUE TITLE
Formatter never finishes

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/language-tools#341] opened 2020-07-23 20:29 UTC
**Describe the bug**
The bug described in #115 seems to be back.
When I try to save changes to a .svelte file I get a dialog that says "Saving 'Whatever.svelte': Running 'Svelte for VS Code' Formatter".
My changes are not saved unless I click the "Cancel" button in the dialog.
I have an empty `tsconfig.json` file in the root of my project and I do not have a `tsconfig.json` in my home directory.

**To Reproduce**
For me it happens when I try to save changes to any .svelte file.

**Expected behavior**
Format the code and save the file in a second or two.

**Screenshots**
![Screen Shot 2020-07-23 at 3 27 39 PM](https://user-images.githubusercontent.com/79312/88335550-1df8f780-ccf9-11ea-8ccb-f785a6ac4610.png)

**System (please complete the following information):**
 - OS: macOS
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by mvolkmann** [comment] 2020-07-23 20:44
When this happens I see one or more processes named "Code Helper (Renderer)" that take 99 to 100% of a CPU. I have to quit VS Code and manually kill each of those processes to get the fans on my laptop to settle down.

**Comment by mvolkmann** [comment] 2020-07-23 21:39
The problem goes away if I disable "Editor: Format On Save" in VS Code, but I want to keep that enabled.

**Comment by mvolkmann** [comment] 2020-07-24 17:40
Actually even disabling "Editor: Format On Save" wasn't enough. Doing that makes the dialog go away, but I still get "Code Helper (Renderer)" processes with high CPU usage. The only solution so far is to disable the "Svelte for VS Code" extension.

**Comment by dummdidumm** [comment] 2020-07-25 06:21
Seems like the same problem last time - that somehow too many files are loaded. Could you check the output view and paste everything except the out of memory error (if it's that error again)?

**Comment by YogliB** [comment] 2020-07-25 09:18
any way around this?

**Comment by dummdidumm** [comment] 2020-07-25 17:05
We need more info to know what's goind on. @mvolkmann @YogliB if you could paste your output from VSCode's output->Svelte, that would be great.

**Comment by mvolkmann** [comment] 2020-07-25 19:00
Should I have a svelte.config.js file?

Here is the output:

Initialize language server at  /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/ui/src/App.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/ui/src/Password.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess
Initialize new ts service at  /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/tsconfig.json
SnapshotManager File Statistics:
Project files: 8
Svelte files: 0
From node_modules: 0
Total: 8
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/ui/src/MessageDialog.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/ui/src/Dialog.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/svelte-account-demo/ui/src/Icon.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess

**Comment by dummdidumm** [comment] 2020-07-25 19:36
Ok so seems it's not the same error as last time. Does this happen in every svelte project/file or only specific projects files? If so, could you specify them?

You only need a `svelte.config.js` if you use anything else than js/css/html in your svelte components.

**Comment by mvolkmann** [comment] 2020-07-25 23:05
I've made some progress on tracking this down. It does not happen with a fresh project created from `npx degit sveltejs/template`. But I can reproduce the problem in a project that contains a single file with very little in it. My test project only has a `src` directory and that only contains the file `Icon.svelte`. Here is the contents of that file:

```html
<script>
  //   import * as solid from '@fortawesome/free-solid-svg-icons';
  //
  //   :global(.icon) {
  //     color: green;
  //   }
</script>

<div>Hello</div>
```

Note that all the lines inside the `script` tag are commented out. It seems like something is parsing those lines anyway and doing something that drives the CPU usage of the "Code Helper (Renderer)" process to 100%.

Here is the output from the "Svelte for VS Code" extension in this small project:

Initialize language server at  /Users/mark/Documents/programming/languages/javascript/svelte/delete-me
Trying to load config for /Users/mark/Documents/programming/languages/javascript/svelte/delete-me/src/Icon.svelte
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v3.9.12 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte-preprocess
Initialize new ts service at

Note how that last line is incomplete. It stays like that for about 45 seconds and then outputs this:

SnapshotManager File Statistics:
Project files: 0
Svelte files: 0
From node_modules: 0
Total: 0
Using Svelte v3.24.0 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte/compiler
Using Svelte v3.24.0 from /Users/mark/.vscode/extensions/svelte.svelte-vscode-101.3.0/node_modules/svelte/compiler

Then the CPU usage drops. So the question is what is it doing for those 45 seconds and what do the commented lines have to do with that.

**Comment by dummdidumm** [comment] 2020-07-26 07:44
Probably same cause as #337 then, I guess it's a regex taking too long.

**Comment by mvolkmann** [comment] 2020-07-26 12:07
Maybe there needs to be a step before the content of a file is processed where all comments are removed.

**Comment by dummdidumm** [comment] 2020-07-27 07:07
Duplicate of #337

**Closed by dummdidumm** 2020-07-27 07:07 UTC
Labels: bug
