### ISSUE TITLE
Configuring VS Code to organize imports breaks file saves under certain circumstances

### ISSUE THREAD

**Issue by dslatkin** [sveltejs/language-tools#1719] opened 2022-11-10 19:15 UTC
### Describe the bug

After configuring VS Code to automatically organize imports on save, certain common circumstances using the Svelte extension will break trying to save changes on a file. I originally discovered this in a dev container running in the cloud on Linux on x86 with a more complicated repo. It reproduces locally on Mac with arm64.

### Reproduction

You can skip steps 1-6 if you start from [this repo](https://github.com/dslatkin/svelte-vscode-issue).

1. `npm init svelte`
2. Create the demo project and all default options
3. `npm install`
4. Add the following to `/.vscode/settings.json`:
    ```json
    {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
    ```
5. Save a new route at `/src/routes/demo/+page.svelte` with:
    ```html
    <script context="module">
        import { dev } from '$app/environment';
        // import { setContext } from 'svelte';
    </script>
    
    <script>
        // const context = setContext('test', 'example');
        // console.log(`context is ${context}`)
    </script>
    
    <p>In dev? {dev}</p>
    ```
6. `npm run dev` if you want to verify `/demo` is working
7. Uncomment the commented lines above
8. **ATTEMPT** a save; notice the file can't save, is difficult to close, and syntax highlighting is broken

### Expected behaviour

I would expect that I could use this VS Code setting to organize imports with Svelte.

### System Info

- OS: Mac, Linux devcontainer
- IDE: VS Code

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

This is what the file looks like with syntax highlighting broken after save:

<img width="512" alt="CleanShot 2022-11-10 at 11 14 08@2x" src="https://user-images.githubusercontent.com/9263640/201185872-9f1da435-1e03-4d14-81a3-397765511f3a.png">

**Comment by jasonlyu123** [comment] 2022-11-11 00:46
Duplicate of #1703 #1710 #1712 #1713. This is an upstream issue that is fixed in VSCode 1.73.1.

**Closed by jasonlyu123** 2022-11-11 00:46 UTC
Labels: bug
