### ISSUE TITLE
Type safety for two way binding

### ISSUE THREAD

**Issue by seancolsen** [sveltejs/language-tools#1420] opened 2022-03-22 20:51 UTC
## Problem

- Let's say I have a `NumberInput.svelte` component which accepts user input, somewhat like `<input type="number"/>`

    ```svelte
    <script lang="ts">
      export let value: number | null = null;

      // etc...
    </script>

    <!-- 
      etc...
    -->
    ```

    Notice that **`value` has type `number | null`** because it becomes `null` when the user clears the contents of the input field.

- Now I use that component inside `MyForm.svelte` as follows:

    ```svelte
    <script lang="ts">
      import NumberInput from './NumberInput.svelte';

      let quantity = 1;
    </script>

    <NumberInput bind:value={quantity} />
    <!--                     ^^^^^^^^  I would like to see an error here.
    -->
    ```

    Here **`quantity` has type `number`**.

- Currently this code does not produce any type errors. That's problematic because the two way binding may set `quantity` to `null` at runtime, and it's hard to see that from within `MyForm.svelte`.

## Proposed solution

- I'd like to see a type error at the specified location because `quantity` has type `number` whereas `value` has type `number | null`.

- I would fix the type error inside `MyForm.svelte` as follows:

    ```svelte
    let quantity: number | null = 1;
    ```

## Alternate solutions

- Perhaps the type of `quantity` could be inferred to be `number | null`. I'm not sure though.
- I'm open to other approaches or other advice on how people have solved similar issues.

**Comment by dummdidumm** [comment] 2022-03-23 08:49
Duplicate of #1392 (although I like your title much better, so I updated it in #1392)

**Closed by dummdidumm** 2022-03-23 08:49 UTC
