### ISSUE TITLE
`svelte-check` not ignoring excluded files in certain cases.

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/language-tools#2430] opened 2024-07-02 23:54 UTC
### Describe the bug

According to the docs, `svelte-check` should ignore files that are excluded by `tsconfig.json`.
However this is not always working when using bun as a package manager and linked packages.

### Reproduction

1. create an external package: `mkdir /tmp/my-pkg/ && cd /tmp/my-pkg && bun init .` 
2. add some non-sense to the `index.ts` to trigger an error: `echo 'ThisIsWrong' > index.ts` 
3. make the package available on the host machine: `bun link`
4. create a new svelte project: `mkdir /tmp/app && cd /tmp/app && bun create svelte@latest`; (use skeleton project and enable Typescript)
5. add the external reference: `bun link my-pkg && bun install`
6. reference the external package: `echo 'import * from "my-pkg"' > src/lib/index.ts`
7. add `exclude: [ "my-pkg/**", "../my-pkg/**", "my-pkg", "node_modules/" ]` to your `tsconfig.json`
8. run `bun run check` and see it fail caused by the error in our external package ("/tmp/app/../my-pkg/index.ts").

### Expected behaviour

`svelte-check` should ignore the errors in the file since they match the pattern in tsconfig's exclude list.

### System Info

- OS: Linux
- IDE: VSCode

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

- I didn't make a repository, since this requires two packages to demonstrate. Please follow the commands above.
- I dug a bit into this and it seems that [here](https://github.com/sveltejs/language-tools/blob/027ab23e3e59939ad1f018a34ca5e0386cbaf829/packages/language-server/src/svelte-check.ts#L198) the files of the external package are still in the list of files to be checked.
- To my understanding, [here](url) is where it is decided if we check the file or not. I don't know if this happened earlier in the code maybe but I think this is where the files should be removed. Or even better, maybe in [L198](https://github.com/sveltejs/language-tools/blob/027ab23e3e59939ad1f018a34ca5e0386cbaf829/packages/language-server/src/svelte-check.ts#L198) already?

**Comment by jasonlyu123** [comment] 2024-07-03 01:22
`exclude` does not prevent files from being loaded. It prevents files from being an entry point. Files will still be loaded if it is referenced through import. This behaviour is in line with `tsc` so I'll say this works as intended. This is usually solved by using the `skipLibCheck` option but this only applies to `.d.ts` files and there aren't equivalent options for ts files. I don't know if there is a way to work around it. Your best option is probably just to contact the author to fix the error.

**Comment by ptrxyz** [comment] 2024-07-03 09:11
Thanks for the answer, I guess you are right then. I misunderstood the meaning of `exclude`.
I have `skipLibCheck` enabled and just as you pointed out it doesn't work. 

I assume this is only a problem with "bad" libraries then. Not sure if this is a common problem or just me. But if it's more common could we enable the "ignore" flag also for cases where a `tsconfig.json` is specified? Or maybe some "--force-ignore" or so in that matter?

**Comment by dummdidumm** [comment] 2024-07-03 09:15
Yeah in practise `skipLibCheck` helps you for "bad libraries" (and the library itself should probably fix its types). Ignoring a `.ts` file is out of the question.

I'm against adding a `--force-ignore` option or something similar in order to keep `svelte-check` as closely aligned with TypeScript's `tsc` type checking semantics. Therefore closing.

**Closed by dummdidumm** 2024-07-03 09:15 UTC
Labels: question
