### ISSUE TITLE
Formatting of angle brackets

### ISSUE THREAD

**Issue by techniq** [sveltejs/language-tools#1472] opened 2022-05-03 18:03 UTC
### Describe the bug

This one has plagued me for a while, but I think I might have somewhat boiled it down.   It appears formatting custom components (ex. `<Button>`) handles closing angle brackets (`>`) differently than "some" DOM elements (ex. `<div>` but not `<button>`).

### Reproduction

For example, I'll end up with something like this quite often (note the closing angle bracket `>` of the opening `<Button>` tag).

<img width="537" alt="image" src="https://user-images.githubusercontent.com/177476/166510181-27fbd33e-84e2-436a-9c91-58a664cbe9f5.png">

If I change the `<Button>` to a `<div>` and save/format, I get what I expected:
- Alignment of `>` with opening tag
- Inner text (Click me) on it's own line
- Closing tag on it's own line
<img width="549" alt="image" src="https://user-images.githubusercontent.com/177476/166509810-f6b57882-2ae3-463a-85d6-e84ffba7068d.png">

Back to the original `<Button>` example, if I add a carriage return before "Click me"...

<img width="545" alt="image" src="https://user-images.githubusercontent.com/177476/166510298-286149af-ea9d-4f3b-9411-aa9c4abf88f5.png">

and save/format, it fixes the opening tag's `>` but not the closing tag

<img width="555" alt="image" src="https://user-images.githubusercontent.com/177476/166510407-ab45b37d-631f-47f8-8e1a-7cc9786aa5e5.png">

If I then add a carriage return before the closing tag...

<img width="539" alt="image" src="https://user-images.githubusercontent.com/177476/166510570-406341e9-6c31-4f02-a6ea-510d8219462e.png">

and save/format, it fixes the closing tag completely...

<img width="542" alt="image" src="https://user-images.githubusercontent.com/177476/166510735-a706ef72-eb88-4e5d-93cf-a03dc9a6edd9.png">

Also, if I have it all on one line to start...

<img width="857" alt="image" src="https://user-images.githubusercontent.com/177476/166511159-33c83c34-0dab-48af-ab7a-c4af06d1ecfa.png">

and save/format, it gives me the original issue

<img width="560" alt="image" src="https://user-images.githubusercontent.com/177476/166511256-1200d847-5e10-4017-bc3f-47893a250859.png">

It's also interestingly that once manually fixed, it doesn't return to the original / broken example (luckily).

Also using `<button>` instead of `<div>` breaks like `<Button>`.  Actually, a handful of DOM elements seem to work as expected.  A quick tests results in the following:

## works as expected
- `<div>`
- `<main>`

## broken
- `<Button>`
- `<a>`
- `<span>`

### Expected behaviour

<img width="858" alt="image" src="https://user-images.githubusercontent.com/177476/166513115-2ad05da6-91a1-4a85-8904-795e122720d2.png">

should format as 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/177476/166513317-77a1096f-dc53-4eea-8c04-68345d181d72.png">

and not as 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/177476/166513447-71dfafb5-c3a5-4667-9e77-52634c33ac29.png">

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code

**Comment by dummdidumm** [comment] 2022-05-03 20:08
See https://github.com/sveltejs/prettier-plugin-svelte/blob/master/README.md#why-is-the-closing-or-opening-tag--or--hugging-the-inner-tag-or-text , this is expected behavior due to whitespace sensitivity. You can switch that behavior through the mentioned option in the link.

**Closed by dummdidumm** 2022-05-03 20:08 UTC
Labels: bug

**Comment by techniq** [comment] 2022-05-04 12:11
@dummdidumm That's it, thanks for the tip (and sorry I later realized the prettier plugin has it's own [repo](https://github.com/sveltejs/prettier-plugin-svelte)).

One thing that always surprised me is with React, the default appears to always ignore the whitespace.

Before
<img width="702" alt="image" src="https://user-images.githubusercontent.com/177476/166677414-431a6f69-261c-41f0-a07b-6d229f0c93f5.png">

After
<img width="626" alt="image" src="https://user-images.githubusercontent.com/177476/166677443-2e5628c0-6d7e-42c0-b4b7-930a3076599e.png">

Even using the [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAogB4CGAtgA4A2cAFAJT7AA6U++ATnDOp+3TYcOAHgDOlUlAB84yTIAqACxxj8q-GIjk4+AG5xOAT3zVoAc3zxiMKxE1xdSiAHd8LlfAmkwujUqkAE1pAkQB6bxlwyOkhfAYAbjYAXzYQABoQCEpcaDFkUFJOTlcABSKEfJRSahdSI3zMgCNOHwBrHgBlCjgAGRwoOGRUGrE4ZtawDphOyTAB82QYTnRxkDhyJrhAwO3eqXN0UnM4ADEITnJSGFwoRer0GAgMkCUYcmoAdU84b19Oyo4XB6IFGZDgMSNEADMacGClVrmK7DUZrABWYmInQWtAAiugIPAUdQxplJJxYeCmqQttQXpROAMYJ8cIEYEpkAAOAAMZJKY0+rUo4IZv0MBheAEcCfAEdkqiBSGIALSDbbbF7caU4bgI47IpAjElrMbkHBLFYmnFwfGEoaG1GZGA0llsjlIABMTtaOGoCwAwtoDesxABWF7oMYKGlVI2kkB6VYASSgu1gnTAjJyAEFU50YEZaMSxslkkA), changing the `--html-whitespace-sensitivity` seems to have no affect.  Maybe this is due to a fundamental difference between Svelte and React?  I know React prettier likes to insert `{' '}` which feel like the `&nbsp;` of React :)

<img width="251" alt="image" src="https://user-images.githubusercontent.com/177476/166678148-95c26c63-2c87-4720-87ce-4734f0486383.png">

One of my large React applications has over 260 of these when I just checked :)

**Comment by dummdidumm** [comment] 2022-05-04 13:01
JSX != HTML. They chose to ignore whitespaces in all cases, which is why you need those `{' '}` if you want them
