### ISSUE TITLE
The type of `<svelte:self>` seems to be `any` making it possible to pass any props

### ISSUE THREAD

**Issue by Ennoriel** [sveltejs/language-tools#2291] opened 2024-02-16 08:21 UTC
### Describe the bug

The type of `<svelte:self>` seems to be `any` making it possible to pass any props.

Replacing `svelte:self` with `svelte:component` and importing the component itself works as expected

### Reproduction

https://github.com/Ennoriel/bug-svelte-self

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 2.05 GB / 15.69 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^4.2.7 => 4.2.11
```

### Severity

annoyance

**Comment by brunnerh** [comment] 2024-09-12 09:59
Duplicate of:
- #1229

**Closed** 2024-09-12 10:14 UTC
Labels: feature request
