### ISSUE TITLE
type declaration without ending semicolon last in script block breaks syntax highlighting (again)

### ISSUE THREAD

**Issue by thepuzzlemaster** [sveltejs/language-tools#2458] opened 2024-08-06 21:20 UTC
### Describe the bug

I am experiencing the exact same symptoms from https://github.com/sveltejs/language-tools/issues/1970

Inside my script tags, if the last line is a type declaration, it breaks syntax highlighting for the rest of the file if there is no semicolon.

Prior bug claimed this was fixed in vscode 1.78
I'm using vscode 1.92.0

This is my first svelte project, so I have no prior history to reference.

### Reproduction

_component.svelte_
```
<script lang="ts">
  
  type $$Props = {}
</script>

<div>My component</div>
```

<img width="394" alt="image" src="https://github.com/user-attachments/assets/2896ae70-c3be-4be9-83b8-24a1b6d4f25a">

### Expected behaviour

(but without the semicolon)
<img width="373" alt="image" src="https://github.com/user-attachments/assets/40a2fca5-6869-4ac4-affb-d98c9bdd1e43">

### System Info

- OS: M1 Max Macbook Pro OS 14.3
- IDE: VSCode 1.92

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2024-08-07 01:35
This isn't a regression for #1970 but a duplicate of #1110. This is an upstream limitation in https://github.com/microsoft/TypeScript-TmLanguage. VSCode uses TextMate format for syntax highlight, but the format has capability limitations and will likely never be fixed upstream.

**Closed by jasonlyu123** 2024-08-07 01:35 UTC
Labels: bug
