### ISSUE TITLE
Add option to fold import statements - VS Code Extension

### ISSUE THREAD

**Issue by fev4** [sveltejs/language-tools#2037] opened 2023-05-27 02:04 UTC
### Description

Hey there!

Sometimes imports can get really long and it takes a couple of scrolls to get to the actual start of the code within a `script` tag.

VS Code has an option called:
```
"editor.foldingImportsByDefault": true
```
But this doesn't seem to work.

### Proposed solution

It would be nice to be able to auto-fold after a certain number of import statements (let's say 5), and then they are auto-folded. Or even being able to fold manually or with a keyboard shortcut would be perfect.

This would make getting to the code a little faster.

### Alternatives

As mentioned, VS Code has an option for folding imports, but this doesn't work. Aside from that I haven't found an extension to fold imports in Svelte files.

I'm also able to fold the entire `script` tag with `Ctrl+Shift+[`, but this is not useful for the problem described here.

### Additional Information, eg. Screenshots

Here's an example of one the files I have where the import statements take the first full page:

![image](https://github.com/sveltejs/language-tools/assets/16828078/1a9050f8-ceaa-4ed7-ba05-fda5b2f2f380)

These are the folds available:
![image](https://github.com/sveltejs/language-tools/assets/16828078/4c1d5a21-3175-4073-935e-3186bcd6f77b)

This is a nice to have, nothing critical.

Thanks for reading.

**Comment by jasonlyu123** [comment] 2023-05-27 03:12
Closing as duplicate of #1704. The current folding is indentation based provided by VSCode. This should work as expected once we provide a more "semantic" folding range support.

**Closed by jasonlyu123** 2023-05-27 03:12 UTC
