### ISSUE TITLE
Using $$Events corrupts component's props typing

### ISSUE THREAD

**Issue by 7nik** [sveltejs/language-tools#1690] opened 2022-10-18 17:14 UTC
### Describe the bug

If a component has manually defined event types via `interface $$Events`, the component props get incorrectly typed, and even more, the component type cannot be cast to `SvelteComponentTyped<any, any, any>`

### Reproduction

```html
<script lang="ts">
    import type {  ComponentProps, ComponentType } from "svelte";
    // import itself
    import type Test from "./Test.svelte";

    interface $$Events {
        test: CustomEvent<null>
    }

    export let param: string;

    // Props is `never` instead of `{ param: string }`
    type Props = ComponentProps<Test>; 
    // Error: Type 'Test__SvelteComponent_' does not satisfy the constraint 'SvelteComponentTyped<any, any, any>'
    type Constructor = ComponentType<Test>; 
</script>
{param}
```

### Expected behaviour

The Props type is `{ param: string }` and the component with `$$Events` can be cast to `SvelteComponentTyped`.

### System Info

Code - OSS
Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-06T22:56:30.304Z
Electron: 19.0.13
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.217-1-MANJARO
Sandboxed: No

Svelte for VS Code: v106.2.0

**Comment by dummdidumm** [comment] 2022-10-18 17:27
What do you mean by this line?
```js
    // import itself
    import type Test from "./Test.svelte";
```

**Comment by 7nik** [comment] 2022-10-18 17:40
No, you can import itself - https://svelte.dev/repl/8eb937738eb84a1fa3c48776e5f0b70b?version=3.52.0

Talking about importing its own type - well, at least there are no errors when you comment the `$$Events`

**Comment by dummdidumm** [comment] 2022-10-18 17:58
You should use `<svelte:self>` for that. I'm also talking about the typing perspective. The following typescript snippet isn't type-checkeable, because the return type isn't set specifically:
```ts
function foo(i: number) {
  return foo(i - 1);
}
// type error: 'foo' implicitly has return type 'any' because it does not have a return type annotation
// and is referenced directly or indirectly in one of its return expressions
```

The same happens in your above example. The type of the component isn't determined yet but you are already using it.

**Comment by 7nik** [comment] 2022-10-18 18:20
You can use `<svelte:self>` only in the markup. But, if you want to define in the `context="module"` a function for creating the current component, and optionally even a singleton, you must use self-import. Anyway, self-import is just a simplification for reproduction.

In my initial case, I used `$$Events` to correct the type of the forwarded event from a generic to a certain one (maybe it is also a bug because if I add a local handler, it has the correct type, but the forwarded event keeps being generic). But then I was faced with the problem that my function for creating components started to complain about typings.

As a workaround, I can use
```ts
    createEventDispatcher<{
        test: null, // or another type
    }>();
```
this also corrects the event type to what I need, but it's a workaround.

**Comment by jasonlyu123** [comment] 2023-02-24 09:45
Not sure what fixes this. But This is fixed in the latest version. I can reproduce it in v106.2.0 but not the latest version. I am closing this. If you still have problems feel let us know.

**Closed by jasonlyu123** 2023-02-24 09:45 UTC
Labels: bug
