### ISSUE TITLE
--ignore <path1,path2> is not ignoring paths

### ISSUE THREAD

**Issue by amunrarara** [sveltejs/language-tools#1573] opened 2022-08-03 03:46 UTC
### Describe the bug

When running ```svelte-check``` with the ```--ignore``` flag, it is not actually ignoring the paths I've specified. I'm running it as a package.json script, using yarn. Please see "Reproduction" for the exact command.

### Reproduction

```
//package.json
{
   "scripts": {
      ...
      "scheck": "yarn scheck:base --tsconfig ./tsconfig.json",
      "scheck:base": "svelte-check --threshold warning --fail-on-warnings --ignore \"src/routes/spike,src/routes/dev,src/lib/vendor\"",
      ...
}}
```
```
//tsconfig.json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "strict": true,
  }
}
```

### Expected behaviour

The paths specified following ```--ignore``` should be ignored

### System Info

- OS: MacOS Big Sur 11.6.4
- IDE: VSCode

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment] 2022-08-03 07:42
Duplicate of #1495

**Closed by dummdidumm** 2022-08-03 07:42 UTC
Labels: bug
