### ISSUE TITLE
{#snippet ...} are not resolved

### ISSUE THREAD

**Issue by Dudek-AMS** [sveltejs/language-tools#2404] opened 2024-06-17 07:52 UTC
### Describe the bug

![image](https://github.com/sveltejs/language-tools/assets/100142218/2bc8c504-a40e-40a2-875f-85486f226aff)

### Reproduction

```html
{#snippet snippetDefaultIcon()}<div class="mr-2">
<svelte:component this={defaultIcons[status]} />
</div>
{/snippet}
```

### Expected behaviour

defined snippets dont throw a unresolved error

### System Info

- OS: Window 11
- IDE: Intellij
Language Server: 0.16.10
Typescript Svelte Plugin 0.3.38
![image](https://github.com/sveltejs/language-tools/assets/100142218/f3e094b4-b35e-43c8-a936-3cee354841ff)

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment] 2024-06-17 19:42
Closing as duplicate of #2403  because I'm pretty sure it's the same underlying cause. If not we can reopen later.

**Closed by dummdidumm** 2024-06-17 19:42 UTC
Labels: bug
