### ISSUE TITLE
Exports declared in between imports are deleted when sorting/organising imports

### ISSUE THREAD

**Issue by sidharthv96** [sveltejs/language-tools#2178] opened 2023-10-13 03:52 UTC
### Describe the bug

During a bulk cleanup of a repo, I tried to organise imports in all files, by adding the following config in `settings.json` and then doing a replace of `import ` with `import `. 

```
  "editor.codeActionsOnSave": {
    "source.fixAll": "always",
    "source.organizeImports": "always",
    "source.sortImports": "always" // Also tried this
  }
```

There were 100s of files changed, but few of them had errors. 
Looking into them, they initially had an `export ` statement sandwiched in between the imports at the top. 
And the sort/organise action deleted that export instead of moving it below the import block. 

### Reproduction

```
<script lang="ts">
  import { goto } from '$app/navigation';
  import Component2 from '$components/Component.svelte';
  export let prop: string;
  import Component from '<path>';

  export let prop2: number;
```

becomes after saving

```
<script lang="ts">
  import { goto } from '$app/navigation';
  import Component from '$components/Component.svelte';
  import Component2 from '<path>';

  export let prop2: number;
```

### Expected behaviour

```
<script lang="ts">
  import { goto } from '$app/navigation';
  import Component2 from '$components/Component.svelte';
  import Component from '<path>';

  export let prop: string;
  export let prop2: number;
```

### System Info

- OS: macOS
- IDE: VSCode

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment] 2023-10-13 03:58
Duplicate of https://github.com/sveltejs/language-tools/issues/1590. This is a limitation for which we have yet to find a workaround.

**Closed by jasonlyu123** 2023-10-13 03:58 UTC
Labels: bug

**Comment by sidharthv96** [comment] 2023-10-13 04:10
Sorry, I searched with [these keywords](https://github.com/sveltejs/language-tools/issues?q=is%3Aissue+sort+delete+export+is%3Aclosed), and that issue didn't show up. 😅
