### ISSUE TITLE
Prop with a single apostrophe followed by on: directive leads to syntax error

### ISSUE THREAD

**Issue by rudolfs** [sveltejs/language-tools#1185] opened 2021-09-28 16:39 UTC
**Describe the bug**

When a component has a prop which contains a single apostrophe followed by an `on:` directive, the language server reports a syntax error.

**To Reproduce**

```svelte
<script lang="typescript">
  import EmptyComponent from "EmptyComponent.svelte";
</script>

<EmptyComponent title="'" on:click={() => {}} />
```

**Expected behavior**
No error should be shown, it is valid syntax.

**Screenshots**

<img width="546" alt="Screenshot 2021-09-28 at 18 34 24" src="https://user-images.githubusercontent.com/158411/135128712-61ab74c7-087a-4b94-8b44-2df7f3c76811.png">

**System (please complete the following information):**
 - OS: macOS
 - IDE: neovim v0.5.0
 - Plugin/Package: "evanleck/vim-svelte", "'neoclide/coc.nvim", "coc-svelte 0.3.0"

**Comment by dummdidumm** [comment] 2021-09-29 07:30
Duplicate of #1153 . This was fixed a while ago. Your package probably uses an outdated version of `svelte-language-server` and `svelte2tsx`. If possible, update the two and it should work as expected.

**Closed by dummdidumm** 2021-09-29 07:30 UTC
Labels: bug
