### ISSUE TITLE
svelte-check: update svelte-preprocess to fix npm warn deprecated?

### ISSUE THREAD

**Issue by lts20050703** [sveltejs/language-tools#2408] opened 2024-06-21 04:03 UTC
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

---

`npm list inflight`
```
└─┬ svelte-check@3.8.1
  └─┬ svelte-preprocess@5.1.4
    └─┬ sorcery@0.11.1
      └─┬ sander@0.5.1
        └─┬ rimraf@2.7.1
          └─┬ glob@7.2.3
            └── inflight@1.0.6
```

**Comment by jasonlyu123** [comment] 2024-06-21 04:24
Duplicate of #2401 and #2391

**Closed by jasonlyu123** 2024-06-21 04:24 UTC
