### ISSUE TITLE
Global SCSS variables

### ISSUE THREAD

**Issue by daarxwalker** [sveltejs/language-tools#232] opened 2020-06-26 15:00 UTC
Hey guys,
have a one little problem. I tried to have global SCSS variables. Compilation works, but extension seems not. I get it, when importing nothing, it doesn't know about variables.
I added this to rollup.config.js as argument to autoPreprocess():
```javascript
const autoPreprocessConfig = {
	scss: { includePaths: ['src/styles'], data: '@import "theme";' },
	postcss: {
		plugins: [ require('autoprefixer') ],
	},
}
```
In svelte.config.js doesn't work, so that's why rollup.config.js.
I have file _theme.scss in included path, as I said, compilation works.
But when I use variables like this:
```scss
<style type="text/scss">
    .test {
        color: $color-primary;
    }
</style>
```
..it shows at the beggining of component this
```text
The file cannot be parsed because script or style require a preprocessor that doesn't seem to be setup.
Did you setup a `svelte.config.js`?
See https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#using-with-preprocessors for more info.
```

**Comment by dummdidumm** [comment] 2020-06-26 15:21
Did you follow the [instructions for SCSS](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/docs/preprocessors/scss.md)? Especially the last point (setting node path) might be what you need to do.

**Comment by daarxwalker** [comment] 2020-06-26 15:27
![Snímek obrazovky 2020-06-26 v 17 26 35](https://user-images.githubusercontent.com/26570413/85873969-321d0800-b7d2-11ea-83d6-17f1f6b58439.png)

You mean this, right?

**Comment by daarxwalker** [comment] 2020-06-26 15:33
Really dunno what to do. Any idea?

**Comment by daarxwalker** [comment] 2020-06-26 15:38
Need something like global reference to variables, so extension will know about it + autocompleting.

**Comment by dummdidumm** [comment] 2020-06-26 15:56
You need to have the same preprocessor config setup in your `svelte.config.js` as in your `rollup.config.js`.

**Comment by daarxwalker** [comment] 2020-06-26 15:59
I did it. Still same warning. Same preprocess config in svetle.config.js && rollup.config.js (client && server)
![Snímek obrazovky 2020-06-26 v 17 58 08](https://user-images.githubusercontent.com/26570413/85876850-993cbb80-b7d6-11ea-9a2e-aa599d88c8a6.png)
![Snímek obrazovky 2020-06-26 v 17 58 19](https://user-images.githubusercontent.com/26570413/85876874-9fcb3300-b7d6-11ea-8bc8-567c0e82dbe7.png)

**Comment by daarxwalker** [comment] 2020-06-26 16:03
Restarted lang-server, restarted vscode, nothing changed, still warning in componen.

**Comment by daarxwalker** [comment] 2020-06-26 16:04
Looks like the component can't reach variable.
![Snímek obrazovky 2020-06-26 v 18 04 11](https://user-images.githubusercontent.com/26570413/85877432-71018c80-b7d7-11ea-9cb0-808974216187.png)

**Comment by blindfish3** [comment] 2020-06-26 16:28
@daarxwalker - IIRC includePaths does not by definition make the variables available within all your SCSS code.  It just provides SCSS paths from which imports can be resolved.  So you might typically include node_modules if you know you have dependencies there...

So I think you still need an @import for your dependencies inside your component <style> tag.  I don't have time to confirm in docs yet; but that's what I'd check first ;)

**Comment by daarxwalker** [comment] 2020-06-26 16:35
I know. I tried without data and import, still same message. But it's really pretty not good, if I can't just inject variables to all components in one place. I can live with @import 'theme'; in all components, but it still doesn't work.

**Comment by dummdidumm** [comment] 2020-06-26 16:37
If your build runs fine, this is "just" and IDE intellisense error which we have to fix. So you can continue programming and ignore the error until we have come up with a solution.

**Comment by daarxwalker** [comment] 2020-06-26 16:41
I know, i know. But it's really annoying and I don't know, if I have to do something more in configs. Thanks anyway for guides.

**Comment by dummdidumm** [comment] 2020-06-27 16:18
I cannot reproduce this.

This is what I did:
1. use [svelte starter template](https://github.com/sveltejs/template)
2. `npm i --D svelte-preprocess sass` (note: not `node-sass`, to get around the annoying node environment thing)
3.  add `theme.sccs` inside `src`, content `$bla: blue;`
4. enhance rollup to deal with it
5. create `svelte.config.js` with this:
```js
import autoPreprocess from 'svelte-preprocess';

export const preprocess = autoPreprocess({
  includePaths: ['src'],
});
```
6. add `lang="scss"` to `style` tag in `App.svelte`, add `@import './theme';` at the top and `background: $bla;` to `main` styling.

**Comment by daarxwalker** [comment] 2020-06-27 18:22
@dummdidumm 
- I'm using Sapper with TypeScript.
- yarn add -D sass
- src/styles/_theme.scss
![Snímek obrazovky 2020-06-27 v 20 21 23](https://user-images.githubusercontent.com/26570413/85929277-c6ab6700-b8b3-11ea-8cdc-7debee5d7a2f.png)

- rollup.config.js
![Snímek obrazovky 2020-06-27 v 20 19 55](https://user-images.githubusercontent.com/26570413/85929245-919f1480-b8b3-11ea-8913-df0ba64f2df4.png)
![Snímek obrazovky 2020-06-27 v 20 19 38](https://user-images.githubusercontent.com/26570413/85929238-877d1600-b8b3-11ea-86d6-9f120056b8d0.png)

- svelte.config.js same as rollup.config.js
![Snímek obrazovky 2020-06-27 v 20 21 59](https://user-images.githubusercontent.com/26570413/85929286-ddea5480-b8b3-11ea-8e35-959dd1ab3d4a.png)

- component
![Snímek obrazovky 2020-06-27 v 20 20 17](https://user-images.githubusercontent.com/26570413/85929255-9fed3080-b8b3-11ea-93f5-8a2e4c955300.png)

**Comment by dummdidumm** [comment] 2020-06-28 09:04
You cannot use the new syntax inside the `svelte.config.js`. You need to write it like this:

```js
const autoPreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: autoPreprocess({
    scss: { includePaths: ['src/styles'], data: '@import "theme";' },
    postcss: { plugins: [require('autoprefixer')] }
  }),
};

```

This worked for me.

**Comment by blindfish3** [comment] 2020-06-28 09:18
> * component
>   ![Snímek obrazovky 2020-06-27 v 20 20 17](https://user-images.githubusercontent.com/26570413/85929255-9fed3080-b8b3-11ea-93f5-8a2e4c955300.png)

You still don't have an `@import` statement here

**Comment by daarxwalker** [comment] 2020-06-28 09:33
@dummdidumm You're right about svelte.config.js, warning disappear. What about autocomplete, still not working. Really need to have manual `@import "theme";` in every component or it's in data prop just fine and problem with autocomplete is somewhere else?

@blindfish3 I know. I want it global. It's standard thing with SCSS.

**Comment by dummdidumm** [comment] 2020-06-28 09:43
Since the error went away I'm going to close this. 

Autocomplete is not supported yet, please open another feature request for this.

**Closed by dummdidumm** 2020-06-28 09:43 UTC

**Comment by kjaonline** [comment] 2021-03-18 01:32
This worked for me: 

svelte.config.js
`const autoPreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: autoPreprocess({
    scss: {  prependData: `@import 'src/styles/main.scss';`},
    postcss: { plugins: [require('autoprefixer')] }
  }),
};`

rollup.config.js
`svelte({
            dev: !production, // run-time checks      
            // Extract component CSS — better performance
            css: css => css.write(`bundle.css`),
            hot: isNollup,
            preprocess: [
                autoPreprocess({
                    scss: { prependData: `@import 'src/styles/main.scss';`},
                    postcss: { plugins: [postcssImport()] },
                    defaults: { style: 'postcss' }
                })
            ]
        }),`

App.svelte
`<style global lang="scss">
</style>`

**Comment by babakfp** [comment] 2021-08-04 17:44
Hi
I'm having a great day, working with Svelte
![Screenshot 2021-08-04 104314](https://user-images.githubusercontent.com/44144724/128228809-f107276f-d2e7-42b0-91fb-9b6a4c275fa8.png)
![Screenshot 2021-08-04 103939](https://user-images.githubusercontent.com/44144724/128228534-3aa62998-53aa-488c-88fe-28c1cbd968f3.png)
![Screenshot 2021-08-04 104035](https://user-images.githubusercontent.com/44144724/128228557-ba07b9b9-5f5a-49dc-afa0-b893715af3d0.png)
 
@kjaonline
