### ISSUE TITLE
Renaming .svelte filenames in multiple files causes the (auto)formatter to hang indefinitely

### ISSUE THREAD

**Issue by hanszoons** [sveltejs/language-tools#2075] opened 2023-06-28 07:57 UTC
### Describe the bug

When I rename a .svelte-file or perform a find/replace operation that affects .svelte-filenames that are imported in other components, I receive multiple pop-ups with the message "Saving '<filename>.svelte': Running 'Svelte for VS Code' Formatter." These pop-ups keep spinning endlessly and prevent me from using the code editor. 

![image](https://github.com/sveltejs/language-tools/assets/91126835/81a415c2-5fb8-4d02-83d9-56b9444e3570)

The only solution is to force a full window reload.

![image](https://github.com/sveltejs/language-tools/assets/91126835/e590f1bb-d79c-420e-9149-04e67f2e65c5)

Most of the files that were affected by the find and replace operation will open as "dirty" after performing a full window reload, which is fine, nothing is actually lost.

### Reproduction

* Rename a .svelte file that is imported in other .svelte-files.
* Globally find and replace the old filename to the new file name.

### Expected behaviour

A manual find and replace on imports should not cause any issues.
Renaming the file should perhaps automatically update the imports in other files, so we shouldn't have to resort to find/replace-operations 

### System Info

- OS: MacOS Ventura 13.4.1
- IDE: VSCode 1.79.2
- Extension: Svelte for VS Code 107.6.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by hanszoons** [comment] 2023-06-28 08:12
Yes, this started happening since Svelte 4.

Perhaps it's my memory, but I always thought that imports were updated automatically when I changed a .svelte-filename. I can't remember having to do the find/replace-step after every file rename. Or did that only ever work for .js files?

**Comment by jasonlyu123** [comment] 2023-06-28 08:20
There is currently a performance problem with update import after rename. You have to "search and replace" because it's too slow, and you probably restart the editor before it ever finishes. Since it started happening since Svelte 4, I am going to close this as a duplicate of #2065.

**Closed by jasonlyu123** 2023-06-28 08:20 UTC
Labels: bug
