### ISSUE TITLE
Alias is not resolved

### ISSUE THREAD

**Issue by numfin** [sveltejs/language-tools#468] opened 2020-08-20 18:19 UTC
**Describe the bug**
I used import alias `@/` and it worked. Then i switched to Vite and it supports only root aliases. So i switched my code to use `/@/` aliases. It compiles and works in browser, but gives me an error in vscode:

![image](https://user-images.githubusercontent.com/8134947/90809736-979cf900-e32a-11ea-92f4-6b1911732572.png)

**To Reproduce**
Use `/@/` import

**Expected behavior**
Everything works

**System (please complete the following information):**
 - OS: Ubuntu
 - IDE: VSCode
 - Plugin/Package:"Svelte for VSCode"

**Comment by jasonlyu123** [comment] 2020-08-20 22:37
You'll also have to configure the alias for typescript though tsconfig/jsconfig.json

https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by cayter** [comment] 2020-08-21 05:04
I'm also facing the same issue which `tsc` can compile it just fine. However, when tools like `svelte-check` won't be able to resolve the alias path.

**Comment by jasonlyu123** [comment] 2020-08-21 05:09
That error is because we have used some special property injected by svelte2tsx to do component type-check. If we can't find the actual file we can't transform the file using svelte2tsx.

@cayter where do you put your tsconfig?

**Comment by cayter** [comment] 2020-08-21 05:15
@jasonlyu123 Below is my project folder structure which happens to be a monorepo for both backend/frontend:

```bash
.
├── Brewfile
├── Brewfile.lock.json
├── Makefile
├── README.md
├── database
│   └── database.rules.json
├── firebase.json
├── firestore
│   ├── firestore.indexes.json
│   └── firestore.rules
├── functions
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   │   └── index.ts
│   └── tsconfig.json
├── hosting
│   ├── index.html
│   ├── jest.setup.js
│   ├── package-lock.json
│   ├── package.json
appist $ tree . 
.
├── Makefile
├── README.md
├── database
│   └── database.rules.json
├── firebase.json
├── firestore
│   ├── firestore.indexes.json
│   └── firestore.rules
├── functions
│   ├── package-lock.json
│   ├── package.json
│   ├── src
│   │   └── index.ts
│   └── tsconfig.json
├── hosting
│   ├── index.html
│   ├── jest.setup.js
│   ├── package-lock.json
│   ├── package.json
│   ├── postcss.config.js
│   ├── public
│   │   ├── favicon.ico
│   │   └── robots.txt
│   ├── src
│   │   ├── components
│   │   │   ├── App.svelte
│   │   │   └── ...
│   │   ├── images
│   │   │   ├── cover.png
│   │   │   └── ...
│   │   ├── index.css
│   │   ├── index.d.ts
│   │   ├── index.ts
│   │   ├── initFB.ts
│   │   ├── initSW.ts
│   │   ├── pages
│   │   │   ├── Auth
│   │   │   │   └── ...
│   │   │   ├── Error
│   │   │   │   └── NotFound.svelte
│   │   │   ├── Home
│   │   │   │   └── ...
│   │   │   └── User
│   │   │       └── ...
│   │   └── stores
│   │       ├── app.ts
│   │       ├── auth.ts
│   │       └── router.ts
│   ├── svelte.config.js
│   ├── tailwind.config.js
│   ├── tsconfig.json
│   ├── vite.config.ts
│   └── workbox.config.js
├── package-lock.json
├── package.json
```

**Comment by cayter** [comment] 2020-08-21 05:27
> If we can't find the actual file we can't transform the file using svelte2tsx.

Yep, this is relevant to alias path resolving defined in the project's `tsconfig.json` is not being honoured.

**Comment by cayter** [comment] 2020-08-21 05:35
> If we can't find the actual file we can't transform the file using svelte2tsx.

Yep, this is relevant to alias path resolving defined in the project's `tsconfig.json` is not being honoured. So, if we change it to relative path instead of using alias path, the vscode extension and svelte-check will not throw any error anymore which you can see from OP's screenshot for the `ComboBox` component.

**Comment by jasonlyu123** [comment] 2020-08-21 05:48
Can you check the output channel of vscode, chose svelte in the dropdown on the right. And see if you have something like this
`Initialize new ts service at  c:/Current Projects/svelte-app/tsconfig.json` and post the log here.

**Comment by dummdidumm** [comment] 2020-08-21 07:12
I can reproduce this. For some reason `getDefinitionAndBoundSpan` can deal with TS/JS files imported from such locations, but not with `.svelte` files.

**Comment by dummdidumm** [comment] 2020-08-21 08:31
The problem is inside our `module-loader`, which delegates to the normal TS resolution because the check for "is absolute path" is true (file paths starting with `/` are absolute in linux). I think we need additional checks for "is this prefix part of tsconfig paths".

**Closed** 2020-08-24 06:02 UTC
Labels: Fixed, bug, question

**Comment by numfin** [comment] 2020-08-27 17:52
I forgot to say how awesome you guys are. Thank you fro quick response
