### ISSUE TITLE
unused css highlighting is always messed up

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/language-tools#540] opened 2020-09-14 18:27 UTC
**Describe the bug**
When using SCSS style blocks, the unused CSS wiggly yellow lines don't show up in the right place.

![image](https://user-images.githubusercontent.com/12383587/93122909-98297500-f6c7-11ea-889b-1d43b69f8cdb.png)

It should highlight the `.introduction` class, but it highlights the `height` property (or any last property of the first defined style) instead.

When switching back to a normal CSS block without the `lang` attribute, it works fine.

**To Reproduce**
1. Make a simple component with some elements
2. Add some used and unused vanilla CSS without SCSS functions or syntax sugar
3. Change the `<style>` to `<style lang="scss">`

**Expected behavior**
Work the same as when it is just a normal `<style>` block

**Screenshots**
See above

**System (please complete the following information):**
 - OS: Windows
 - IDE: VScode
 - Plugin/Package: "Svelte for VSCode"

**Additional context**
No additional plugins or extensions were enabled when making the screenshot. I even restarted vscode just in case.

**Comment by dummdidumm** [comment] 2020-09-14 18:30
Could you please post the code snippet that gave you the squiggles at this line?

**Comment by UltraCakeBakery** [comment] 2020-09-14 18:41
> Could you please post the code snippet that gave you the squiggles at this line?

It shouldn't matter what code you use. It quickly starts breaking on my end. The more code, the worse it gets.

Here is a quick REPL:
https://svelte.dev/repl/97a01882d3444d77ad2a62480e310921?version=3.25.0

In my IDE, with the SCSS attribute
![image](https://user-images.githubusercontent.com/12383587/93124807-81d0e880-f6ca-11ea-9bfb-1308d9f7f7a9.png)

without the attribute:
![image](https://user-images.githubusercontent.com/12383587/93124856-8d241400-f6ca-11ea-9e1c-635ba82965a9.png)

**Comment by UltraCakeBakery** [comment] 2020-09-14 18:49
Are the sourcemaps something I can fix on my end? Or is that a problem with svelte preprocess? rollup?
Lucky for me I know what css i'm writing and html i'm removing, so I can deal with this for now. Is there a sain way to turn these off for now?

**Comment by benmccann** [comment] 2020-09-14 18:56
https://github.com/sveltejs/svelte/pull/5015 needs to be merged for preprocessor sourcemap support

**Comment by dummdidumm** [comment] 2020-09-14 18:57
> Are the sourcemaps something I can fix on my end? Or is that a problem with svelte preprocess? rollup?

The scss compiler (`node-sass` / `sass`, depends what you are using) produces the source maps. 

> Lucky for me I know what css i'm writing and html i'm removing, so I can deal with this for now. Is there a sain way to turn these off for in case I have to?

If you want to turn off some warnings globally, you can do so through [this option](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsveltecompilerwarnings).

**Comment by dummdidumm** [comment] 2020-09-14 18:57
> [sveltejs/svelte#5015](https://github.com/sveltejs/svelte/pull/5015) needs to be merged for preprocessor sourcemap support

Not for the language-tools, at the moment we do mapping ourselves (but can hopefully throw out a whole bunch of code once this lands).

**Comment by UltraCakeBakery** [comment] 2020-09-14 19:02
> [sveltejs/svelte#5015](https://github.com/sveltejs/svelte/pull/5015) needs to be merged for preprocessor sourcemap support

It looks like it is a relatively popular pull request. Any known reason on why it hasn't been merged yet?

**Comment by benmccann** [comment] 2020-09-14 19:07
It's high on our radar. It's not in a mergable state yet though. I left some comments on it.

**Comment by dummdidumm** [comment] 2020-09-16 05:54
I checked but was not able to reproduce the line offsets you experience when using only SCSS. Do you use PostCSS, too? I only can reproduce if I also use PostCSS. If so, the reason for that is missing source maps from PostCSS. I opened [this issue](https://github.com/sveltejs/svelte-preprocess/issues/251) over at `svelte-preprocess` for it.

**Comment by UltraCakeBakery** [comment] 2020-09-17 17:56
Sorry for the late response. I have https://www.npmjs.com/package/postcss-load-config installed. That's about it.

**Comment by dummdidumm** [comment] 2020-09-17 18:00
So this means you are using postcss, so `postcss: true` is part of your preprocessor config? If so, this will be fixed after the issue within `svelte-preprocess` is fixed.

**Comment by UltraCakeBakery** [comment] 2020-09-17 18:15
> So this means you are using postcss, so `postcss: true` is part of your preprocessor config?

If postcss is set to true by default, yes.

> If so, this will be fixed after the issue within svelte-preprocess is fixed.
👀

**Comment by dummdidumm** [comment] 2020-11-21 14:34
This should be fixed with version `4.6.1` of `svelte-preprocess`.

**Closed by dummdidumm** 2020-11-21 14:34 UTC
Labels: bug
