### ISSUE TITLE
Unexpected token in visual studio code with svelte(kit) file.

### ISSUE THREAD

**Issue by JohnSters** [sveltejs/language-tools#1841] opened 2023-01-20 14:09 UTC
### Describe the bug

I am getting a Unexpected token when using classes.
The following class copied from the typescript website gives a Unexpected token on the **name: string** property
```
<script lang="ts">
	class GoodGreeter {
		name: string;

		constructor() {
			this.name = 'hello';
		}
	}
</script>
```
`Yes, using TypeScript syntax`  Was selected with Prettier and ESlint. I am kubuntu 22.04 and using node v18. I tried it on a brand new sveltekit installation. I have also tried it in a typescript file and do not get the error then.

### Reproduction

```
class GoodGreeter {
    name: string;

    constructor() {
        this.name = 'hello';
    }
}
```

### Expected behaviour

Should not be getting an Unexpected token.

### System Info

Kubuntu
Visual Studio Code.
Svelte for VS Code v107.0.1
Svelte Intellisense
Svelte 3 Snippets
sveltekit-snippets

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2023-01-20 16:13
Duplicate of sveltejs/svelte#6900

**Closed by jasonlyu123** 2023-01-20 16:13 UTC
Labels: bug
