### ISSUE TITLE
TypeScript no type hint in {#each}

### ISSUE THREAD

**Issue by Kapsonfire-DE** [sveltejs/language-tools#919] opened 2021-03-28 07:56 UTC
**Describe the bug**
The IDE/Compiler gives a warning when using types/objects in #each

**Logs**
Please include browser console and server logs around the time this bug occurred.
`Property 'value' does not exist on type 'unknown'`

**To Reproduce**
` type SelectOption = { value: string, display: string };
    const selectOptions: SelectOption[] = [
        {
            value: '%',
            display: '%'
        },
        {
            value: '$',
            display: '$'
        }
    ];
   `
    
    `   {#each selectOptions as opt}
        {opt.value} {opt.display}
    {/each}`

**Expected behavior**
Well bring over the type inside #each

**Comment by dummdidumm** [comment] 2021-03-28 15:26
This works for me:

```svelte
<script lang="ts">
  type SelectOption = { value: string, display: string };
  const selectOptions: SelectOption[] = [ { value: '%', display: '%' }, { value: '$', display: '$' } ];
</script>

{#each selectOptions as opt}
    {opt.value} {opt.display}
{/each}
```

Could you provide more info? `tsconfig.json` etc.

**Comment by Kapsonfire-DE** [comment] 2021-03-28 16:00
compilation/transpile works, but IDE doesnt detect the type of opt... dont think its tsconfig related

`{
  "compilerOptions": {
    "module": "esnext",
    "rootDir": "./../",
  },
  "extends": "@tsconfig/svelte/tsconfig.json",

  "include": ["src/**/*", "../network/**/*", "../shared/**/*"],
  "exclude": ["node_modules/*", "__sapper__/*", "public/*"]
}`

**Comment by dummdidumm** [comment] 2021-03-28 16:11
Still can't reproduce. Which IDE are you using? If VS Code, are you using the Svelte for VS Code extension? If so, which version?

**Comment by Kapsonfire-DE** [comment] 2021-03-28 16:55
Im using intellij with svelte plugin, but someone else on discord had the same problem using another IDE.
I dunno, but looks like vscode with plugin
https://cdn.discordapp.com/attachments/457912077277855766/825635956068450324/ts.png

**Comment by dummdidumm** [comment] 2021-03-29 12:07
The IntelliJ plugin is not maintained by us, and since I there is no reproducible, I'm going to close this.

**Closed by dummdidumm** 2021-03-29 12:07 UTC
