### ISSUE TITLE
Support `tsconfig.json` with references

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/language-tools#2457] opened 2024-08-05 04:02 UTC
### Description

I am trying to use multiple `tsconfig` files using the `references` field.

- https://github.com/sveltejs/kit/issues/12537

However, `svelte-check` and [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) do not seem to utilize the referenced project(s).

As a result, `svelte-check` results and error messages in VS Code editor do not match.

Reference the `FIXME` comments in https://github.com/hyunbinseo/svelte-kit-templates/commit/85616f71fd05608391563976ef85968e735b2644

```jsonc
// tsconfig.json - base config
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": { "lib": ["ES2022"] },
  "references": [{ "path": "./tsconfig.client.json" }]
}
```

```jsonc
// tsconfig.client.json - client-only config
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "composite": true,
    "noEmit": false,
    "declaration": true,
    "emitDeclarationOnly": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"] // lower lib value in this case
  },
  "exclude": [
    "./node_modules/**",
    "./src/service-worker.js",
    "./src/service-worker.ts",
    "./src/service-worker.d.ts",
    // Exclude server files.
    "./src/lib/server/**/*.js",
    "./src/lib/server/**/*.ts",
    "./src/**/*.server.js",
    "./src/**/*.server.ts",
    "./src/**/+server.js",
    "./src/**/+server.ts"
  ]
}
```

### Proposed solution

Support `tsconfig` file's `references` field.

https://www.typescriptlang.org/tsconfig/#references

**Comment by jasonlyu123** [comment] 2024-08-05 04:50
Duplicate of #2148

**Closed by jasonlyu123** 2024-08-05 04:50 UTC
