### ISSUE TITLE
When use "organize imports", same folder imports are deleted

### ISSUE THREAD

**Issue by Maze-fr** [sveltejs/language-tools#1476] opened 2022-05-09 04:47 UTC
### Describe the bug

When I do `right click -> Source Action... -> Organize Imports` or also using the shortcut associated `alt + shift + o`, all my local imports disappear, whatever if I use them or not.
Then, of course, VSCode is full of colours like a Xmas tree...

### Reproduction

1. Create 3-4 components with simple slots, in the same `$lib` sub-folder.
2. Create index files (JS and TS) to export them from that folder.
3. In one of these components, create a hierarchy (one component inside another, for the slot), by using language tool imports on auto-completion.
4. Auto-completion should have created one import line for each component.
5. Trigger `Organize Imports`
6. No more imports...

Code example :
```html
<script lang="ts">
    import { ComponentA } from '.';
    import { ComponentB } from '.';
    import { ComponentC } from '.';
</script>

<ComponentA>
    <ComponentB>
        <ComponentC/>
    </ComponentB>
</ComponentA>
```
From what I noticed, it's only with local imports, and only when the script tag contains only local imports.

### Expected behaviour

Imports still in use shouldn't disappear, and should be merged in only one import line.

### System Info

- OS: `Xubuntu 22.04`
- IDE: `VSCode 1.67.0`, using `Svelte for VS Code`

Everything is up to date, VSCode installed from Micro$oft website deb file (not using the shitty Canonical snap system).

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots

Its a bit random, I don't manage to reproduce it 100% of time, I didn't figure out the exact perfect conditions to reproduce it.

**Comment by jasonlyu123** [comment] 2022-05-12 04:29
I can't reproduce this with the reproduction steps. Can you provide a reproduction repository with the reexporting `index.js`?

**Comment by NoelOConnell** [comment] 2022-05-13 11:43
I am experiencing the same issue also. It is hard to replicate consistently.

The most common time it happens is when there is a syntax error on the page like a missing end tag or a missing component import. If you hit save then all local component imports are removed.

Imports for stores etc are kept but not component imports.

**Comment by Maze-fr** [comment] 2022-05-13 12:53
Oh yes ! I think you are right !
I think I did a "Format document" after writing the components, and one of them had a mandatory attribute.
So it did underline the component in red, then "Organize imports", and imports vanished.

**Comment by jasonlyu123** [comment] 2022-05-17 11:42
In that case, wondering if we should only sort the imports or if we just don't send any edits.

**Comment by dummdidumm** [comment] 2022-05-17 12:10
Oh I think I know why. When the file is in a broken state, TS doesn't see the markup contents and thinks everything that's only used there is unused, removing it when doing "organize imports"

**Comment by NoelOConnell** [comment] 2022-05-17 16:02
Just got bit by this again. I was changing an element from a span to label but only changed the opening tag and saved the file.
So the file had a error since the opening/closing tags did not match. My imports were removed.

If the file is in a broken state it would be ideal if it defaulted to organize imports only or do nothing.

**Closed** 2022-06-18 10:19 UTC
Labels: bug, Fixed
