### ISSUE TITLE
<svelte:head  tag not support！！　

### ISSUE THREAD

**Issue by MS-ELEX** [sveltejs/language-tools#730] opened 2020-12-31 04:59 UTC
![Picture 2020-12-31 13_51_38](https://user-images.githubusercontent.com/16563756/103395191-4e7a7280-4b70-11eb-991c-b2811c38c374.png)

**Comment by jasonlyu123** [comment] 2020-12-31 05:35
Please provide more info on the error message or provide a minimal reproducible.
If you have a preprocess setup, follow [this doc](https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors) for setup and troubleshooting

**Comment by dummdidumm** [comment] 2021-01-13 15:00
Closing due to lack of reproduction.

**Closed by dummdidumm** 2021-01-13 15:00 UTC
Labels: bug
