### ISSUE TITLE
VSCode Error - SyntaxError: Named export 'isIdentifier' not found.

### ISSUE THREAD

**Issue by stolinski** [sveltejs/language-tools#1228] opened 2021-11-03 16:45 UTC
**Describe the bug**

Currently seeing 
```
SyntaxError: Named export 'isIdentifier' not found. The requested module '@babel/types' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@babel/types';
const { isVariableDeclarator, isIdentifier, isTemplateLiteral, isImportDefaultSpecifier, isImportSpecifier } = pkg;
```
In all Svelte files when using a custom plugin. 

To be clear, the plugin works 100% as expected. The only problem here is the error message in VSCode.

**To Reproduce**

Clone repo
https://github.com/stolinski/sk-gquery-reporduction
npm install
Open in vscode, look at any .svelte file.

**Expected behavior**

Plugin would work and no errors on loading.

**Screenshots**
<img width="1523" alt="Screen Shot 2021-11-03 at 10 44 03 AM" src="https://user-images.githubusercontent.com/669383/140104704-1d80f48b-b5d5-4d60-9ad2-a8d9992deb89.png">

**System (please complete the following information):**
 - OS: MacOS
 - IDE: VSCode
 - Plugin/Package:"Svelte for VSCode"

 
**Additional context**

There doesn't seem to be any issue functionally but the error does clog our error log and causes issues trying to find TS errors.

**Comment by stolinski** [comment] 2021-11-03 16:46
An extra note, no need to run svelte, or get the app running, just load in vscode to see the problem.

**Comment by jasonlyu123** [comment] 2021-11-04 01:42
As mentioned in the discord. This is a problem with the node.js version vscode bundled. It's 14.16.0 in vscode 1.61.2. Using the `svelte.language-server.runtime` config should make the error goes away. It works on my machine.

From node.js API docs [14.16.0](https://github.com/nodejs/node/blob/v14.16.0/doc/api/esm.md#commonjs-namespaces) uses `cjs-module-lexer` 1.0.0. While [14.17.0](https://github.com/nodejs/node/blob/v14.17.0/doc/api/esm.md) uses `cjs-module-lexer` 1.1.1. And from the [change log](https://github.com/nodejs/cjs-module-lexer/blob/main/CHANGELOG.md). The babel issue seems to be fixed in 1.1.1. So this issue should be resolved the next time vscode bumps the node.js version. (probably depends on the electron version they're using though)

**Comment by stolinski** [comment] 2021-11-04 15:38
> As mentioned in the discord. This is a problem with the node.js version vscode bundled. It's 14.16.0 in vscode 1.61.2. Using the `svelte.language-server.runtime` config should make the error goes away. It works on my machine.

Just for future reference and clarity. What are you setting `svelte.language-sever.runtime` too? Did you install the runtime globally and then just use that path?

**Comment by dummdidumm** [comment] 2021-11-04 15:44
You pass it the path to the executable of your NodeJs runtime

`"svelte.language-sever.runtime": "/path/to/your/node.exe"`

**Comment by stolinski** [comment] 2021-11-04 15:45
Oh right, that makes sense. 😅

**Comment by jasonlyu123** [comment] 2022-03-31 09:34
VSCode 1.66.0 is released with node.js16.13.0. So this should be fixed now. I can't reproduce it with VSCode 1.66. Can you test it again?

**Comment by jasonlyu123** [comment] 2022-04-21 07:49
I am going to close this since I think this is fixed and I can't reproduce this anymore. Feel feel to reopen if you can still reproduce this.

**Closed by jasonlyu123** 2022-04-21 07:49 UTC
Labels: question, upstream
