### ISSUE TITLE
VSCode 1.73: Saving Typescript *.svelte causes Code Helper freeze when Organize Imports is enabled

### ISSUE THREAD

**Issue by benallfree** [sveltejs/language-tools#1713] opened 2022-11-06 17:14 UTC
### Describe the bug

```json
{
  "editor.codeActionsOnSave": {
      "source.organizeImports": true
  }
}
```

In v1.72, the feature works fine. But in 1.73 Code Helper freezes. No other extensions enabled.

### Reproduction

No minimum reproducible example at this time - just seeing if anyone else is having this same issue.

### Expected behaviour

Expecting Organize Imports to work :)

### System Info

- OS: OS X Ventur 13.0
- IDE: VSCode 1.73 (October)

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment] 2022-11-06 17:37
Duplicate of #1703

**Closed** 2022-11-06 17:37 UTC
Labels: bug
