### ISSUE TITLE
Svelte syntax highlighting breaks when a non-initialized variable is defined

### ISSUE THREAD

**Issue by Rinconx64** [sveltejs/language-tools#1998] opened 2023-05-02 22:27 UTC
### Describe the bug

When I export a property from a Svelte component without initializing it, the syntax highlighting breaks. Semicolons can be used to solve this, but Prettier automatically corrects it.

### Reproduction

![wrong](https://user-images.githubusercontent.com/25558870/235798186-3d042f0a-a3ab-4a8a-b1c8-4a18afc77d8e.png)

![fine](https://user-images.githubusercontent.com/25558870/235798364-3c1967a6-792b-44fb-8c94-1b35c8bd0303.png)

### Expected behaviour

That the syntax highlighting doesn't break when semicolons are not used

### System Info

- OS: Windows
- IDE: VSCode

**Comment by Rinconx64** [comment] 2023-05-02 22:41
Adding a simple comment after the declaration also works and we don't have the problem that when you save, Prettier deletes the semicolon

**Comment by jasonlyu123** [comment] 2023-05-02 23:00
Duplicate of #1970

**Closed by jasonlyu123** 2023-05-02 23:00 UTC
Labels: bug
