### ISSUE TITLE
Syntax highlighting fails in TS script tags without a semicolon

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/language-tools#1989] opened 2023-04-17 23:15 UTC
### Describe the bug

If a TypeScript script content ends with a type without a semicolon, then the syntax highlighting breaks down:

<img width="230" alt="CleanShot 2023-04-18 at 06 03 34@2x" src="https://user-images.githubusercontent.com/5859177/232628972-51c0478f-fedb-4bd7-8719-613378062192.png">

I don't know if this is the right repo to report the issue, but the only place where the issue is apparent is in Svelte files.

### Reproduction

```svelte
<script lang="ts">
export let name: string
</script>

<div>
  {name}
</div>
```
NB: same issue with syntax highlighting here

### Expected behaviour

Expected the code to be highlighted like this, but without the use of a semicolon:

<img width="218" alt="CleanShot 2023-04-18 at 06 14 37@2x" src="https://user-images.githubusercontent.com/5859177/232629995-976c2fdd-27ab-4e5f-810a-b1365e6c9811.png">

### System Info

- OS: Mac OS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

I have reported a similar issue (https://github.com/sveltejs/language-tools/issues/1110), but it looks like the problem is less specific than what was described there.

### Workaround

Adding a comment (`//`) at the very end resolves the issue with syntax highlighting:
```svelte
<script lang="ts">
export let name: string //
</script>

<div>
  {name}
</div>
```

**Comment by jasonlyu123** [comment] 2023-04-18 00:52
Duplicate of https://github.com/sveltejs/language-tools/issues/1970. It's an upstream issue fixed but not released in VSCode Stable yet.

**Closed by jasonlyu123** 2023-04-18 00:52 UTC
Labels: bug

**Comment by jasonlyu123** [comment] 2023-04-18 01:43
It's [Github linguist](https://github.com/github/linguist). I see TypeScript TmLanguage in that repo. So it probably would be resolved as well.
