### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by potatotomatobanana** [sveltejs/language-tools#2099] opened 2023-07-16 22:34 UTC
### Describe the bug

![Screenshot 2023-07-16 150650](https://github.com/sveltejs/language-tools/assets/116115216/5bad27d7-6ab0-4932-959d-05a616a19984)

### Reproduction

.

### Expected behaviour

.

### System Info

- OS: Windows
- IDE: VSCode

**Comment by potatotomatobanana** [comment] 2023-07-16 22:39
After clicking on configure
![Screenshot 2023-07-16 153811](https://github.com/sveltejs/language-tools/assets/116115216/d8a89e2d-7fda-4e17-a8d6-4e2f80a12a26)

**Comment by potatotomatobanana** [comment] 2023-07-16 22:41
After setting prettier as the default formatter:

![Screenshot 2023-07-16 154022](https://github.com/sveltejs/language-tools/assets/116115216/da6beb3c-0095-4feb-a8ce-ea3bd995c108)

**Comment by ghostdevv** [comment] 2023-07-16 22:59
I don't think you can use prettier v3 yet, you must use v2

**Comment by jasonlyu123** [comment] 2023-07-17 00:52
Closing as duplicate of https://github.com/sveltejs/prettier-plugin-svelte/issues/317

**Closed by jasonlyu123** 2023-07-17 00:52 UTC
Labels: bug

**Comment by potatotomatobanana** [comment] 2023-07-17 12:55
I'm not using version 3 of Prettier. I'm using version 2.8.8

**Comment by jasonlyu123** [comment] 2023-07-17 13:12
If so, please provide a reproduction. `.` clearly isn't a reproduction.

**Comment by AlexRMU** [comment] 2023-10-23 13:08
Why is it closed?
The prettier plugin has already been updated - https://github.com/sveltejs/prettier-plugin-svelte/issues/317
But this one is not - https://github.com/sveltejs/language-tools/blob/master/package.json#L20

**Comment by AlexRMU** [comment] 2023-10-23 13:08
As a result, similar errors appear:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module c:\server\prettier.config.js from c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js not supported.
Instead change the require of prettier.config.js in c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js to a dynamic import() which is available in all CommonJS modules.
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at module2.exports (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:83:61)
    at loadJs2 (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8050:22)
    at Explorer.loadFileContent (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8449:36)
    at Explorer.createCosmiconfigResult (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8453:40)
    at Explorer.loadSearchPlace (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8438:35)
    at async Explorer.searchDirectory (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8428:31)
    at async run (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8413:26)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async cacheWrapper (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8294:22)
    at async Explorer.search (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\prettier\third-party.js:8407:24)
    at async Promise.all (index 0)
    at async getConfig (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:53:67)
    at async importFittingPrettier (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:76:29)
    at async SveltePlugin.formatDocument (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\svelte\SveltePlugin.js:85:67)
    at async PluginHost.tryExecutePlugin (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:347:20)
    at async Promise.all (index 0)
    at async PluginHost.execute (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:324:24)
    at async PluginHost.formatDocument (c:\Users\User\.vscode\extensions\svelte.svelte-vscode-107.12.0\node_modules\svelte-language-server\dist\src\plugins\PluginHost.js:114:38) {
  code: 'ERR_REQUIRE_ESM'
}
```
