### ISSUE TITLE
Extract component command does not remove it's variables and imports 

### ISSUE THREAD

**Issue by SlavenDj** [sveltejs/language-tools#1867] opened 2023-02-13 17:59 UTC
### Describe the bug

When attempting to create a component, I noticed that while all the necessary elements were successfully copied into the new file, the accompanying variables and imports were not removed in the original file where. As a result, I had to manually remove these unused variables and imports, which added extra time to my workflow. I would appreciate it if this issue could be addressed so that the component creation process is streamlined and more efficient.

### Reproduction

1.  Select the HTML code that you want to convert into a component.
2.  Right-click and choose "Svelte: Extract Component" from the menu.
3.  Give a name to the newly created component.
4.  Observe that there are still unused variables and imports in the script tag of the original file.

### Expected behaviour

Variables and imports that are moved into new file should me removed from original file.

### System Info

- OS: Linux (Zorin OS)
- IDE: VSCode 1.75

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2023-02-14 01:12
Duplicate of #187.

**Closed by jasonlyu123** 2023-02-14 01:12 UTC
