### ISSUE TITLE
Missing editor syntax highlighting with svelte preprocessor defaults set.

### ISSUE THREAD

**Issue by xeptore** [sveltejs/language-tools#888] opened 2021-03-19 07:57 UTC
**Describe the bug**
Editor syntax highlighting goes away when svelte preprocessor defaults are set. It seems the editor falls-back to its default _nature_, e.g., expects all `style` tags to be `css`.

Note: All the errors and warnings are still reported fine, the **only** missing part is the syntax highlighting (and editor suggestions of course).

**To Reproduce**

1. Add `svelte.config.js` with the following contents (from [here](https://github.com/sveltejs/svelte-preprocess/blob/af3df3aa7cd7c1d5736609bba5717a6e76cdecd2/docs/preprocessing.md#auto-preprocessing-options), and [here](https://github.com/sveltejs/svelte-preprocess/blob/795c02bc8799504ebbfb99e3f032dc3d1e4af5b6/docs/getting-started.md#31-setting-default-languages)):
    ```js
    const sveltePreprocess = require('svelte-preprocess');

    module.exports = {
      preprocess: sveltePreprocess({
        defaults: {
          markup: 'html',
          script: 'typescript',
          style: 'scss'
        },
      });
    };
    ````
2. Restart the Svelte's language server by issuing `Svelte: Restart Language Server` VSCode command.

**Expected behavior**
Syntax highlighting **should** work fine with or without setting `lang="scss"` attribute on component's `style` tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/29199390/111748655-0a148e00-88a6-11eb-9c46-b2d60b297b2b.png)

**System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode official extension

**Comment by jasonlyu123** [comment] 2021-03-19 08:07
Duplicate of #747. This is currently not possible as the syntax highlight can't be dynamic. Sorry.

**Closed by jasonlyu123** 2021-03-19 08:07 UTC
Labels: bug
