### ISSUE TITLE
Vscode does not auto import a component file with the name input.svelte

### ISSUE THREAD

**Issue by Nukiloco** [sveltejs/language-tools#1196] opened 2021-10-06 06:28 UTC
**Describe the bug**
When having a file named ``input.svelte`` and then typing ``<Input>`` into any other component, vscode will not import it in. Vscode can auto import file names like ``button.svelte``. Also by the way, ``input.svelte`` works if I manually import it in.

**To Reproduce**
1. Create a svelte component with the file name of ``input.svelte``
2. Type ``<Input>`` and it tab,
3. It does not autocomplete.

For example a code snippet that is treated in a way you don't expect.

**Expected behavior**

```
<Input></Input>
```

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - IDE: [e.g. VSCode, Atom] VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by Nukiloco** [comment] 2021-10-06 07:01
Another thing to mention, after typing in <Input>, if you try to type in ``</`` it will autocorrect instantly it to ``</div>`` instead.

**Comment by jasonlyu123** [comment] 2021-10-06 08:49
I can't reproduce it. Can you check if it happens in another directory?

**Comment by Nukiloco** [comment] 2021-10-06 13:48
> 
> 
> I can't reproduce it. Can you check if it happens in another directory?

In some cases it does auto import it but it doesn't auto complete the tag.
Aka the input component is in a folder called ``components``
I'm currently in a different folder right now which it can auto import the script but it doesn't auto complete the tags.

**Comment by jasonlyu123** [comment] 2021-10-07 01:22
Yes. it won't auto-complete the tag. We're using vscode-html-language-service for tag completion. Since the input tag doesn't have an end tag in HTML, it won't auto close it. 

As for the auto import problem can you provide a reproducible? Also, do you have a jsonfig.json or tsconfig.json?

**Comment by Nukiloco** [comment] 2021-10-07 13:49
I have a tsconfig.json, and its not actually a default input tag, its a custom component thats called ``Input``.

**Comment by jasonlyu123** [comment] 2021-10-08 01:08
Yes, I am aware of that and it's an unrelated issue. What I mean by "in HTML" is that vscode-html-language-service treat it as an HTML tag. 

Can you check if the svelte files are included in the tsconfig? It would be nice to have a reproducible otherwise I can only guess what could have happened.

**Comment by dummdidumm** [comment] 2022-12-09 15:24
Closing due to inactivity.

**Closed by dummdidumm** 2022-12-09 15:24 UTC
Labels: bug, needs repro
