### ISSUE TITLE
"globals" list, where global functions can be defined, so there are no warnings

### ISSUE THREAD

**Issue by kobe-ra** [sveltejs/language-tools#2113] opened 2023-07-30 22:10 UTC
### Description

I'm using Laravel-Inertiajs-Svelte setup, which means I have global function `route()` available according to my `web.php`.

However, I'm getting `'route' is not defined svelte(missing-declaration)` warning.
I had to ignore these warning altogether, instead of declaring my global functions.

### Proposed solution

Add `"globals"` input array to extension settings to make users able to provide list of their `global` functions.

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/32091524/0297c611-ecb1-4596-838c-661163f628ec)

**Comment by jasonlyu123** [comment] 2023-07-30 23:49
Duplicate of upstream https://github.com/sveltejs/svelte/issues/7240

**Closed by jasonlyu123** 2023-07-30 23:49 UTC
