### ISSUE TITLE
{#if} blocks should narrow types, as in TypeScript if

### ISSUE THREAD

**Issue by gristow** [sveltejs/language-tools#986] opened 2021-05-05 20:19 UTC
**Describe the bug**
`{#if}` blocks in templates don't result in [narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) of union types, as they would in a standard `if` block in TypeScript. This can result in code that is type safe not being compilable.

**To Reproduce**
```
<script lang="ts">
  type Foo = string | null;

  export let foo: Foo;

  function logString(url: string) {
    console.log(url);
  }

  if (foo) {
    // Compiles correctly, TS narrows foo to be type string within "if"
    logString(foo);
  }
</script>

{#if foo}
  <!-- Does not compile, foo not narrowed to type string -->
  <button on:click={() => logString(foo)}>Log It</button>
{/if}
```

**Expected behavior**
TypeScript should narrow foo to type string within the `{#if}` block, which excludes the null type of the union.

**Screenshots**
![Screenshot of above code showing the TS error popup of Argument of type 'string | null' is not assignable to parameter of type 'string'](https://user-images.githubusercontent.com/8905340/117203687-4dc34880-adbd-11eb-98b9-6727e8b132dd.png)

**System (please complete the following information):**
 - OS: Mac
 - IDE: VSCode
 - Plugin/Package: Svelte for VS Code v104.12.0

**Comment by dummdidumm** [comment] 2021-05-05 20:49
Duplicate of #876

**Closed by dummdidumm** 2021-05-05 20:49 UTC
Labels: bug
