### ISSUE TITLE
Improve Intellisense Implementation

### ISSUE THREAD

**Issue by Enteleform** [sveltejs/language-tools#665] opened 2020-11-10 09:31 UTC
## **Is your feature request related to a problem? Please describe.**

- VSCode's `Rename Symbol` only works within a single .svelte file
- component attributes do not have autocompletion or type information

&nbsp;  
### **Example:**

**Counter.svelte**  
```html
<script lang="ts">
  export let count = 0
</script>
```

**index.svelte**  
```html
<!-- neither of these will update when using VSCode's `Rename Symbol` on the `count` definition @ Counter.svelte -->

<Counter count={5}/>  

<Counter count={"7"}/>  <!-- should result in error "Type 'string' is not assignable to type 'number'. ts(2322)" -->
```

&nbsp;  
## **Describe the solution you'd like**

- `Rename Symbol` should update all references within a project
- component attributes should have autocompletion and type information

&nbsp;  
## **How important is this feature to you?**
Absolutely essential. Not being able to use the code intelligence features of TypeScript + VSCode detracts greatly from the development experience and nullifies critical debugging safeguards which are one of the main reasons to use TypeScript in the first place.

**Comment by jasonlyu123** [comment] 2020-11-10 10:35
About rename see #110 for more information.

About the component props completion, what exactly is missing? The extension does have this feature. Maybe you can try following the troubleshooting doc [here](https://github.com/sveltejs/language-tools/tree/master/docs) to see if there is any issue.

**Comment by dummdidumm** [comment] 2020-11-10 11:12
I can't reproduce any of your issues. Errors diagnostics, rename functionality and autocompletion works with the following setup:

#### Counter.svelte
```svelte
<script lang="ts">
  export let count = 0
</script>
```

#### index.svelte
```svelte
<script lang="ts">
  import Counter from "./Counter.svelte";
</script>

<Counter count={5}/>  
<Counter count={"7"}/>
```

**Comment by jasonlyu123** [comment] 2020-11-10 11:32
Did you have path alias? That might explain why your language feature only works within the component.

**Comment by Enteleform** [comment] 2020-11-10 11:32
@jasonlyu123 

Nevermind @ completion, I'm running the `svelte@next` starter and the included `tsconfig.json` wasn't synced up with the aliases defined @ `@sveltejs/snowpack-config`. Added the following and now have functional completion:
```json
"baseUrl": ".",
"paths": {
  "$components/*": ["./src/components/*"],
},
```

&nbsp;  
However, the types are still not being enforced and there is an extra line that shows `undefined` for some reason.  
(*confirmed @ latest stable starter as well*)

![image](https://user-images.githubusercontent.com/10906415/98667845-fe73f200-231c-11eb-87c5-6f04a2889328.png)

&nbsp;  
Here's a screenshot of the expected hover info w/ a valid assignment:  
![image](https://user-images.githubusercontent.com/10906415/98668158-7b9f6700-231d-11eb-9aff-2612a9f3ab24.png)

&nbsp;  
And the expected hover info w/ an invalid assignment:  
![image](https://user-images.githubusercontent.com/10906415/98668456-e9e42980-231d-11eb-86e7-329a4adebacd.png)

**Comment by Enteleform** [comment] 2020-11-10 11:46
@dummdidumm 

I see that renaming & completion are functional after checking out #110 and updating `tsconfig.json` as mentioned in my last post.

I'm still not receiving any errors on invalid assignment types though. Also, there are no errors for nonexistent attributes. (*e.g. `coumt` typo does not trigger an error*).

**Comment by dummdidumm** [comment] 2020-11-10 11:58
You said these errors occur in the context of `svelte@next`. We do not offer any kind of guarantees/support for it yet, everything is highly experimental at this point and may break at any time, therefore I close this issue. Also, in your screenshot, `App.svelte` does not have `lang="ts"` set, so it's treated as JavaScript, not TypeScript.

About the optional type:  Right now it's only required in strict mode, otherwise every prop is marked as optional. We may need to revisit this decision in the future.

**Closed by dummdidumm** 2020-11-10 11:58 UTC
Labels: enhancement

**Comment by Enteleform** [comment] 2020-11-10 12:24
@dummdidumm 
Ok, sorry for the confusion. Adding `lang="ts"` resolved most of the issues. Also, I was testing this on both `next` and `stable` in parallel; just made the error of copying the script tag w/o `lang` to the stable starter.

&nbsp;
Is there anywhere to provide feedback for `next`?  
The starter has 2 issues that I'm aware of:  
- no `lang="ts"` @ `routes/index.svelte`
- `tsconfig.json` aliases do not match `@sveltejs/snowpack-config`

&nbsp;  
Also, just found that the `count: undefined` hover info occurs when using relative imports with inferred types.

```ts
// does not show `undefined`
import Counter from "$components/Counter.svelte" // aliased import
export let count: number = 0                     // explicit type

// does not show `undefined`
import Counter from "$components/Counter.svelte" // aliased import
export let count = 0                             // inferred type

// does not show `undefined`
import Counter from "./components/Counter.svelte" // relative import
export let count: number = 0                      // explicit type

// shows `undefined`
import Counter from "./components/Counter.svelte" // relative import
export let count = 0                              // inferred type
```

![image](https://user-images.githubusercontent.com/10906415/98673556-7e9e5580-2325-11eb-8d64-f241b372950e.png)

**Comment by dummdidumm** [comment] 2020-11-10 12:34
There is no official way to give feedback yet, because everything's changing so fast that one's feedback might be obsolete two days later. We will announce when we enter the beta phase where you can give feedback like this.
