### ISSUE TITLE
Preprocessors must be ran before svelte2tsx

### ISSUE THREAD

**Issue by ottomated** [sveltejs/language-tools#2447] opened 2024-07-26 22:46 UTC
### Describe the bug

If a svelte preprocessor edits the code to, for example, change the value of a $props() rune, the language server will not reflect that change. I believe this is because `svelte2tsx` is receiving the original unprocessed code.

### Reproduction

```js
// preprocess.js

export default function preprocess() {
  return {
    script: ({ content }) => {
      return {
        code: 'const { test }: { test: string } = $props();\n' + content
      }
    }
  };
}
```
```js
// svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import preprocess from './preprocess.js';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [preprocess(), vitePreprocess()],
  kit: { adapter: adapter() },
};

export default config;
```
```svelte
<!-- +page.svelte -->
<script>
  import Foo from './Foo.svelte';
</script>

<Foo test="foo" />
<!-- ^~~~ Type 'string' is not assignable to type 'never'. ts(2322) -->
```
```svelte
<!-- Foo.svelte -->
<script>
</script>

{test}
```

### Expected behaviour

Since the above example compiles and runs, the language server output should match it.

### System Info

- OS: Linux
- IDE: VSCode

### Which package is the issue about?

svelte-language-server, svelte2tsx

**Comment by jasonlyu123** [comment] 2024-07-27 00:14
Duplicate of #1567, #339. Preprocess API is asynchronous but TypeScript API requires it to be synchronous. There is also no way to tell if the preprocess is intended to transpile typescript into javascript or add stuff to typescript code.

**Closed by jasonlyu123** 2024-07-27 00:14 UTC
Labels: bug
