### ISSUE TITLE
TS constructor with attributes short-hand throws "Unexpected token"

### ISSUE THREAD

**Issue by dloreto** [sveltejs/language-tools#1602] opened 2022-08-26 15:51 UTC
### Describe the bug

TS constructor with attributes short-hand throws "Unexpected token": https://dev.to/satansdeer/typescript-constructor-shorthand-3ibd

### Reproduction

![image](https://user-images.githubusercontent.com/29567012/186944111-f48ea753-a58a-4c3c-8079-b0498f672e90.png)

### Expected behaviour

Should not throw

### System Info

  System:                                  
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 12.16 GB / 31.42 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.428 => 1.0.0-next.428 
    svelte: ^3.49.0 => 3.49.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment] 2022-08-26 15:57
Duplicate of https://github.com/sveltejs/svelte/issues/6900

**Closed by dummdidumm** 2022-08-26 15:57 UTC
Labels: bug
