### ISSUE TITLE
String content erased when inferring slot/event type from props

### ISSUE THREAD

**Issue by geigerzaehler** [sveltejs/language-tools#1113] opened 2021-07-23 08:24 UTC
The following Svelte code fails to check with `svelte-check` v2.2.3.
~~~svelte
<!-- Component.svelte -->
<script lang="typescript">
  export let variant: "foo" | "bar"
  export let style: string
</script>
~~~

~~~svelte
<!-- index.svelte -->
<script lang="typescript">
  import Component from "./Component.svelte";
</script>

<Component
  variant="foo"
  style={`${
    1
  }`}
  on:click={() => {}}
/>
~~~

It shows the error
~~~plain
Error: Type '""' is not assignable to type '"foo" | "bar"'. (ts)
  on:click={() => {}}
/>
~~~

The example looks artificial but this layout is produced by prettier if the expression inside `${}` is long.

**Comment by jasonlyu123** [comment] 2021-07-23 14:42
I can't reproduce the type-check error with the example you provide. The `new Custom` thing is supposed to be hidden from the type-check. The only thing I could think of it's that the component is generic and the props is used to infer a generic type parameter. It's that the problem you're encountering? If not can you provide another reproducible?

**Comment by geigerzaehler** [comment] 2021-07-23 16:00
You’re right. The code I posted works indeed. I assumed that I narrowed the error down to a minimal case. I’ll update the description with an example that indeed fails.

**Comment by jasonlyu123** [comment] 2021-07-30 00:49
There're two problems with this one. The empty string is used to simplify transformation. In more cases, it shouldn't matter. The reason you're only encountering it with a template literal is that its multi-line. The multi-line causes the generated code to not been ignored properly with our current approach. 

I fixed the empty string part (not released yet). But you might still encounter some problems with rename symbol when the identifier is referenced in the props. As the generated code is not being ignored. This one is more tricky to fix.

**Comment by jasonlyu123** [comment] 2021-08-02 14:34
The empty string part is released. You can try it again. I'll leave this open for the multi-line problem.

**Comment by dummdidumm** [comment] 2021-08-24 09:25
The multiline problem is fixed now.

**Closed by dummdidumm** 2021-08-24 09:25 UTC
Labels: bug, Fixed
