### ISSUE TITLE
Components with dot notation does not work

### ISSUE THREAD

**Issue by N00nDay** [sveltejs/language-tools#1701] opened 2022-10-22 17:17 UTC
### Describe the bug

I am building a svelte component library that utilizes dot notation for component composition. I have dot notation working as it should but when I type a . instead of showing only the possible child components it acts like I just typed a < and started a new tag. I have the following <Button /> component:

```
import OriginalButton from './Button.svelte';
import Icon from './Icon.svelte';

const Button = OriginalButton as ButtonStatic;
Button.Icon = Icon;
Button.Leading = Icon;
Button.Trailing = Icon;

export default Button;

export interface ButtonStatic {
    new (...args: ConstructorParameters<typeof OriginalButton>): OriginalButton;
    Icon: typeof Icon;
    Leading: typeof Icon;
    Trailing: typeof Icon;
}
```

When I type <Button. I would like autocomplete/intellisense to show me Icon, Leading, or Trailing but instead it is showing me all available components.

<img width="512" alt="bVFcL" src="https://user-images.githubusercontent.com/28783829/197353260-f9235c6b-7921-4f0e-b155-8ad27a3a1a86.png">

### Reproduction

**Create a SvelteKit Project**
```
npm create svelte@latest my-app
cd my-app
npm install
```

**Install STWUI**
```
npm i -D stwui
```

**Install TailwindCSS**
```
npx svelte-add@latest tailwindcss
npm install
```

**Modily `tailwind.config.cjs**
```
module.exports = {
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		'./node_modules/stwui/**/*.{svelte,js,ts,html}
	],
	plugins: [
		require('@tailwindcss/forms'),
		require('stwui/plugin')
	],
	darkMode: 'class',
};
```

- Open root +page.svelte
- `import { Button } from "stwui"`
- Type `<Button.`

### Expected behaviour

The expected behavior is that only the child components `Leading`, `Trailing`, and `Icon` would be listed or at least at the top of the list.

### System Info

- OS: Mac
- IDE: VSCode

**Comment by jasonlyu123** [comment] 2022-10-23 01:27
Duplicate of #776. This is a limitation of our current approach. We won't be able to fix it until https://github.com/sveltejs/language-tools/pull/1177 is merged or we find a reliable workaround.

**Closed by jasonlyu123** 2022-10-23 01:27 UTC
Labels: bug
