### ISSUE TITLE
Can't discriminate on auto-subscribed union

### ISSUE THREAD

**Issue by AlexGalays** [sveltejs/language-tools#546] opened 2020-09-18 00:31 UTC
store.ts
```ts
type SimpleRoute = {name: 'routeA', params: {}} | {name: 'routeB', params: {id: string}} 

export const simpleRoute = writable<SimpleRoute>({name: 'routeA', params: {}})
```

app.svelte

```svelte

<script>
  if ($simpleRoute.name === 'routeB') {
    $simpleRoute.params.id // Error
  }
</script>
```

![image](https://user-images.githubusercontent.com/1375586/93541429-ba84f200-f956-11ea-893f-e7943af08699.png)

It also doesn't work in the HTML, when using `{#if}`

Cheers

**Comment by dummdidumm** [comment] 2020-09-18 05:38
Duplicate of #493

**Closed by dummdidumm** 2020-09-18 05:38 UTC
Labels: bug
