### ISSUE TITLE
Add support for new @const tag

### ISSUE THREAD

**Issue by dimfeld** [sveltejs/language-tools#1330] opened 2022-01-12 08:46 UTC
Right now the extension doesn't like if you use the `@const` tag added in the latest Svelte release, especially in `svelte2tsx` I think.

I'll work on adding support on Wednesday or Thursday if nobody else gets to it first. Looks like a rather small change that can be mostly based on the existing `@html` tag support.

**Comment by dimfeld** [comment] 2022-01-12 09:10
Will be fixed by #1072

**Comment by dummdidumm** [comment] 2022-01-13 10:14
Closing as duplicate of #1067

**Closed by dummdidumm** 2022-01-13 10:14 UTC
