### ISSUE TITLE
Breaks CMD  + CLICK 

### ISSUE THREAD

**Issue by luispozo94** [sveltejs/language-tools#2069] opened 2023-06-26 16:41 UTC
Type: <b>Bug</b>

When you try to cmd + click to find a file when the Svelte extensio is enabled.. it breaks the shortcut.

Extension version: 107.6.0
VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|22, 22, 24|
|Memory (System)|64.00GB (28.13GB free)|
|Process Argv|--crash-reporter-id a38430f3-20fd-4105-8c75-68982f6793ed|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30773604
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
gsof1:30774496
e440d664:30776459
pythonidxpt:30772539
pythondjangotscf:30772537
pythonnocebcf:30776496

```

</details>

**Comment by jasonlyu123** [comment] 2023-06-26 22:49
I'll close this because this issue description is unactionable, and most people submitting the issue with VSCode UI never replies. If you have more detailed information, please open another issue with Github, follow our issue template, and provide a reproduction.

**Closed** 2023-06-26 22:49 UTC
