### ISSUE TITLE
Color Picker not working in VS Code with Svelte Extension

### ISSUE THREAD

**Issue by ejoflo** [sveltejs/language-tools#309] opened 2020-07-15 04:35 UTC
According to the feature list for the Svelte for VS Code extension:

CSS / SCSS / LESS
"Color highlighting and color picker"

However, when I open a .svelte file, and add a color or background-color property to under the <style> tag of said .svelte file, there is no color picker displayed.

The settings have the following enabled:
svelte.plugin.css.colorPresentations.enable - TRUE

**Comment by jasonlyu123** [comment] 2020-07-15 05:19
hmm... that works for me. Can you provide the content in your style?

**Comment by ejoflo** [comment] 2020-07-15 08:41
Here's a screenshot of a .svelte file, notice that there is no color picker on the background-color property.

![Screen Shot 2020-07-14 at 10 40 57 PM](https://user-images.githubusercontent.com/51680874/87523860-2da27d00-c623-11ea-83b1-cf0d344bf53f.png)

**Comment by jasonlyu123** [comment] 2020-07-15 09:15
oh! only the top-level one would have that. If it's under another tag it won't have CSS language feature. Only the component style would.

**Comment by ejoflo** [comment] 2020-07-15 09:35
> oh! only the top-level one would have that. If it's under another tag it won't have CSS language feature. Only the component style would.

Thanks for the reply. Could you clarify what you mean by "top-level"? The style tag above is inside of a Header.svelte tag. Is that not the same as a "component style"? Thank you.

**Comment by jasonlyu123** [comment] 2020-07-15 09:41
not a child of any tag. 
```svelte
<!-- this one -->
<style>

</style>

<svelte:head>
	<!-- not this one -->
	<style>
		.a {}
	</style>
</svelte:head>
```
https://svelte.dev/repl/6bdac66b78064f57ab2d12e425ff60f1?version=3.24.0

**Comment by ejoflo** [comment] 2020-07-15 09:51
This bug seems to be related to the Svelte prettier plugin. My current configuration is as follows:

 "svelteSortOrder" : "scripts-markup-styles",

Since my <style> tag is located at the bottom of my .svelte file, it loses the color picker. When I move the <style> tag all the way to the top of the file, the color picker re-appears.

**Comment by jasonlyu123** [comment] 2020-07-15 09:55
if it's not under any tag? Do you have any self-close tag before it?

**Comment by ejoflo** [comment] 2020-07-15 09:59
No, it is not under any tag. The <style> tag is independent.

**Comment by jasonlyu123** [comment] 2020-07-15 10:12
Can you provide the entire file or just the reproduable

**Comment by ejoflo** [comment] 2020-07-15 10:24
> Can you provide the entire file or just the reproduable

Sure, here it is on REPL:
https://svelte.dev/repl/9a3f422b49ec4097a1fd6e294b1bb386?version=3.24.0

**Comment by jasonlyu123** [comment] 2020-07-15 10:35
This is another form of #194 once you have an end tag of svelte:window instead of self-close the error would be gone.

**Comment by jasonlyu123** [comment] 2020-07-15 12:04
I was wrong. It's somewhat related topics to it. The actual problem is the arrow function. The parser thinks the tag has ended so it treat anything after it as text until it encounter a opening/closing tag again. So the self-close is ignored because it thinks it is just a text. 
The repo's syntax highlight parser also does the same thing so that's why anything behind it has no syntax highlight.

**Comment by jasonlyu123** [comment] 2020-07-15 12:09
I don't think this can be fixed soon. Maybe you can work around it by moving the event handler to the script.

**Comment by dummdidumm** [comment] 2020-08-05 11:35
Duplicate of #425

**Comment by dummdidumm** [comment] 2020-08-10 14:43
The REPL link shows me an empty file so I cannot reproduce this. Could you post the failing sample code directly in this issue @ejoflo ?

**Comment by jasonlyu123** [comment] 2020-08-27 05:01
minimal reproducible
```
<svelte:body on:click={() => {}} />

<style>
   div { 
        background-color: #ffffff
    }	
</style>
```

**Comment by jasonlyu123** [comment] 2020-08-27 05:27
Maybe we could allow multiple style sections in `CSSPlugin` and let the svelte compiler judge if there are multiple root style elements. That can enable language feature on style element like this
```svelte
<svelte:head>
  <style>

  </style>
</svelte:head>
```
and also pave the way for language features in the style attribute of https://github.com/sveltejs/language-tools/issues/381

**Closed** 2020-11-25 14:33 UTC
Labels: Fixed, bug
