### ISSUE TITLE
intellisense in the html part not as expected

### ISSUE THREAD

**Issue by btrauma8** [sveltejs/language-tools#714] opened 2020-12-13 13:53 UTC
I have the vs code 102.8.0 svelete plugin and no other svelte plugins.
made this from the svelte template, ran the setup typescript script.
is this expected? do i need to set some setting somewhere?
![image](https://user-images.githubusercontent.com/4399964/102013853-50db7080-3d18-11eb-9e57-3fa288c36ca5.png)

**Comment by jasonlyu123** [comment] 2020-12-13 13:59
Duplicate of #538 . This is a limitation of current solution. Once you type at least one character after `.` it would show up.

**Closed by jasonlyu123** 2020-12-13 13:59 UTC
