### ISSUE TITLE
weird syntax hilight

### ISSUE THREAD

**Issue by KryptoPX** [sveltejs/language-tools#1627] opened 2022-09-09 14:41 UTC
### Describe the bug

Syntax hilight gets weird in some case when import a ts file

### Reproduction

https://github.com/sveltejs/language-tools/issues/1627#issuecomment-1257347686

### Expected behaviour

Normal syntax hilight, i gess?

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![](https://user-images.githubusercontent.com/23123160/192175864-30fb1882-1fc1-4cf0-ae02-dba5633d239d.gif)

### Screenshots

![image](https://user-images.githubusercontent.com/79398439/189375488-1347efde-1500-4480-bf4a-e98130d4ae07.png)
![image](https://user-images.githubusercontent.com/79398439/189375663-4828007a-c11f-4139-ab3f-300d18305e20.png)
![image](https://user-images.githubusercontent.com/79398439/189375993-843f5baf-114a-417d-b4bc-7ff5da44b61c.png)
![image](https://user-images.githubusercontent.com/79398439/189377726-5c5a0edc-4922-4063-bd43-6982d4cecc21.png)

**Comment by jasonlyu123** [comment] 2022-09-10 03:35
Does this only happen in a specific file? Looks like something is wrong with source mapping to the generated code under the hood. We'll still need a reproducible to work on it. What do mean by "random moment"? Does it only happen during editing and it wouldn't persist if you restart the editor?

If it persists after you restart the editor. Can you copy the file to a new project and see if it still happens? Also, we'll need something we can copy and paste instead of just a screenshot.

@JoDo-dev @falco467 Is this what you're seeing?

**Comment by KryptoPX** [comment] 2022-09-10 16:39
Update... Maybe isn't refreshing info when i put some text or an enter

When i start VSCode:
![image](https://user-images.githubusercontent.com/79398439/189493040-46caf398-2f1a-44a3-a70f-04761c091b6b.png)

later when i add a new line:
![image](https://user-images.githubusercontent.com/79398439/189493079-cdd86ffd-4a52-4df1-aba2-9bab1b71b7da.png)

**Comment by jasonlyu123** [comment] 2022-09-12 04:49
Does the error disappear after restart? I want to know if it's related to how we update the file content stored in the memory. Also, please try removing some code to find a minimal reproduction. In text form, not a screenshot. We need more information to be able to help you.

**Comment by dummdidumm** [comment] 2022-09-15 08:48
This may be related to the semantic token highlight being too slow to apply. I've noticed this behavior a few times before where you write new code and for a brief time the highlighting is wrong, as if the tokens apply to the set range and VS Code isn't smart enough to move them with the word boundaries.

**Comment by RubenPX** [comment] 2022-09-26 01:17
Test case @jasonlyu123 @dummdidumm 

Steps:
1. [Download this repo](https://github.com/RubenPX/ATS/tree/99a745bcb7003653387150fe2b94f2e5b02c2698)
2. open with VSCode
3. open: `src\routes\+layout.svelte` and `src\components\layout\Header.svelte`
4. install dependencies
5. `npm run dev`
7. Rename `Header.svelte` to `header.svelte` and save all
8. edit any html part of header.svelte
9. The syntax will be wrong

PD: I'm @KryptoPX but using other account

**Comment by jasonlyu123** [comment] 2022-09-26 06:37
Thanks for the effort! I can reproduce it now. It seems like the problem is that after the file is renamed. VSCode is still using the old casing. But TypeScript uses the new casing. So there's a text sync mismatch.

**Comment by jasonlyu123** [comment] 2022-09-28 05:11
Reproduction steps:

1. open both `+layout.svelte` and `Header.svelte`.
2. focus the tab on `+layout.svelte` and restart the editor (reload window command also works). i.e. When the editor started. `Header.svelte` shouldn't be focused but it should be in the background tabs. 
3. rename `Header.svelte` to `header.svelte` and then focus the `header.svelte` tab.
4. edit header.svelte

Sounds to me that VSCode reuses the same text document object in the case-insensitive file system. But it could probably be fixed on our side. I think this might be the same issue as #1329 or at least some of the commenters.

**Comment by phcoliveira** [comment] 2022-10-22 13:46
I was going to create a new issue, but perhaps what I found can be fixed here as well.
BTW, I am willing to help with a PR, but I could use some guidance. Never worked syntax highlighting before.

Please check the picture below. The second script tag is not correctly highlighted.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/594605/197342206-98910e7e-5214-47c7-9449-e582c0bfb338.png">

If the attribute `lang="ts"` is removed from the second script tag, then the syntax highlighting works again.
Perhaps it should work like this by design, with a single usage of `lang="ts"` at the top, meaning that all other script tags will be preprocessed by TypeScript. But I found it to be weird.

Perhaps this is not actually a problem with the syntax highlighting at all. So I will look for a way to add an explanation about it in the docs.

**Comment by dummdidumm** [comment] 2022-10-22 14:41
Sounds like a bug. Can you provide a copy -pasteable snippet that reproduces this?

**Comment by phcoliveira** [comment] 2022-10-22 14:55
Sure thing, @dummdidumm.
```
<script context="module" lang="ts">
  export const foo = 'foo' // this is alright, you can add it or remove it
  export type Foo = 'foo' // adding an "export type" here does the trick.
</script>

<script lang="ts">
  let bar = 'bar'
</script>

<slot />
```

![image](https://user-images.githubusercontent.com/594605/197345985-9f92ba23-4d9c-4d43-aa0d-ff4676cdd2ae.png)

**Comment by phcoliveira** [comment] 2022-10-22 14:59
I need to rectify what I said before. Removing `lang="ts"` from the second script does not fix the problem. The highlighting is still weird and Svelte complains about using a preprocessor.
@dummdidumm 

![image](https://user-images.githubusercontent.com/594605/197346190-408ed9da-4e76-4c99-b389-6353aac10cfd.png)

**Comment by jasonlyu123** [comment] 2022-10-22 15:53
Sounds like https://github.com/sveltejs/language-tools/issues/1110

**Closed** 2022-11-29 15:17 UTC
Labels: bug, Fixed
