### ISSUE TITLE
detect potentially undefined values in templates

### ISSUE THREAD

**Issue by christophsturm** [sveltejs/language-tools#1893] opened 2023-02-23 11:05 UTC
### Describe the problem

I'm always frustrated when my website shows the string undefined.
for example in this code:
```svelte
<script lang="ts">
    type Product = {
    name: string;
    description?: string;
}
 const p: Product={name:"my fine product"}

 </script>
<div> name: {p.name} </div>
<div> description: {p.description} </div>
```

 And I think svelte could help me with that.

### Describe the proposed solution

I would like to see svelte force me to handle the state where `description` is undefined, and force me to fix my template like this:
```svelte
<div> name: {p.name} </div>
{#if p.description}
<div> description: {p.description} </div>
{/if}
```

### Alternatives considered

I really don't know of any alternative. live without type checking

### Importance

would make my life easier

**Comment by jasonlyu123** [comment] 2023-02-24 09:55
Closing as duplicate of #1582.

**Closed by jasonlyu123** 2023-02-24 09:55 UTC
Labels: enhancement
