### ISSUE TITLE
problem with  type-only imports for typescript

### ISSUE THREAD

**Issue by betfix** [sveltejs/language-tools#1092] opened 2021-07-09 08:19 UTC
I noticed a problem with syntax highlighting, auto-import, svelte-check and Quick Fix options for importing Typescript types.

E.g. for this code

```
<script lang="ts">
import { Link } from 'svelte-navigator'
export let navigate: NavigateFn
</script> 
```

1) auto-import
During typing the word "NavigateFn" intellisense displays a tooltip to auto-import this type from svelte-navigator. The auto-import adds the type to existing import, resulting in:
`import { Link, NavigateFn } from 'svelte-navigator'`

2) Quick Fix
The same happens when choosing a Quick Fix option to add NavigateFn to existing import (this is the only option to choose).

3) syntax highlighting
All is looking ok inside VSCode, despite adding a compiler option in tsconfig.json:
`"importsNotUsedAsValues": "error"`
Setting this option to "remove" or "preserve" seems to have no impact on VSCode behavior, either.

4) svelte-check
No error

During runtime there is an error:

> SyntaxError: The requested module '/node_modules/.pnpm/svelte-navigator@3.1.5_svelte@3.38.3+typescript@4.3.4/node_modules/svelte-navigator/src/index.js' does not provide an export named 'NavigateFn'

The expected behavior is to:

1) either display an error inside VSCode and in svelte-check, according to the `"importsNotUsedAsValues": "error"` typescript setting 

2) or make auto-import and Quick Fix use type-only import for types, resulting in code:
```
import { Link } from 'svelte-navigator'
import type { NavigateFn } from 'svelte-navigator'
```

**Comment by dummdidumm** [comment] 2021-07-09 08:45
The problem is within `svelte-preprocess`. Since `svelte-preprocess` only knows the content of the script, it does not know whether something is a type or a value import, so you need to strictly separate them. TypeScript can't help here because it's okay with `import` as long as there's at least one value import.
See https://github.com/sveltejs/svelte-preprocess/issues/318 for more info and a possible way to fix this.
Keeping this open for visibility

**Comment by dummdidumm** [comment] 2021-09-05 11:09
This is fixed with the latest version of `svelte-preprocess`, therefore closing this.

**Closed by dummdidumm** 2021-09-05 11:09 UTC
Labels: bug
