### ISSUE TITLE
Component refs and exported properties

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#330] opened 2020-07-22 10:26 UTC
**Is your feature request related to a problem? Please describe.**
I am not really sure if it is a feature request, bug report or request for docs. 

Svelte allows you to use exported const properties when using component refs.

`Child.svelte`:
```html
<script lang="ts">
  export const get = () => 'hey';
</script>
```

`Parent.svelte`:
```html
<script lang="ts">
  import Child from './Child.svelte';

  let childRef: Child | undefined = undefined;
  
  // Error: `Property 'get' does not exist on type 'Child__SvelteComponent_'.` when calling the function
  const call = () => childRef!.get();
</script>

<Child bind:this={childRef} />
```

**Describe the solution you'd like**
It would be cool if the compiler knew the signatures of exported properties automatically.

**Describe alternatives you've considered**
I see two alternatives, both of which drop the typing security drastically:
1. use `any` for refs
2. assign the type explicitly
```typescript
let childRef: Child & { get: () => string }
```
It's bad, because when child changes its signature parent would never know about it until we manually update the signature.

**Comment by dummdidumm** [comment] 2020-07-22 10:28
Duplicate of #307

**Closed by dummdidumm** 2020-07-22 10:28 UTC
