### ISSUE TITLE
Support container-type CSS property

### ISSUE THREAD

**Issue by amyjko** [sveltejs/language-tools#2208] opened 2023-11-21 20:23 UTC
### Describe the bug

A CSS declaration with `container-type` generates an "Unknown property: 'container-type' (css)" message. This property is [widely supported](https://caniuse.com/?search=container-type) and probably shouldn't be a warning anymore.

### Reproduction

Create a Svelte component with this style:

```
<style>
  div {
    container-type: inline-size;
  }
</style>
```

Run `svelte-check`, see the warning:

```
Warn: Unknown property: 'container-type' (css)
        container-type: inline-size;
    }
```

### Expected behaviour

I do not expect a warning on this valid CSS property.

### System Info

- OS: mac OS 14.0
- IDE: VS Code 1.84.2

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment] 2023-11-21 23:06
Closing as duplicate of #1888. Let's keep all the container-related stuff in that issue.

**Closed** 2023-11-21 23:07 UTC
Labels: bug
