### ISSUE TITLE
TS type guard not respected in event callback

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/language-tools#1657] opened 2022-09-22 13:41 UTC
### Describe the bug

TS type guard is not respected in event callbacks

### Reproduction

Here I'm checking that radio exists in dataCell to then use it in the event callback:

![image](https://user-images.githubusercontent.com/53383860/191761907-2c9b3d67-a0b2-45ea-a988-b617d8711ef7.png)

### Expected behaviour

I expect no error to be thrown.

A workaround to this is by using `@const`
![image](https://user-images.githubusercontent.com/53383860/191762636-e9b6b7ad-5f36-4c0a-9fd5-f615420ea5dc.png)

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment] 2022-09-22 13:45
Duplicate of #876 - the question is whether or not this is "works as designed".

**Closed by dummdidumm** 2022-09-22 13:45 UTC
Labels: bug
