### ISSUE TITLE
Syntax highlighting breaks when using typescript and linebreaks

### ISSUE THREAD

**Issue by andremacola** [sveltejs/language-tools#1980] opened 2023-04-10 05:32 UTC
### Describe the bug

When you have only one line break right after defining a typing the Syntax highlighting breaks.

### Reproduction

Even in the Github Preview the error is showing

Without error
```svelte
<script lang="ts">
  export let label: string

</script>

<div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p></div>
```

With error
```svelte
<script lang="ts">
  export let label: string
</script>

<div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p></div>
```

### Expected behaviour

Correct Syntax highlighting

### System Info

- IDE: VSCode, Github Preview

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

https://user-images.githubusercontent.com/3408809/230832932-e78b98ee-1b03-41fd-a884-1827607db72e.mp4

**Comment by jasonlyu123** [comment] 2023-04-10 05:34
Duplicate of #1970

**Closed by jasonlyu123** 2023-04-10 05:34 UTC
Labels: bug
