### ISSUE TITLE
Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by sadafansari180** [sveltejs/language-tools#2456] opened 2024-08-01 16:02 UTC
Type: <b>Bug</b>

Extension Bisect is active and has disabled 9 extensions. Check if you can still reproduce the problem and proceed by selecting from these options.

1. start extension bisect 
2. i can repeoduce 
3. stop bisect

I don't understand which option seleted

Extension version: 108.5.4
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (8.26GB free)|
|Process Argv|--crash-reporter-id ea4c21ba-cceb-4fcc-81aa-3c1a82149b9e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31101459
ccplti:31103428
pythonrstrctxtcf:31103194

```

</details>

**Comment by jasonlyu123** [comment] 2024-08-01 16:06
I'll close this because this issue description is unactionable, and most people submitting issues with VSCode UI never reply. If you have more detailed information, please open another issue with Github, follow our issue template, and provide a reproduction repository.

Here are some pointers for common user errors:
https://github.com/sveltejs/language-tools/issues/2287#issuecomment-1934044841
https://github.com/sveltejs/language-tools/issues/2278

**Closed by jasonlyu123** 2024-08-01 16:06 UTC
