### ISSUE TITLE
[TypeScript] Declaring variable as type, without a value, without a semicolon, as the last item in the <script>, messes up syntax highlighting in VS Code

### ISSUE THREAD

**Issue by D-Marc1** [sveltejs/language-tools#1993] opened 2023-04-23 17:19 UTC
### Describe the bug

Declaring the final item in the `<script>` as a type, without setting a value, without a semicolon, messes up the syntax highlighter:

```svelte
<script lang="ts">
export let name: string
</script>

<p>{name}</p>
```

### Reproduction

Say I have the following Svelte file:

```svelte
<script lang="ts">
export let name: string
</script>

<p>{name}</p>
```

This will mess up the syntax highlighting.

However, the syntax highlighting is fixed by setting a default value to the variable, using a semicolon or setting a variable to a value under it:

**Setting default value to variable**

```svelte
<script lang="ts">
export let name = ''
</script>

<p>{name}</p>
```

**Using a semicolon**

```svelte
<script lang="ts">
export let name: string;
</script>

<p>{name}</p>
```

**Setting default value to a variable as the last item in the `<script>`**

```svelte
<script lang="ts">
export let name: string
export let count = 0
</script>

<p>{name}</p>
```

Notice how even on GitHub's syntax highlighter, you can see the difference between by first example and last 3 ones.

### Expected behaviour

The expected behavior is that declaring a variable as a type as the last item in the `<script>`, without setting it to value, without semicolons, shouldn't break the syntax highlighting.

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

**Syntax highlighting breaking**

<img width="216" alt="Screen Shot 2023-04-23 at 1 18 03 PM" src="https://user-images.githubusercontent.com/30007968/233854677-74c15602-fa84-45ee-8607-60240b62e358.png">

**Syntax highlighting working**

<img width="195" alt="Screen Shot 2023-04-23 at 1 18 26 PM" src="https://user-images.githubusercontent.com/30007968/233854679-d637e001-9f91-4579-9b5b-917d40bbfa23.png">

**Comment by jasonlyu123** [comment] 2023-04-23 23:19
Duplicate of #1970

**Closed by jasonlyu123** 2023-04-23 23:19 UTC
Labels: bug
