### ISSUE TITLE
Using derived store together with $derived rune throws TS error

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/language-tools#2629] opened 2024-12-12 12:01 UTC
### Describe the bug

Note: I'm not sure if this is the right repo to post this.

In my SvelteKit app i'm deriving something from the `page` store while also deriving a value from a rune.

In this component i get an error (see images below), but it seems like a completely valid thing to looking at this REPL: https://svelte.dev/playground/3c5aeb154a48436ebed50948786726f7?version=5.11.2

I'm not sure if this is coming from the language-server, or if it is something wrong with TypeScript.

### Reproduction

<img width="491" alt="image" src="https://github.com/user-attachments/assets/ea38d8b8-19aa-43b5-8b63-52ba90ce935e" />

<img width="589" alt="image" src="https://github.com/user-attachments/assets/ade7438d-8d04-4fc7-8a4d-6c5ff1109b49" />

<img width="577" alt="image" src="https://github.com/user-attachments/assets/286f3a09-1d28-42b8-8376-7791617f8607" />

### Expected behaviour

An error should not be thrown

### System Info

- OS: macOS 15.1.1 (24B91)
- IDE: VScode

### Which package is the issue about?

svelte-language-server, svelte-check

**Comment by dummdidumm** [comment] 2024-12-12 14:21
Closing as duplicate of #2605

**Closed by dummdidumm** 2024-12-12 14:21 UTC
Labels: bug
