### ISSUE TITLE
Calling possibly undefined check throws false positive within anonymous function

### ISSUE THREAD

**Issue by Rudedog9d** [sveltejs/language-tools#1891] opened 2023-02-22 16:01 UTC
### Describe the bug

Svelte-check will return the following error when calling a method that is possibly undefined.

> Error: Cannot invoke an object which is possibly 'undefined'. (ts)

The call is wrapped in an `{#if function}`, so the function will always be defined. The check works correctly if the call is not wrapped in an anonymous function. 

This seems related to https://github.com/sveltejs/language-tools/issues/619

### Reproduction

This snippet throws the error

```svelte
<script lang="ts">
  export let addMember: ((email: string) => void) | undefined = undefined;
  export let admin: boolean = false;
  let addMemberInput = '';
</script>

{#if addMember && admin}
  <section class="w-full">
    <form
      class="flex gap-5 text-xl font-semibold mt-10 w-full"
      on:submit|preventDefault={() => addMember(addMemberInput)}>
      <label for="team-name">Add Teammate: </label>
      <input id="team-name" bind:value={addMemberInput} />
      <input type="submit" value="Add" />
    </form>
  </section>
{/if}
```

This snippet does not, although it throws an error on passing an event instead of a string. only change is the way `addMember` is called

```svelte
<script lang="ts">
  export let addMember: ((email: string) => void) | undefined = undefined;
  export let admin: boolean = false;
  let addMemberInput = '';
</script>

{#if addMember && admin}
  <section class="w-full">
    <form class="flex gap-5 text-xl font-semibold mt-10 w-full" on:submit|preventDefault={addMember}>
      <label for="team-name">Add Teammate: </label>
      <input id="team-name" bind:value={addMemberInput} />
      <input type="submit" value="Add" />
    </form>
  </section>
{/if}
```

Current workaround is to call it like this: `() => addMember && addMember(addMemberInput)`

### Expected behaviour

Svelte-check shouldn't throw an error when calling a function within an anonymous function.

### System Info

- OS: Linux
- IDE: Webstorm - but this error came from CI/CLI, running `svelte-check --tsconfig ./tsconfig.json`

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

The instance this appeared in production for us is here:

https://gitlab.com/c2-games/ux/c2-games-ui/-/blob/8b8291c2e61d01157f5c174725643a212e003cd9/src/lib/components/pages/team-dashboard/TeamTable.svelte#L69

Full error:

```svelte
/home/bdavis/Dev/c2-games-ui/src/lib/components/pages/team-dashboard/TeamTable.svelte:69:39
Error: Cannot invoke an object which is possibly 'undefined'. (ts)
      class="flex gap-5 text-xl font-semibold mt-10 w-full"
      on:submit|preventDefault={() => addMember(addMemberInput)}>
      <label for="team-name" class="min-w-fit">Add Teammate: </label>
```

**Comment by dummdidumm** [comment] 2023-02-22 16:17
Thank you for the detailed issue! Closing as a duplicate of #876

**Closed by dummdidumm** 2023-02-22 16:17 UTC
Labels: bug
