### ISSUE TITLE
Definition of TS prop breaks formatting without semi

### ISSUE THREAD

**Issue by eivindchr** [sveltejs/language-tools#1995] opened 2023-04-26 11:55 UTC
### Describe the bug

This happens if the last line is a TS prop and you don't add a semi.

### Reproduction

Make a simple Svelte component with a single Typescript prop and don't add a semi at the end. 

### Expected behaviour

I expect it to work the same way as if you add a semi

### System Info

- OS: MAC 13.3.1
- IDE: VSCode 1.77.3 

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="964" alt="Screenshot 2023-04-26 at 13 50 18" src="https://user-images.githubusercontent.com/35451285/234567386-61952424-23ff-4a61-b620-8c1b7491b48e.png">
<img width="959" alt="Screenshot 2023-04-26 at 13 49 58" src="https://user-images.githubusercontent.com/35451285/234567402-af212ed8-a2b4-4321-acf2-ef11cd9fc137.png">

**Comment by jasonlyu123** [comment] 2023-04-26 12:18
Duplicate of #1970

**Closed by jasonlyu123** 2023-04-26 12:18 UTC
Labels: bug
