### ISSUE TITLE
Not folding properly

### ISSUE THREAD

**Issue by eldhoz515** [sveltejs/language-tools#1787] opened 2022-12-17 11:33 UTC
Type: <b>Bug</b>

Add some code in svelte file. Try fold all from command palette. It folds it all wrong. Folding in .svelte files is a mess.

Extension version: 106.3.2
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

**Comment by jasonlyu123** [comment] 2022-12-17 14:12
Please follow the issue template and do not use external tools to create issues.  We need more info to be able to help you. 

Currently folding is based on indentation and not the semantic mean of the code. I guess this is what you mean. So I am close this as a duplicate of #1704.

**Closed by jasonlyu123** 2022-12-17 14:12 UTC
