### ISSUE TITLE
Exports other than default are not supported in typescript

### ISSUE THREAD

**Issue by cortopy** [sveltejs/language-tools#648] opened 2020-11-02 11:09 UTC
**Describe the bug**
[As per the docs](https://svelte.dev/docs#script_context_module) when exporting something from a `<script context="module">`that something is available to import in javascript files.

```svelte
<script context="module">
	let totalComponents = 0;

	// this allows an importer to do e.g.
	// `import Example, { alertTotal } from './Example.svelte'`
	export function alertTotal() {
		alert(totalComponents);
	}
</script>

<script>
	totalComponents += 1;
	console.log(`total number of times this component has been created: ${totalComponents}`);
</script>
```

**To Reproduce**
However, when trying a similar example to the docs in typescript I get a similar error to this:

```
Module '"*.svelte"' has no exported member 'alertTotal'. Did you mean to use 'import alertTotal from "*.svelte"' instead?
```

**Expected behavior**
It's possible to import types, variables, functions, etc. from any module context in a component

Ideally both `import` and `import type` should be supported

**System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: Svelte for VS Code

**Comment by dummdidumm** [comment] 2020-11-02 11:22
Duplicate of #550

**Closed by dummdidumm** 2020-11-02 11:22 UTC
Labels: bug
