### ISSUE TITLE
svelte-language-server neovim, end tags duplicated

### ISSUE THREAD

**Issue by cpt-n3mo** [sveltejs/language-tools#1905] opened 2023-02-28 09:05 UTC
Good day.

i was wondering if someone can help me with this one.
when i use svelte-language-server inside neovim, and for instance in the html type div it cleanly autocompletes on enter, but pressing enter again for a new line will give a second end tag so it becomes like this after 2 enter presses  

```html

<div></div></div>

```

repeating enter will continue to add end tags.
this seems weird. is this a setting or might it be a bug..?

kind regards.

**Comment by jasonlyu123** [comment] 2023-02-28 09:48
Duplicate of #1844. Let's keep the discussion there.

**Closed by jasonlyu123** 2023-02-28 09:48 UTC

**Comment by diogenesofweb** [comment] 2023-03-02 12:47
Removing ">" from trigger characters in nvim LSP config should help

```vim
local nvim_lsp = require('lspconfig')

nvim_lsp.svelte.setup {
  -- ...
  on_attach = function (client, bufnr) 
    client.server_capabilities.completionProvider.triggerCharacters = {
      ".",
      '"',
      "'",
      "`",
      "/",
      "@",
      "<",
      --  Emmet
      -- ">",
      "*",
      "#",
      "$",
      "+",
      "^",
      "(",
      "[",
      "@",
      "-",
      --  Svelte
      ":",
      "|",
    }

    return on_attach(client, bufnr)
  end,
}
```

**Comment by jasonlyu123** [comment] 2023-03-02 13:38
If that works, then the problem might not be what I mentioned in #1844 but how the completion plugin chose a trigger character. If that is the case, we can probably skip the HTML completion in case of a trigger character of `>.` 

But I will need some help with confirming the fix. I have trouble getting the completion plugin to work in neovim 😅
