### ISSUE TITLE
Make custom store `$` access type resolve to `const` and/or `readonly` type

### ISSUE THREAD

**Issue by Not-Jayden** [sveltejs/language-tools#2045] opened 2023-06-06 05:42 UTC
### Description

When implementing a custom store without a `set()` method, it's possible to still attempt to directly assign a value to the store. 

e.g.

```ts
function createCount() {
	const { subscribe, set, update } = writable(0);

	return {
		subscribe,
		increment: () => update(n => n + 1),
		decrement: () => update(n => n - 1),
		reset: () => set(0)
	};
}

const count = createCount();

// Type: let $count: number
$count = 99; // This doesn't show a type error despite not having a .set() method
```

I have recently been refactoring a codebase to use custom stores to make sure our logic is better encapsulated, but missed these places due to not receiving any errors that I would have anticipated typescript or svelte-check would cover.

### Proposed solution

If a custom store without a `.set()` is accessed using the `$` key inside a svelte file, it should resolve to a `const` instead of a `let`, as well as resolve the store value type as readonly (e.g. wrap in`Readonly<T>`)  to ensure nested object properties can't be assigned to either.

For example, the above example would instead resolve to:
```ts
// Type: const $count: number;
$count = 99 // Error: Cannot assign to '$count' because it is a constant.(2588)
```

### Alternatives

Unsure, maybe it shouldn't be resolved with any type changes but instead a svelte-check error of some kind?

**Comment by jasonlyu123** [comment] 2023-06-06 06:40
Closing as duplicate of #1906

**Closed by jasonlyu123** 2023-06-06 06:40 UTC

**Comment by Not-Jayden** [comment] 2023-06-06 06:44
Thanks 🙏
