### ISSUE TITLE
Please make the svelte.config.js file available to esm users

### ISSUE THREAD

**Issue by GitGangGuy** [sveltejs/language-tools#519] opened 2020-09-03 12:44 UTC
**Is your feature request related to a problem? Please describe.**
ES Modules are the future, and many have realized this. NodeJS has introduced [experimental esm support](https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules) and popular players in open source are enforcing the use of them; for example, airbnb's widely known [javascript style guide](https://github.com/airbnb/javascript) is already forbidding the [use of non-standard module systems](https://github.com/airbnb/javascript#modules--use-them) - this includes CommonJS.  
To enable ESM support across my entire project, I set `"type": "module"` in my `package.json`. Unfortunately, svelte-vscode expects that the svelte.config.js file is written in commonjs and attempts to require it, which breaks it for me and others using esm. Furthermore, svelte-vscode ignores the svelte config file if it has the `.cjs` file ending, which is non standard-compliant behavior and leaves me no option to use the svelte language server/svelte-vscode.

**Describe the solution you'd like**
ES Modules are the only true standard-conformant way of using modules, and even though they're in experimental support I haven't encountered any issues with using them. Please don't strictly `require()` the consumers config file (which might be written in esm and therefore cannot be required), but either infer the module system type from the file ending (`.cjs` vs `.mjs`) and import/require it based on that information or try to automatically detect the module system used. 
**Describe alternatives you've considered**
The alternative is to switch my whole project back to the commonjs default, but that would mean I would have to rewrite a lot of files back into commonjs and I'd loose all the nice features of esm. I shouldn't have to migrate my full project over for one config file that can only be read if it has a `.js` file ending in commonjs format. :/

**Comment by dummdidumm** [comment] 2020-09-03 12:45
Duplicate of #509

**Closed by dummdidumm** 2020-09-03 12:45 UTC

**Comment by dummdidumm** [comment] 2020-09-07 07:26
Why does using the CommonJS syntax in a config file unrelated to the rest of your project prevent you from using ESM syntax in the rest of your project?

**Comment by GitGangGuy** [comment] 2020-09-17 15:21
@dummdidumm svelte-vscode won't read the svelte.config.[ending] file if it has the `.cjs` file ending, which is the only way I can use commonjs in an esm project.

**Comment by dummdidumm** [comment] 2020-09-17 15:41
`svelte.config.js` is not read by anybody except the language server and maybe Svite, noone else uses that config file. So you should be able to use commonjs in there without problems, because the rest of the code is not dependent on that file.

**Comment by dummdidumm** [comment] 2020-09-23 07:53
You should now be able to user `.cjs` config files.
