### ISSUE TITLE
Missing autocomplete suggestions for namespaced components in the template

### ISSUE THREAD

**Issue by AdrianGonz97** [sveltejs/language-tools#2085] opened 2023-07-08 15:03 UTC
### Describe the bug

If we were to reexport components like so:
```ts
import Button from "./CardButton.svelte";
import Title from "./CardTitle.svelte";
import Description from "./CardDescription.svelte";

export default {
	Button,
	Title,
	Description,
};
```

and import them to be used as a namespace:
```svelte
<script lang="ts">
	import Card from "./Card.svelte";
	import C from "./children";
</script>

<Card>
	<C.Title>Hello World</C.Title>
	<C.Description>
		Lorem Ipsum is simply dummy text of the printing and typesetting industry.
	</C.Description>
	<C.Button>Get started</C.Button>
</Card>
```

<hr>

Then we wouldn't get any autocomplete suggestions when typing `<C.>`...

![img](https://i.imgur.com/LeZFf0M.gif)

<hr>

But! If we were to _**close**_ the suggestions and _**reopen**_ it again (so long as we have some valid starting letter), _then_ we'd actually get the proper autocomplete suggestions.

![img](https://i.imgur.com/RQUA8Zr.gif)

### Reproduction

git repo:
```bash
git clone https://github.com/AdrianGonz97/no-autocomplete-suggestions-on-namespaces-issue
```

### Expected behaviour

Ideally, the provided suggestions would be the same as if we were to place the value in mustache tags, like so:

![img](https://i.imgur.com/DEggqdt.png)

### System Info

- OS: WSL2 Ubuntu
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension, svelte-language-server

**Comment by jasonlyu123** [comment] 2023-07-08 15:11
Closing as duplicate of  #776. This is a limitation we have now. If the template has a syntax error, only global completion will be shown. We have special treatment for mustaches, but the same technique is not applicable in a namespaced component.

**Closed by jasonlyu123** 2023-07-08 15:11 UTC
Labels: bug

**Comment by AdrianGonz97** [comment] 2023-07-08 15:24
@jasonlyu123 Thanks for the quick response, it's very much appreciated! 

Might I make a suggestion about editing the title of that original issue to include "Namespace"? It would probably make it easier for people in the future that want to search for that issue 😄
