### ISSUE TITLE
Slot component described as svelte slot

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#733] opened 2021-01-04 09:35 UTC
<img width="418" alt="Code_2021-01-04_10-31-43" src="https://user-images.githubusercontent.com/30108880/103521101-81767c00-4e78-11eb-8093-a610f8da9f26.png">

**Comment by dummdidumm** [comment] 2021-01-04 09:49
Duplicate of #711 , should be fixed with the next release.

**Closed by dummdidumm** 2021-01-04 09:49 UTC
Labels: bug

**Comment by pushkine** [comment] 2021-01-04 13:13
mb
