### ISSUE TITLE
Types: Exported functions and properties of a component are not visible on the components type

### ISSUE THREAD

**Issue by AlexAegis** [sveltejs/language-tools#356] opened 2020-07-25 11:34 UTC
Exported properties and functions should appear on the components type

app.svelte
```svelte
<script lang="ts">
  import Foo from './foo.svelte';
  import { onMount } from 'svelte';

  const myFoo!: Foo;
  onMount(() => {
    console.log(myFoo.foo); // Property 'foo' does not exist on type 'Foo__SvelteComponent_'.ts(2339)
    console.log(myFoo.bar); // Property 'bar' does not exist on type 'Foo__SvelteComponent_'.ts(2339)
    console.log(myFoo.fooBar); // Property 'fooBar' does not exist on type 'Foo__SvelteComponent_'.ts(2339)
    // But all three outputs the correct results
  });
</script>

<Foo bind:this={myFoo} />
```

foo.svelte
```svelte
<script lang="ts">
  export const foo = 10;
  export function bar() {};
  export const fooBar = () => {};
</script>
```

**Comment by jasonlyu123** [comment] 2020-07-25 11:45
Duplicate of #307

**Closed by jasonlyu123** 2020-07-25 11:45 UTC
