### ISSUE TITLE
VSCodium/Code-OSS support

### ISSUE THREAD

**Issue by rewkha** [sveltejs/language-tools#242] opened 2020-06-28 11:15 UTC
I'm using the OSS version of VSCode - VSCodium. But it isn't possible to setup this plugin from the OSS plugins search. By the way I've tried the installation using VSIX file, but I only have an old version of vsix from UnwrittenFun repo which isn't working. Just got the message "Reload the app to complete installation", but after reloading got nothing.

I don't know the real root of the problem, maybe VSIX file in github releases will be enough if plugin starts. But if not - is there any possibilities to support Code-OSS and VSCoium?

**Comment by orta** [comment] 2020-06-28 13:20
Sure, happy to get this added to the deploy process. PRs are welcome.

**Comment by orta** [comment] 2020-06-28 13:20
Dupe of #238

**Closed by orta** 2020-06-28 13:20 UTC
