### ISSUE TITLE
bind:contentRect shows typescript linting error when used in <div> although code works.

### ISSUE THREAD

**Issue by mongodillo** [sveltejs/language-tools#2081] opened 2023-07-04 05:20 UTC
### Describe the bug

![image](https://github.com/sveltejs/language-tools/assets/92282907/0c775b6b-3375-4f03-8bf1-6ca18fc8e3df)

1. Getting a lint error which mentions `Property 'contentRect' does not exist on type 'HTMLDivElement'.ts(2339)`

2. tooltip for bind:contentRect mentions `Available for all elements. (read-only)`

is this a false positive linting error ? 

Code runs fine.

### Reproduction

using fresh npm create svelte@latest installation with Svelte 4.

```
<script lang="ts">
let newRect: DOMRectReadOnly
//does stuff with newRect here
</script>

<div bind:contentRect={newRect}>
	<slot />
</div>
```

### Expected behaviour

Given tooltip mentions bind:contentRect is available on all elements, I do not expect any linting errors.

Code otherwise runs fine.

### System Info

- OS: Windows 10
- IDE: VS Code with Svelte extension 107.6.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2023-07-04 05:22
Duplicate of #2066

**Closed by jasonlyu123** 2023-07-04 05:22 UTC
Labels: bug
