### ISSUE TITLE
Unused export property warning is on the wrong line when using the TypeScript pre-processor.

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#489] opened 2020-08-26 22:05 UTC
**Describe the bug**
`export let` statements of an unused property cause a warning. The warning is displayed on the line above the actual property for me.

**To Reproduce**

Set the script language to typescript (`lang="ts"` or `type="text/typescript"`).
Declare some export property, do not use it anywhere.

**Expected behavior**

The warning is on the property not being used.

**Screenshots**

![image](https://user-images.githubusercontent.com/834235/91361338-5e67fb80-e7f8-11ea-8436-282065c2a241.png)

If the property is in the first line of the script:

![image](https://user-images.githubusercontent.com/834235/91361408-8192ab00-e7f8-11ea-96bd-eeca55a8de72.png)

**System (please complete the following information):**
 - OS: Windows 10, 64bit
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment] 2020-08-26 22:56
Try update your @tsconfig/svelte to lastest

**Comment by brunnerh** [comment] 2020-08-27 00:21
I am not using that.
Added it temporarily, did nothing.

**Comment by jasonlyu123** [comment] 2020-08-27 00:38
Oh I thought you were using the official template. The package is a base config for svelte. You can update the  `extends` of your `tsconfig.json` to match this.
https://github.com/sveltejs/template/blob/8194bf8f6452f8117195bf304ac99b15d329fbb3/scripts/setupTypeScript.js#L87

**Comment by jasonlyu123** [comment] 2020-08-27 00:45
Duplicate of #375

**Comment by brunnerh** [comment] 2020-08-27 19:45
@jasonlyu123 As i said, i added the base config temporarily but nothing changed. I still get the errors on the wrong line.

**Comment by jasonlyu123** [comment] 2020-08-27 22:55
Then can you try run `tsc` to compile a ts file in your workspace and see if the output file has sourcemap?

**Comment by jasonlyu123** [comment] 2020-08-27 23:09
The problem is with sourcemap. We use the svelte compiler to get svelte diagnostics. if you have a svelte.config.js and specify your preprocessor in it we would use that to preprocess, other than that we'll use the official svelte-preprocess. And if the preprocessor doesn't return a sourcemap the warning would be in a wrong position.

**Comment by brunnerh** [comment] 2020-08-28 00:32
It does not always generate source maps. If i call `tsc` on a single file it apparently does not load the tsconfig; if i use `tsc -p .` or `tsc --build tsconfig.json` it will output the source map as expected.

**Comment by jasonlyu123** [comment] 2020-08-28 00:52
Can I take a look at your `svelte.config.js` if you have it, also which preprocessor do you use?

**Comment by brunnerh** [comment] 2020-08-28 01:27
I use the default processor, which should be `svelte-preprocess` in auto mode. I made a [minimal example repository](https://github.com/brunnerh/svelte-misplaced-error-issue) which has the errors on the input component.

I tried creating a `svelte.config.js`, explicitly setting the pre-processor in auto mode, did not matter. Explicitly using only the `typescript` one with a path to the `tsconfig.json` did not do anything either.

**Comment by jasonlyu123** [comment] 2020-08-28 01:34
Ummm... this is unexpected, it would only work when I also set `sourcemap` to true in `tsconfig.json`

**Comment by brunnerh** [comment] 2020-08-28 01:41
Then the `extends` does not quite work. Well, i do not mind setting that explicitly for now.
Thanks

**Comment by jasonlyu123** [comment] 2020-08-28 02:00
Yeah, I have a quick look at the source file of the svelte-preprocess. It looks like it doesn't parse the `extend`.
Thanks for the issue!

**Comment by dummdidumm** [comment] 2020-08-28 06:39
I opened [this issue](https://github.com/sveltejs/svelte-preprocess/issues/230) over at `svelte-preprocess`, because [according to the docs](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#auto-preprocessing-options), in auto-preprocessing mode, source maps should be generated.

@brunnerh if you remove `"sourceMaps": true` and the base config reference from your `tsconfig.json` and instead do `sveltePreprocess({sourceMap: true})` in your `svelte.config.js`, does it show the warnings at the correct line then?

**Comment by brunnerh** [comment] 2020-08-28 17:02
> @brunnerh if you remove `"sourceMaps": true` and the base config reference from your `tsconfig.json` and instead do `sveltePreprocess({sourceMap: true})` in your `svelte.config.js`, does it show the warnings at the correct line then?

No, still off.

**Comment by dummdidumm** [comment] 2020-08-28 17:04
So it only works if you add `"sourceMaps": true` to the `tsconfig.json`?

**Comment by brunnerh** [comment] 2020-08-28 18:46
Yes

**Closed** 2021-01-26 13:23 UTC
Labels: bug

**Comment by stefanosandes** [comment] 2023-09-21 19:30
Hello Guys!

I don't know if this issue is being tracked elsewhere, but I believe this problem is sensitive to changes in `svelte.config.js`.

I am using MeltUI, so here are the results:
![Group 2074](https://github.com/sveltejs/language-tools/assets/6722075/800c304f-218f-4b46-8d80-9a58ebf2e519)

Just variations 1 and 2 show the warning in the correct position.

The variations are:

```
import sequence from 'svelte-sequential-preprocessor';
import adapter from '@sveltejs/adapter-vercel';
import { vitePreprocess } from '@sveltejs/kit/vite';
```
1 - OK: `preprocess:vitePreprocess(),`
2 - OK: `preprocess:[vitePreprocess()],`
3 - WRONG: `preprocess:[vitePreprocess(), preprocessMeltUI()],`
4 - WRONG: `preprocess:[preprocessMeltUI(), vitePreprocess()],`
5 - WRONG: `preprocess:sequence([vitePreprocess()],`

**Comment by martinjo** [comment] 2023-10-24 05:08
> Hello Guys!
> 
> I don't know if this issue is being tracked elsewhere, but I believe this problem is sensitive to changes in `svelte.config.js`.
> 
> I am using MeltUI, so here are the results: ![Group 2074](https://user-images.githubusercontent.com/6722075/269731694-800c304f-218f-4b46-8d80-9a58ebf2e519.png)
> 
> Just variations 1 and 2 show the warning in the correct position.
> 
> The variations are:
> 
> ```
> import sequence from 'svelte-sequential-preprocessor';
> import adapter from '@sveltejs/adapter-vercel';
> import { vitePreprocess } from '@sveltejs/kit/vite';
> ```
> 
> 1 - OK: `preprocess:vitePreprocess(),` 2 - OK: `preprocess:[vitePreprocess()],` 3 - WRONG: `preprocess:[vitePreprocess(), preprocessMeltUI()],` 4 - WRONG: `preprocess:[preprocessMeltUI(), vitePreprocess()],` 5 - WRONG: `preprocess:sequence([vitePreprocess()],`

Did you solve this? I’m running into the same problem when trying to use MeltUI in my SvelteKit project.

**Comment by stefanosandes** [comment] 2023-10-24 13:26
> > Hello Guys!
> > I don't know if this issue is being tracked elsewhere, but I believe this problem is sensitive to changes in `svelte.config.js`.
> > I am using MeltUI, so here are the results: ![Group 2074](https://user-images.githubusercontent.com/6722075/269731694-800c304f-218f-4b46-8d80-9a58ebf2e519.png)
> > Just variations 1 and 2 show the warning in the correct position.
> > The variations are:
> > ```
> > import sequence from 'svelte-sequential-preprocessor';
> > import adapter from '@sveltejs/adapter-vercel';
> > import { vitePreprocess } from '@sveltejs/kit/vite';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 1 - OK: `preprocess:vitePreprocess(),` 2 - OK: `preprocess:[vitePreprocess()],` 3 - WRONG: `preprocess:[vitePreprocess(), preprocessMeltUI()],` 4 - WRONG: `preprocess:[preprocessMeltUI(), vitePreprocess()],` 5 - WRONG: `preprocess:sequence([vitePreprocess()],`
> 
> Did you solve this? I’m running into the same problem when trying to use MeltUI in my SvelteKit project.

Not a solution, but a workaround. I removed the MeltUI preprocessor and am now using Melt components in a destructuring style.

**Comment by martinjo** [comment] 2023-10-24 20:47
Ok, thanks! Seems like the most reasonable thing to do. I've already spent way too much time looking for a solution to this now 🤦‍♂️
