### ISSUE TITLE
Cannot save `.svelte` file + flickering imports

### ISSUE THREAD

**Issue by douglashellowell** [sveltejs/language-tools#1710] opened 2022-11-04 21:58 UTC
### Describe the bug

When a `.svelte` file has two `import` statements without a line-break between them and has unsaved changes made to the file a number of visual and behavioural bugs happen when I try and save the file - *until I press another key* - then the bug stops.

**When saving the file:**
1. The file does not save
2. The file is not formatted
3. The import statements _apart from the first one_ lose syntax highlighting and have a slight flicker
4. if the cursor is within the `import` statements it is moved to the end
5. if the added change is an unused import or single word (i.e `hello`) then it is removed

**When pressing another key**
 1. the character is added to the document **then** the document is saved
 2. visual bugs from above stop
 3. sometimes it takes two key presses

### Reproduction

Write a `.svelte` file that has two or more `import` statements that are being used within the component

> e.g 

```html
<script lang='ts'>
    import Foo from './Foo.svelte';
    import Bar from './Bar.svelte';
</script>

<Foo />
<Bar />
```

make changes to the file and save it. Press another key (`A-Z`, `0-9`, `space`, `enter` or any symbol)

### Expected behaviour

I expected the file to save

### System Info

- OS: OSX 12.6
- IDE: VSCode Version: 1.73.0 (Universal)

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="586" alt="image" src="https://user-images.githubusercontent.com/53038423/200080656-246d6811-aeaa-4cac-a783-df03645ebf44.png">

https://user-images.githubusercontent.com/53038423/200081083-5e760e2d-de02-4258-8856-fa9f661b86ca.mov

**Comment by jasonlyu123** [comment] 2022-11-04 22:38
Duplicate of #1703. The upstream issue seems to do with codeActionOnSave and not just organize import. I'll reopen it if it turns out to separate issue.

**Closed by jasonlyu123** 2022-11-04 22:38 UTC
Labels: bug
