### ISSUE TITLE
Auto format doesn't work with {@render } 

### ISSUE THREAD

**Issue by zoaha** [sveltejs/language-tools#2462] opened 2024-08-11 03:52 UTC
### Describe the bug

seems auto-format doesn't work whenever there's a `{anything here}` declaration

### Reproduction

```svelte
<script>
    let { children } = $props();
</script>

<div class="outer">
    <div class="inner">
        <div class="container">
            {@render children()}
        </div>
        
        
    </div>
</div>
```

^will not auto format, comment out the line `<!-- {@render children()} -->` allows it to work again

### Expected behaviour

expect auto format, in the case of the example, extra lines between the divs should be removed

### System Info

- OS: Windows
- IDE: VSCode

**Comment by zoaha** [comment] 2024-08-11 04:11
in addition, I closed and reopened vs code and now am getting a red squiggly on that line due to :

`'children' is of type 'unknown'`

everything still works, just a ts false error (not sure if should file separate bug)

wasn't there for the last 2 hrs

**Comment by jasonlyu123** [comment] 2024-08-11 04:29
Duplicate of https://github.com/sveltejs/language-tools/issues/2338. Svelte 5 currently require a workspace version of prettier-plugin-svelte and a prettier config file.

https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Bprettier/.prettierrc

As for the second issue, in SveltKit's route files, the snippet `children` props may have auto-typing, but it needs explicit typing in other components. 


```js
<script>
    /**
     * @type {{children: import('svelte').Snippet}}
     */
    const {
        children
    } = $props();
</script>

**Closed by jasonlyu123** 2024-08-11 04:29 UTC
Labels: bug
