### ISSUE TITLE
Multiple <template> tags in the same file emits an error

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/language-tools#810] opened 2021-02-09 10:42 UTC
**Describe the bug**
Attempting to use multiple `<template>` tags in the same file emits an error:
```
</template> attempted to close an element that was not open
svelte(invalid-closing-tag)
```

**To Reproduce**
```svelte
<template>
    <h1>Hello</h1>
</template>
<template>
    <h1>How are you</h1>
</template>
```

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1460917/107351095-c8e9cb00-6afc-11eb-9cbd-f0f9dbc23477.png)
![image](https://user-images.githubusercontent.com/1460917/107351101-cdae7f00-6afc-11eb-9693-78f2aa599d40.png)

**System:**
Visual Studio Code on Windows
```
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
**Plugin/Package:** Svelte for VSCode (`svelte.svelte-vscode`) and confirmed the old extension is not installed.

**Additional context**
#694 is likely related (which is not fully fixed)~~, as is snowpackjs/snowpack/discussions/2595.~~
**EDIT:** latter is related to `svelte-preprocess` insted at sveltejs/svelte-preprocess#310

It's likely that it is greedily parsing the contents from the first opening tag to the last closing tag.

I thought this may have been either a Svelte or HTML limitation at first, but it seems to work with no issues:
- [in the REPL](https://svelte.dev/repl/5d41d03cb51b486e9931a6cd4c8cb605?version=3.32.2)
- in a fresh instance of Svelte with Rollup
- in a fresh instance of Sapper with Rollup

This leads me to believe that multiple `<template>` tags is valid and it is the extension that is incorrect.

**Comment by dummdidumm** [comment] 2021-02-10 08:40
#694 is unrelated, that's only highlighting. The problem is inside `svelte-preprocess`. Therefore I'll close this issue. We will bump the `svelte-preprocess` version once it's fixed other there, then the VS Code error should go away, too.

**Closed by dummdidumm** 2021-02-10 08:40 UTC
Labels: bug
