### ISSUE TITLE
Incredibly slow imports in Svelte & SvelteKit projects.

### ISSUE THREAD

**Issue by takoyaro** [sveltejs/language-tools#1017] opened 2021-05-22 01:50 UTC
**Describe the bug**
The Language server is extremely slow when importing packages in both Svelte 3 projects as well as SvelteKit projects with or without Typescript enabled. Works lightning-fast in non-Svelte/SvelteKit projects.

**To Reproduce**
Importing any component or npm package.

**Expected behavior**
I'm expecting a response in milliseconds.

**Screenshots**
**In a Svelte Project:**

https://user-images.githubusercontent.com/54836677/119210872-c0d0fc80-bae9-11eb-8dbd-74b3fb48c143.mp4

**In a non-Svelte project:**

https://user-images.githubusercontent.com/54836677/119211112-34bfd480-baeb-11eb-9902-f21dbcb185e6.mp4

**System (please complete the following information):**
 - OS: Windows 10 v2004
 - IDE: VSCode 1.56.2
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment] 2021-05-22 02:08
Can't play the video. Can you provide a text description of what exactly is slow? Is it import path completion or auto-import completion?
If it's import-path completion we are working on it. But no ETA on it as there might be multiple causes with it.

**Comment by takoyaro** [comment] 2021-05-22 03:23
Hey @jasonlyu123 , it is indeed the import-path completion.
Since you can't view the videos, I'm attaching the videos as gifs below just for the sake of keeping a record.

Svelte/SvelteKit Projects: 
![sveltelangserver3](https://user-images.githubusercontent.com/54836677/119213194-5b383c80-baf8-11eb-8c9c-a1bd57e79894.gif)

Normal Typescript projects:
![normalts](https://user-images.githubusercontent.com/54836677/119213195-5c696980-baf8-11eb-908b-4a6a33ce0b24.gif)

**Comment by jasonlyu123** [comment] 2021-05-22 03:39
#1015 would likely address part of this if you have some not resolvable import in the codebase. For example, CSS, file import, or svelte import without the file extension.

**Comment by dummdidumm** [comment] 2021-05-22 15:27
I think the problem is that the diagnostics are called too often / not only on the latest state.

**Comment by jasonlyu123** [comment] 2021-05-23 00:32
tssever is likely to use a cancellation token to cancel the request. And the LSP also has a cancellation mechanism. 

So I tried to hook up the cancellation token of the LSP to the cancellation token of the typescript. I found that we need a file-system-based implementation to work. Because typescript language service is synchronized. And node.js is single-threaded. So the cancel message of the LSP won't be able to cancel the synchronous ts code. 

What I mean by file-system-based is that client written a temporary file into the file system. And the sever can check if the file exists to know if the request is canceled.  That means we have to able to identify which file is meant by which specific request.

With vscode-languageserver 7.1 next 4, I at least managed to cancel the request in the asynchronous part of our code. 

I'll create a PR next week for the asynchronous cancellation approach. And we can think about the synchronized cancellation in the future.

**Comment by dummdidumm** [comment] 2021-05-23 07:04
Another thought: I think that the TS language service calls some kind of "synchronize program" method before he does the actual work. If so, we could check how long that synchronisation takes time, and if it's relevant, we pull out that part and do it ourselves, then wait for a tiny bit and then check if there's a new request, and if so return early.

**Comment by dummdidumm** [comment] 2021-05-24 15:37
Could you try again with the latest version? That one hopefully made this one more performant (although there certainly is still room for improvement)

**Comment by takoyaro** [comment] 2021-05-24 20:19
> Could you try again with the latest version? That one hopefully made this one more performant (although there certainly is still room for improvement)

Absolutely life-changing improvement, I have no words. Thanks a lot for your help!!

**Comment by dummdidumm** [comment] 2021-05-25 09:15
Glad to hear that, I'm going to close this issue then (@jasonlyu123 you can still open your asynchronous cancel PR if you want to).

**Closed by dummdidumm** 2021-05-25 09:15 UTC
Labels: Fixed, bug
