### ISSUE TITLE
Importing in a .ts file what was exported in the context="module" script tag of a .svelte file shows a reg squiggly

### ISSUE THREAD

**Issue by AradAral** [sveltejs/language-tools#914] opened 2021-03-24 17:36 UTC
`SomeComp.svelte:`

```svelte
<script lang="ts" context="module">
    export const foo = {
        a: 'b',
        c: 'd',
    }
</script>
```

`someFile.ts:`
```ts
import { foo } from './SomeComp.svelte'; // ERROR
```

A red squiggly would appear under `foo`, saying:
> Module '"*.svelte"' has no exported member 'foo'.

Note that this actually works in practice, so VS Code is wrongly showing a red squiggly.

**Comment by dummdidumm** [comment] 2021-03-24 17:55
Duplicate of #550

**Closed by dummdidumm** 2021-03-24 17:55 UTC
Labels: bug
