### ISSUE TITLE
TS named like "MyButton.svelte.d.ts" breaks "@component" in "MyButton.svelte"

### ISSUE THREAD

**Issue by leoj3n** [sveltejs/language-tools#2310] opened 2024-03-09 08:17 UTC
### Describe the bug

For a fresh library repository with `lib` like so:

![image](https://github.com/sveltejs/language-tools/assets/990216/2155c958-460b-4436-b3d0-0343ae3753ef)

After running `npm run build` the intellisense works fine:

![image](https://github.com/sveltejs/language-tools/assets/990216/9f20ed7c-dd05-45d9-bf70-168c968d4b9a)

However, if we rename `ZZZ-MyButton.svelte.d.ts` to `MyButton.svelte.d.ts` (even with empty contents) and run again `npm run build`, the intellisense will now look like that:

![image](https://github.com/sveltejs/language-tools/assets/990216/205a89e7-581f-49b1-a256-4cc61e6df059)

![image](https://github.com/sveltejs/language-tools/assets/990216/29b912c9-b330-4af9-b4a4-f8d98b6e4872)

If we move away the `MyButton.svelte.d.ts`, the intellisense remains broken until running `npm run build` again.

Can someone explain to me what is going on here? I'm assuming if I name the file something like `./types` and import that it will solve the issue; but should this naming collision really be an issue?

### Reproduction

See above.

### Expected behaviour

Perhaps this file naming isn't supported? Is it bad practice to do this anyways?

### System Info

- OS: macos
- IDE: vscode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Here is the Typescript I am trying to apply to `MyButton.svelte`:

```js
import type { SvelteComponent } from 'svelte';
import type { SvelteHTMLElements } from 'svelte/elements';

type RestProps = SvelteHTMLElements['button'];
interface Props extends RestProps {
	myName: string;
	myCustomProp: boolean;
}

export default class MyButton extends SvelteComponent<Props> {}
```

This doesn't work if I name the `MyButton.svelte.d.ts` something else; so right now I have to choose between `<!-- @component` working or getting the default button attributes to show up.

I am trying to avoid putting Typescript in the component `<script>`.

**Comment by leoj3n** [comment] 2024-03-09 09:03
Ok, interesting... I made a new library starter but selected Typsecript instead of JSDoc + Typescript.

For `MyButtonTS.svelte` I put the following code:

```svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';

	interface $$Props extends HTMLButtonAttributes {
		/** What should my name be? */
		myName: string;
		/** My custom prop! */
		myCustomProp: boolean;
	}

	export let myName: $$Props['myName'] = 'Foo';
	export let myCustomProp: $$Props['myCustomProp'];
</script>

<button {...$$restProps}>
	{myName}
	{#if myCustomProp}isTrue{/if}
	<slot />
</button>

<!--
@component
Here's some documentation for this component...

## Usage
- Simple usage:
```tsx
<MyButton>Foo</MyButton>
```
- Advanced usage:
```tsx
<MyButton myName="Foo" myCustomProp={true}>Bar</MyButton>
```

## Props
@prop export let myCustomProp: boolean;
@prop export let myName: string;
-->
```

I then ran `npm run build` and check `./dist` to see it had generated `MyButtonTS.svelte.d.ts`:

```ts
import { SvelteComponent } from "svelte";
import type { HTMLButtonAttributes } from 'svelte/elements';
declare const __propDef: {
    props: HTMLButtonAttributes & {
        /** What should my name be? */
        myName: string;
        /** My custom prop! */
        myCustomProp: boolean;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {
        default: {};
    };
};
export type MyButtonTsProps = typeof __propDef.props;
export type MyButtonTsEvents = typeof __propDef.events;
export type MyButtonTsSlots = typeof __propDef.slots;
/**
 * Here's some documentation for this component...
 *
 * ## Usage
 * - Simple usage:
 * ```tsx
 * <MyButton>Foo</MyButton>
 * ```
 * - Advanced usage:
 * ```tsx
 * <MyButton myName="Foo" myCustomProp={true}>Bar</MyButton>
 * ```
 *
 * ## Props
 * @prop export let myCustomProp: boolean;
 * @prop export let myName: string;
 */
export default class MyButtonTs extends SvelteComponent<MyButtonTsProps, MyButtonTsEvents, MyButtonTsSlots> {
}
export {};
```

**Comment by leoj3n** [comment] 2024-03-09 09:32
Ah, shoot. Annoyingly I would have to duplicate the `<!-- @component` comment from `MyButton.svelte` into the `MyButton.svelte.d.ts` and try and keep it in sync in order to see the comment while developing as well as after packaging.

Well, I suppose it's not so important to see the comment is working in dev... Not sure if there is a pattern around this or if the VSCode extension could be made to work with this pattern?

**Comment by dummdidumm** [comment] 2024-03-09 09:44
A `.svelte.d.ts` file next to a `.svelte` file with the same name means that the `d.ts` file is used for intellisense, including hover information. So you either have to move/copy the docs into the `d.ts` file or you use typescript inside your Svelte file.
Closing because this is working as intended.

**Closed by dummdidumm** 2024-03-09 09:44 UTC
Labels: bug

**Comment by leoj3n** [comment] 2024-03-09 09:49
@dummdidumm Okay this is what I am seeing as well. Thanks for confirming. Moving the docs into the `d.ts` results in intellisense working as desired.

Does my Typescript file have to be this verbose or is there another way to write it so it's more succinct along the lines of this which was used to generate it:

```
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';

	interface $$Props extends HTMLButtonAttributes {
		/** What should my name be? */
		myName: string;
		/** My custom prop! */
		myCustomProp: boolean;
	}

	export let myName: $$Props['myName'] = 'Foo';
	export let myCustomProp: $$Props['myCustomProp'];
</script>
```

I know it's kind of unrelated to the OP but would be nice to see, if you know.

**Comment by leoj3n** [comment] 2024-03-10 04:20
Followup answer to my own question:

It is correct Svelte and SvelteKit's source code itself was written in JS and JSDoc, and not TypeScript. This allows for hacking on the core library without necessitating a build step. That advice doesn't transfer well to Svelte components, but it still does for "libraries" written in TS. For "component libraries" written in `.svelte`, it's not so really valid advice, because Svelte always has a build step. `@typedef $$props` could work to do this today even though it is not really a benefit for the **component** library... Considering the Svelte 5 `$props` Rune solves prop typing going forwards, I doubt any further effort will be put into Svelte 4's type system, as this typing will be more automatic in the future.
