### ISSUE TITLE
Issue with VSCode completion of filepaths containing $lib

### ISSUE THREAD

**Issue by vlrevolution** [sveltejs/language-tools#1991] opened 2023-04-22 10:59 UTC
### Describe the bug

Using the skeleton project, currently file path completions containing $lib for some reason do not work, this happens (it puts \ instead of $lib):
![2023-04-22 13_38_19-Window](https://user-images.githubusercontent.com/67480746/233779968-cee4aae8-af48-485d-8171-39df24c6a94b.png)
![2023-04-22 13_46_27-Window](https://user-images.githubusercontent.com/67480746/233779972-4c6afdde-26a2-487d-9dc6-512c52bb764a.png)

Anybody else experiencing this?

### Reproduction

Try to auto complete filepaths when doing import containing $lib

### Expected behaviour

Should put $lib into filepath

### System Info

  System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 22.08 GB / 24.99 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Chromium: 106.0.5249.119
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.15.7
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.2.0 => 4.3.1

### Which package is the issue about?

Svelte for VS Code extension, svelte-language-server, svelte2tsx

**Comment by jasonlyu123** [comment] 2023-04-22 11:56
Duplicate of #1854. It's a upstream issue that will be fixed in Typescript 5.1

**Closed by jasonlyu123** 2023-04-22 11:56 UTC
Labels: bug
