### ISSUE TITLE
@apply used in a class shows syntax error on second included class

### ISSUE THREAD

**Issue by b-d-m-p** [sveltejs/language-tools#756] opened 2021-01-11 14:03 UTC
**Describe the bug**

@apply used in a class shows syntax error on second included class. 

**To Reproduce**
Add the above code in a style tag in a .svelte 

For example a code snippet that is treated in a way you don't expect.

```
.selected {
    @apply bg-purple-200 text-purple-600;
    font-weight: 700;
  }
```

**Expected behavior**
No redline will display below the second class.

**Screenshots**
![image](https://user-images.githubusercontent.com/1300390/104191391-cdb95180-5460-11eb-9b69-c0856ba5b49c.png)

**System (please complete the following information):**
 - OS: MacOS
 - IDE: vScode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment] 2021-01-11 14:10
Please provide the full code snippet. If there's no `lang="postcss"` or similar then this error is expected, because normal css can only handle one value after `@apply`.

**Comment by dummdidumm** [comment] 2021-02-10 09:45
Closing due to lack of reproduction.

**Closed by dummdidumm** 2021-02-10 09:45 UTC
Labels: bug
