### ISSUE TITLE
`$$Props` should error if component doesn't implement interface

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#1794] opened 2022-12-21 09:51 UTC
### Describe the bug

When declaring a `$$Props` interface but not declaring all props that it requires should be an error

### Reproduction

```
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";

  interface $$Props extends HTMLButtonAttributes { // should error but doesn't
    foo: boolean; // is required, should be an error
  }
</script>

<!-- ... -->
```

### Expected behaviour

An error should be shown if no `$$props` is used and the `export let X` is not present if it's required in `$$Props`.

### System Info

Windows, VSCode

### Which package is the issue about?

svelte2tsx

**Comment by jorgebv** [comment] 2022-12-23 17:10
I am not sure if it is connected exactly to the PR that was recently merged or if it is something else, but the latest version of svelte-check is now complaining about 3rd party libraries where it didn't before. One of these is carbon-components-svelte which "forwards" any extra props to one of its child elements, kind of like described here: https://sveltesociety.dev/recipes/component-recipes/passing-attributes-to-component-dom-element

So would we say that the typescript type of a Svelte component should be the svelte props + the HTML props of whatever it is forwarding to?

If so I guess this would be a bug in the carbon-components-svelte types. I'm just asking here to try to understand the expected behavior.

**Comment by dummdidumm** [comment] 2022-12-23 20:42
Could you give an example where this fails (code snippet with using a carbon component is enough)?

**Comment by jorgebv** [comment] 2022-12-23 23:49
```
<script lang="ts">
  import { Button } from 'carbon-components-svelte';
</script>

<Button on:click={() => alert('do thing')} data-cy={'forwarded-to-html-button'}>Button</Button>
```

produces
```
Error: Type '{ "data-cy": string; }' is not assignable to type 'ButtonProps'.
  Object literal may only specify known properties, and '"data-cy"' does not exist in type 'ButtonProps'. (ts)
 ```
 
The error is legitimate since indeed the types for the carbon Button component do not include data-cy. But the Button component does forward it to the HTML button through `...$$restProps`, and our cypress tests use it for targeting purposes.

I'm not against svelte-check being more strict here, I just wanted to double check that it was an intentional change.

**Comment by dummdidumm** [comment] 2022-12-24 08:34
Ah I see, yeah anything with `data-` prefix  should be allowed. This worked for the old transformation because any props with a dash in them where excempted from type checking (which is also wrong). You can enhance the typings yourself in the meantime: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error

**Closed** 2023-01-09 14:42 UTC
Labels: bug, Fixed
