### ISSUE TITLE
⚠️ svelte-preprocess 5.1.4 🤔

### ISSUE THREAD

**Issue by Valexr** [sveltejs/language-tools#2505] opened 2024-09-18 10:02 UTC
`3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1`
![Screenshot 2024-09-18 at 12 02 06](https://github.com/user-attachments/assets/e518c497-a1ff-46b4-814c-79e5beb967f1)

**Comment by jasonlyu123** [comment] 2024-09-18 10:07
Duplicate of #2391

**Closed by jasonlyu123** 2024-09-18 10:07 UTC

**Comment by jasonlyu123** [comment] 2024-09-18 10:36
In case if it's not obvious from the linked issue. You'll need to update to svelte-check v4. The removal is a breaking change.
