### ISSUE TITLE
Fallback to / prioritize workplace settings

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/language-tools#331] opened 2020-07-22 19:45 UTC
I use workplace settings instead of global settings for all my projects. This to make sure any developer can just clone my repository, install all `recommended plugins` and get started asap instead of wasting time setting up. 

I just spend 20 minutes trying to get the language server working. It didn't start because it couldn't find my node runtime. It was ignoring the workplace `svelte.language-server.runtime` configuration because the `global user settings` already set to option to the default `usr/something/something` runtime location.

Idk if this expected behavior, my fault or whatever really. It happened and now I'm making this post.

**Describe the solution you'd like**
If the language server fails to (re)start, check for any workplace settings and try those settings instead. Or prioritize the workplace settings over the users global settings.

**Describe alternatives you've considered**
None.

**Additional context**
Maybe I configured it myself and/or don't understand the inner workings of vscode. I'm not familiar with any of the current conventions. If this is something people agree with, well... lets go! If not, consider this request not made I guess.

**Comment by jasonlyu123** [comment] 2020-07-23 00:50
We are using the API of vscode to get the configuration. If my understanding is correct, vscode merge the config for us. So I think workspace config is indeed prioritized. Maybe it's another problem that it can't find the runtime. Did you solve it? Mind if you provide the config that doesn't work and the one that works?

**Comment by UltraCakeBakery** [comment] 2020-07-23 07:48
I did solve it by changing both my `user settings` and `workplace settings`. I just copied the correct path to my `node runtime` from my `workplace settings` to my `user settings`. Both through the UI of vscode, not the `settings.json` files. So the final string should've been formatted exactly the same. After setting the correct path in my `user settings` it worked fine. I did experience #332 but that is entirely unrelated. 

My best guess is that in this case the extension or vscode prioritizes global settings over workplace settings. Which I personally find confusing / dumb if that is the case.

To replicate, just put a faulty path in your `user settings` to the node runtime and put the proper one in your `workplace settings`. That's all I know I did in the end. The faulty configuration is gone now.

**Comment by jasonlyu123** [comment] 2020-07-23 08:17
I try that but I can't reproduce it.
Also, I found that the setting UI would add extra escapes to the windows path separator. If you type 
`C:\\Program Files\\nodejs\\node.exe` it would save to `C:\\\\Program Files\\\\nodejs\\\\node.exe`.

**Comment by dummdidumm** [comment] 2020-07-27 16:39
I cannot reproduce this either:

- I set user settings runtime to `bla`
- I set workspace settings runtime to `blubb`

--> it correctly uses runtime `blubb`

What will happen though if you do not set anything in your workspace settings, it will use the user settings. So if

- I set user settings runtime to `bla`
- I leave workspace settings runtime empty

--> It will use `bla` as runtime

Is this what happened to you?

**Comment by dummdidumm** [comment] 2020-08-12 08:32
Closing as it cannot be reproduced / is the correct behavior.

**Closed by dummdidumm** 2020-08-12 08:32 UTC
