### ISSUE TITLE
Ability to configure the typescript version used by svelte-check

### ISSUE THREAD

**Issue by TimoWilhelm** [sveltejs/language-tools#2082] opened 2023-07-04 17:27 UTC
### Description

Is there any way to override the typescript version used by svelte-check? I'm using the TS 5.2 beta with the `using` feature and svelte-check complains about the new globals.

![image](https://github.com/sveltejs/language-tools/assets/22396907/78816dd8-9035-4244-904b-e73984aac818)

### Proposed solution

Some option to configure the tsserver used by the svelte check command. For example in VSCode you can configure the tsdk with the `typescript.tsdk` key in the `settings.json`.

### Additional Information, eg. Screenshots

It seems like the language-tools package has the typescript dependency version set to "*" https://github.com/sveltejs/language-tools/blob/efd11ef87d5fe1405cd627ce3c0562a55ad11e33/packages/language-server/package.json#L61

 but the svelte-check package has it set to a specific version (currently "^5.0.3")

**Comment by jasonlyu123** [comment] 2023-07-05 01:46
`^5.0.3` is not a specific version. It's any minor later than `5.0.3`. The problem is 5.2 beta is a prerelease. npm won't install it unless you specify it. If you're using pnpm, you may need to pass some flags or manually update the lock file to let it install 5.2 for svelte-check. I don't think we want `|| beta` in the version specifier. That would seem like it's an officially supported version. But we won't actively check if it's compatible with any latest typescript beta.

**Comment by TimoWilhelm** [comment] 2023-07-05 06:43
Thanks for the reply! I understand I could use the `override` section in my `package.json` to manually override the typescript dependency.

My idea was to make the typescript version configurable via an argument to svelte-check. Something like

`svelte-check --typescript-tsdk="./node_modules/typescript"` 

However, if the plan is to only ever support the current stable typescript version, thats understandable too! In that case, please feel free to close this isse.

**Comment by dummdidumm** [comment] 2023-07-05 07:45
You can configure it yourself so to speak by using the tools npm/pnpm etc give you to override certain package versions. We will not add a parameter for this. In the next major version of `svelte-check` we'll also likely make TypeScript a peer dependency which makes overriding it a bit easier. Therefore closing.

**Closed by dummdidumm** 2023-07-05 07:45 UTC
