### ISSUE TITLE
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828).

### ISSUE THREAD

**Issue by jjelier** [sveltejs/language-tools#2292] opened 2024-02-20 09:32 UTC
Type: <b>Bug</b>

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/jos/Dev/test-app/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/jos/Dev/test-app/node_modules/rollup/dist/native.js:96:76)
    ... 2 lines matching cause stack trace ...
    at Module.load (node:internal/modules/cjs/loader:1173:32)
    at node:internal/modules/cjs/loader:1014:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/jos/Dev/test-app/node_modules/rollup/dist/native.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1131:15)
      at node:internal/modules/cjs/loader:976:27
      at Function._load (node:electron/js2c/asar_bundle:2:13327)
      at Module.require (node:internal/modules/cjs/loader:1197:19)
      at require (node:internal/modules/cjs/helpers:121:18)
      at requireWithFriendlyError (/Users/jos/Dev/test-app/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/Users/jos/Dev/test-app/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1318:14)
      at Object..js (node:internal/modules/cjs/loader:1373:10)
      at Module.load (node:internal/modules/cjs/loader:1173:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/Users/jos/Dev/test-app/node_modules/rollup/dist/native.js' ]
  }
}

Extension version: 108.2.2
VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 245bc342-091c-4e35-97a9-095aec5f2dba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
7j2b6412:30967274
ccp2r6:30958158

```

</details>

**Comment by jasonlyu123** [comment] 2024-02-20 09:47
Duplicate of #2278.

**Closed by jasonlyu123** 2024-02-20 09:47 UTC

**Comment by dnkTin** [comment] 2026-04-12 03:38
rm -rf node_modules package-lock.json && npm i
Done
