### ISSUE TITLE
VSCode extension slowing down IntelliSense

### ISSUE THREAD

**Issue by Carter121** [sveltejs/language-tools#2464] opened 2024-08-13 07:17 UTC
### Describe the bug

The VS Code IntelliSense is very slow when the Svelte extension is enabled.

### Reproduction

Press Ctrl + Space.

### Expected behaviour

The IntelliSense loads quickly.

### System Info

- OS: Linux
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

I disabled all extensions and enabled them individually until I found that Svelte was causing the slow IntelliSense.

**Comment by jasonlyu123** [comment] 2024-08-13 07:22
Please check out some existing performance discussions https://github.com/sveltejs/language-tools/labels/perf. If these don't help, please provide a reproduction repository.

**Comment by Carter121** [comment] 2024-08-13 07:29
It is very similar to #2329 and I did some more testing and found that the issue resolves when I disable the "Enable-TS-plugin" setting.

**Comment by jasonlyu123** [comment] 2024-08-13 07:33
Does the performance problem happen in a SvelteKit route file?

**Comment by hyunbinseo** [comment] 2024-09-18 17:46
Disabling `svelte.enable-ts-plugin` also fixed the IntelliSense performance issue for me.

It only happens in the Windows environment, regardless[^1] of the file extension.

[^1]: `+page.server.ts` files are affected as well.

It does not occur in macOS with an identical setup and project.

The following issue also had a similar conclusion: no performance issue on M1 Pro Mac.

- https://github.com/sveltejs/language-tools/issues/2329#issuecomment-1008864430

Would love to share some logs, but `svelte.trace.server` does not seem to work?

**Comment by hyunbinseo** [comment] 2024-09-19 14:24
This is the performance issue I am experiencing on my Windows laptop:

https://github.com/user-attachments/assets/3dc46e1d-c70f-410c-8120-ad5b52a2aced

Simply disabling the Svelte extension greatly improves the `+page.server.ts` IntelliSense perf.

This behavior is reproducible in an Windows on Arm device as well. (Surface Pro 9 5G)

**Comment by jasonlyu123** [comment] 2024-09-19 14:43
Can you provide the dependencies and devDependencies in your package.json and tsconfig.json? Weird that it also seems to happen in a svelte file as well. I am wondering if it has something to do with https://github.com/sveltejs/language-tools/issues/2244#issuecomment-1876202548 but because you only import the package in a svelte file. 

Also, can you the svelte file again with the svelte.language-server.debug config and turn off `svelte.trace.server`?

**Comment by jasonlyu123** [comment] 2024-09-19 14:51
> Am I supposed to re-record the +page.svelte file with this option?

You can also copy the log. There should be some with the [ts] prefix.

**Comment by hyunbinseo** [comment] 2024-09-19 15:00
This is the debug log from typing `new TextEncoder().encode()` in a `+page.svelte` file:

```
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Executing next invocation of "getSemanticTokens" with low priority
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.010999999940395355
[ts] getCompletionData: Is inside comment: 0.0276999999769032
[ts] getCompletionData: Get previous token: 0.021200000075623393
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.3329999998677522
[ts] AutoImportProviderProject: found 397 root files in 4 dependencies in 64.3723000001628 ms
[ts] getExportInfoMap: cache miss or empty; calculating new results
[ts] forEachExternalModuleToImportFrom autoImportProvider: 28.235099999932572
[ts] getExportInfoMap: done in 2651.4216000000015 ms
[ts] collectAutoImports: resolved 39 module specifiers, plus 122 ambient and 311 from cache
[ts] collectAutoImports: response is complete
[ts] collectAutoImports: 264.14669999992475
[ts] getCompletionData: Semantic work: 2925.1110999998637
[ts] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 23.10439999983646
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.006399999838322401
[ts] getCompletionData: Is inside comment: 0.01280000014230609
[ts] getCompletionData: Get previous token: 0.01860000006854534
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.013299999991431832
[ts] getExportInfoMap: cache hit
[ts] collectAutoImports: resolved 94 module specifiers, plus 102 ambient and 461 from cache
[ts] collectAutoImports: response is complete
[ts] collectAutoImports: 586.0183999999426
[ts] getCompletionData: Semantic work: 589.2409000000916
[ts] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 14.66469999984838
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.013700000010430813
[ts] getCompletionData: Is inside comment: 0.024499999824911356
[ts] getCompletionData: Get previous token: 0.0205999999307096
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.010000000009313226
[ts] getCompletionData: Semantic work: 2.0726999999023974
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.13040000014007092
[ts] getCompletionData: Is inside comment: 0.013999999966472387
[ts] getCompletionData: Get previous token: 0.10990000003948808
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.019099999917671084
[ts] getCompletionData: Semantic work: 3.827999999979511
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.02279999991878867
[ts] getCompletionData: Is inside comment: 0.012000000104308128
[ts] getCompletionData: Get previous token: 0.09599999990314245
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.020500000100582838
[ts] getCompletionData: Semantic work: 3.1777999999467283
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.010400000028312206
[ts] getCompletionData: Is inside comment: 0.04689999995753169
[ts] getCompletionData: Get previous token: 0.026099999900907278
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.00430000014603138
[ts] getCompletionData: Semantic work: 2.035300000105053
[ts] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 0.3595000000204891
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
[ts] getCompletionData: Get current token: 0.020800000056624413
[ts] getCompletionData: Is inside comment: 0.12140000006183982
[ts] getCompletionData: Get previous token: 0.021900000050663948
[ts] getCompletionsAtPosition: isCompletionListBlocker: 0.004799999995157123
[ts] getCompletionData: Semantic work: 0.4514000001363456
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
Using Prettier v3.3.3 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\prettier@3.3.3\node_modules\prettier
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
Using Svelte v5.0.0-next.243 from C:\Users\hyunb\Development\sdtvx\node_modules\.pnpm\svelte@5.0.0-next.243\node_modules\svelte\compiler
```

**Comment by jasonlyu123** [comment] 2024-09-19 15:17
Thanks. It's indeed something to auto-import. I'll take a deeper look later.

**Comment by jasonlyu123** [comment] 2024-09-23 09:15
The problem in svelte files only appears the first time completion is triggered. TS Server doesn't have it because some auto-import is calculated a bit earlier. And it only affects auto-import that has never been imported before so I'll probably not change this part. 

The problem in SvelteKit routes files should be what I think it is. Feel free to comment and provide more info if the problem doesn't improve after we release a fix for this.

**Closed** 2024-09-26 12:24 UTC
Labels: bug, Fixed, perf
