### ISSUE TITLE
Property completions broken if editing inside an expression

### ISSUE THREAD

**Issue by EdwardBlair** [sveltejs/language-tools#2622] opened 2024-12-08 20:18 UTC
### Describe the bug

Might be expected behaviour, intellisense breaks if editing on the lhs of an expression - I haven't tested any further cases.

### Reproduction

Create svelte demo app go to a .svelte file which uses ActionData (e.g. `src/routes/demo/lucia/login/+page.svelte`)
Edit, e.g. `{form?.message ?? ''}` 

1. Delete `.message
2.  type `.`,
3. intellisense is wrong
4. press `esc`, press `control+space`
5. intellisense is still wrong.

Incorrect:
<img width="365" alt="image" src="https://github.com/user-attachments/assets/22293692-143d-4d25-a66d-cec9043a0b50">

One way to make it work is delete the rest of the expression.

<img width="487" alt="image" src="https://github.com/user-attachments/assets/8e492524-1c97-46e3-91a7-6fb47288cb5f">

### Expected behaviour

Shows correct completions 

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment] 2024-12-09 00:45
Duplicate of #1302. This is a limitation of the virtual code generation behind the scene. See https://github.com/sveltejs/language-tools/issues/1302#issuecomment-1002358234 for the explanation.

**Closed by jasonlyu123** 2024-12-09 00:45 UTC
Labels: bug
