### ISSUE TITLE
Binding element 'request' implicitly has an 'any' type.ts(7031)

### ISSUE THREAD

**Issue by GabrielGorta** [sveltejs/language-tools#2161] opened 2023-09-19 14:28 UTC
### Describe the bug

```
Binding element 'request' implicitly has an 'any' type.ts(7031)
Binding element 'params' implicitly has an 'any' type.ts(7031)
```

These erros are randomly thrown in `+page.server.js` files, if you define form actions.

```js
export const actions = {
    default: async ({ request, params }) => {
        return await getData({ request, params });
    }
}
```

file in `./.svelte-kit/types/src/routes/some_path/$types.d.ts` seems to be correctly populated.

### Reproduction

1. create project (JS with type-checking + ESLint + Prettier + both test things)
2. run dev server
3. create `+page.server.js` and `+page.svelte` files in `./src/routes/some_path/` dir.
4. write action in server file, and simple form in client file.
5. randomly it shows error, sometimes restarting IDE or `svelte:check` helps.

### Expected behaviour

No Error, code is correct, types are correct.

### System Info

- OS: Windows 11 [22H2] (build: 22621.2283)
- IDE: VSCode 1.82.2 (system setup)
- Node: 18.15.0

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/112625511/a7a9cc58-9332-4cb9-b882-0c86ea1083a4)
![image](https://github.com/sveltejs/language-tools/assets/112625511/d675b5ef-5e04-46f2-bc1d-1f43512581a5)

Also when I hover over "request" parameter, it shows tooltip `const formData: any`, like if it takes line below.
![image](https://github.com/sveltejs/language-tools/assets/112625511/4e435760-3456-46f5-b550-f0231941e475)

At least error underline highligh is at correct position when disabled extension, with enabled, it really shows nonsense.

**Comment by jasonlyu123** [comment] 2023-09-20 00:46
Duplicate of #2053. It's fixed in 107.11.0.

**Closed by jasonlyu123** 2023-09-20 00:46 UTC
Labels: bug
