### ISSUE TITLE
useNewTransformation Feedback Thread

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#1352] opened 2022-01-29 22:54 UTC
We introduced a new transformation which powers the Svelte intellisense under the hood. The goal is to get rid of a tsx-style transformation and simplify transformations along the way.

Advantages for users:

- no messing with projects who use JSX for some other reason and then have conflicting JSX definitions (#1256, #1149)
- better type inference in some cases, for example around svelte:component

Internal advantages:

- TS control flow easier to keep flowing
- overall easier transformations of Svelte specific syntax like await, each etc.

You can try out the new transformation using 
- "Svelte for VS Code" version 105.11.1 and setting `svelte.plugin.svelte.useNewTransformation` to `true`
- `svelte-check` version 2.4.0 with the `--use-new-transformation` flag.

Please provide feedback in here about any improvements or regressions.

**Comment by dummdidumm** [comment] 2022-01-30 09:52
Note for myself: We need to make the "no type definition found" or "type definition is wrong" error which we enhance for the old transformation [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts#L269) better for the new transformation and possibly also wrap the `new Component` call in a function which falls back to some defaults - don't know yet.

**Comment by TomTomB** [comment] 2022-01-30 18:01
Hi, so far I've found 3 issues when using the new transformation. 

**Data attributes**
Using a data attribute (e.g. data-popper-arrow for popper.js) results in the following error 
```
Argument of type '{ class: string; "data-popper-arrow": boolean; }' is not assignable to parameter of type 'HTMLProps<HTMLDivElement>'.
  Object literal may only specify known properties, and '"data-popper-arrow"' does not exist in type 'HTMLProps<HTMLDivElement>'
```

**Some attributes got renamed**
This is a kind of breaking one. Before you could use something like `xlink:href="someId"` inside a svg. now it needs to be `xlinkHref="someId"`. The same applys for `xmlns:xlink` and  `tabIndex` (now `tabindex`).

**Typing custom events from actions is a total loss**
Before, there was a workaround to type custom events dispatched via `use:someAction`. 


```typescript
// custom-events.d.ts
declare namespace svelte.JSX {
 interface HTMLAttributes<T> {
    'onclick-outside'?: (
      event: CustomEvent & {
        target: EventTarget & T;
      },
    ) => void;
  }
}
```

```svelte
svelte component

<script>
  import { clickOutside } from 'somewhere';

  const onClickOutside = () => {
    console.log('foo')
  };
</script>

<div
  on:click-outside={onClickOutside}
/>
```

This now results in errors like 
```
 The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
```
```
',' expected 
```
```
 Argument expression expected
```
```
Declaration or statement expected
```
```
Cannot find name 'outside'
```

**Comment by dummdidumm** [comment] 2022-01-31 14:47
Thank you @TomTomB for the valuable feedback! I adressed all issues in the latest version.

**Comment by sw-yx** [comment] 2022-02-03 08:38
@dummdidumm found this while using the new setting: 
![image](https://user-images.githubusercontent.com/6764957/152308391-c34bf0d0-8c2a-4841-95d2-54436a9643ac.png)

it appears that it is not parsing multiline classnames properly? i can replicate whenever i just add an arbitrary newline in the middle of any classname.

**Comment by ignatiusmb** [comment] 2022-02-03 10:37
`<Nested.Component />` usage error seems to appear again

**Comment by dummdidumm** [comment] 2022-02-03 16:13
Thanks @sw-yx and @ignatiusmb ! Both issues are hopefully fixed with the latest version.

**Comment by ignatiusmb** [comment] 2022-02-04 08:02
Lightning fast as always @dummdidumm! Can confirm it's working again now. No more regressions detected in all the apps that uses the new transformation.

**Comment by ignatiusmb** [comment] 2022-02-04 08:23
Oops, might've spoken too early. `svelte-check` indeed doesn't seem to report any more errors, but autocompletion are now a bit overzealous and treats everything as JavaScript, even outside `<script>` and `{ ... }`, where emmet is supposed to take control.

To reproduce, try triggering autocompletion, or start writing HTML in markup. It works in an empty `.svelte` as well.

**Comment by jasonlyu123** [comment] 2022-02-07 06:03
Find one problem with Components having events in the typedef. Created #1375 for it.

**Comment by dummdidumm** [comment] 2022-02-07 15:02
Thanks @ignatiusmb and @jasonlyu123 , both issues are hopefully fixed in the latest version.

**Comment by ignatiusmb** [comment] 2022-02-07 16:06
Emmet is now working again! But seeing another regression with `svelte-kit package` generated components. Not sure if the library needs to re-generate the definitions again with the new version or it is actually incompatible, but reproduction below.

To reproduce, copy the `.d.ts` below that's been generated from an empty `.svelte` file and name it `Missing.svelte.d.ts` (don't even need to have the `.svelte` file itself), import it in another file (`import Missing from '$lib/Missing.svelte';`) and use it as usual.

```ts
/** @typedef {typeof __propDef.props}  MissingProps */
/** @typedef {typeof __propDef.events}  MissingEvents */
/** @typedef {typeof __propDef.slots}  MissingSlots */
export default class Missing extends SvelteComponentTyped<{}, {
    [evt: string]: CustomEvent<any>;
}, {
    default: {};
}> {
}
export type MissingProps = typeof __propDef.props;
export type MissingEvents = typeof __propDef.events;
export type MissingSlots = typeof __propDef.slots;
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {};
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {
        default: {};
    };
};
export {};
```

Error should show something along these lines, which is most likely from changes in #1375 

![image](https://user-images.githubusercontent.com/8156777/152825159-56afe2d4-fd5b-4d6e-9de4-576a8a219602.png)

**Comment by rgossiaux** [comment] 2022-02-09 02:46
Just tried this on my own codebase and it caught an error that the old transformation does not catch (incorrectly using an attribute `html-for=` instead of `for=` due to bad conversion from React's `htmlFor`), so that was cool.

However I did get a new error when using `<svelte:component>` that I don't understand. This code throws an error:

```svelte
<script lang="ts">
  import type { SvelteComponent } from "svelte";

  export let as: SvelteComponent;
</script>

<svelte:component this={as} />
```

as well as if you change the type from `SvelteComponent` to `SvelteComponentTyped`. What's the correct type here? I think the error message for this is also a bit confusing:
```
Error: Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}

Underlying error:
Argument of type 'SvelteComponentTyped<any, any, any>' is not assignable to parameter of type 'new (args: { target: any; props?: any; }) => Svelte2TsxComponent<any, any, any>'.
  Type 'SvelteComponentTyped<any, any, any>' provides no match for the signature 'new (args: { target: any; props?: any; }): Svelte2TsxComponent<any, any, any>'. (ts)

<svelte:component this={as} />
```

The text at the top of the error is probably helpful for some other case, but in this case it's just confusing.

**Comment by kevin-legion** [comment] 2022-02-10 18:23
I got only a couple of issues (one has been mentioned by @rgossiaux already):

1. Dynamic components + `svelte:component` don't work as expected:

```ts
class MyComp extends SvelteComponentTyped<{
  name: string;
}> {}

// ...

const dynamicComp = ...;

// ...

<svelte:component this={dynamicComp} name="hello" />
```

Will fail with the following error:

```
Error: Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}

Underlying error:
Argument of type 'MyComp' is not assignable to parameter of type 'new (args: { target: any; props?: any; }) => Svelte2TsxComponent<any, any, any>'.
  Type 'SvelteComponentTyped<{ name: string; }, any, any>' provides no match for the signature 'new (args: { target: any; props?: any; }): Svelte2TsxComponent<any, any, any>'. (ts)
      <svelte:component this={dynamicComp} name="hello" />
```

2. `index` in `#each` blocks always fails to compile:

```svelte
{#each things as thing, index (index)}
  // ...
{/each}
```

Will fail as follows:

```
Error: Variable 'index' is used before being assigned. (ts)
{#each things as thing, index (index)}
  // ...
```


Other than that I'm really excited for the new transformation system, it catches much more type errors and is more reliable, amazing job 😃

**Comment by dummdidumm** [comment] 2022-02-16 10:23
Thanks @ignatiusmb, @rgossiaux and @kevin-legion for the feedback!
- The "is this a valid component" check should be better now, fixing the case @ignatiusmb mentioned and also hopefully makes it more clear that the error reported by @rgossiaux and @kevin-legion are actually usage errors - you need to pass a component constructor type, not the instance type (`component: new ({target: any, props: any}) => YourComponent` or `component: typeof YourComponent` instead of `component: YourComponent`)
- The `#each` but should be fixed

**Comment by Jojoshua** [comment] 2022-04-12 21:47
Just wanted to note that this feature has been working great. It's a game changer and gives our team comfort and enhanced productivity.

**Comment by benbender** [comment] 2022-05-02 08:43
given a component with a typing like: 

```ts
  interface $$Props
    extends Partial<HTMLButtonElement> {
    size?: "s" | "m" | "l" | undefined;
  }
```

*without* the new tranformer, AutoCompletion in VSCode correctly only suggests `"s" | "m" | "l"` for the size-prop.

If I enable the new transformer, nearly every possible attribute is suggested. See:
<img width="591" alt="Bildschirmfoto 2022-05-02 um 10 37 42" src="https://user-images.githubusercontent.com/462455/166207938-3297bc6d-9475-4d96-b491-a5726545b57d.png">

**Comment by dummdidumm** [comment] 2022-05-14 16:17
Thanks for reporting @benbender, fixed in the latest version.

**Comment by ZerdoX-x** [comment] 2022-08-12 08:54
Sharing feedback from the production project that uses sveltekit _(not the biggest tho, ~50k lines of code, 40k of them is svelte files)_.

Before using new transformation we got `41 errors, 10 warnings, and 47 hints`, after enabling new transformation svelte-check found `60 errors, 10 warnings, and 43 hints`.

New errors we got and how we fixed them:
1. mask-type:
    ```
    Error: Argument of type '{ ... "mask-type": string; ... }' is not assignable to parameter of type 'SVGProps<SVGMaskElement>'.
      Object literal may only specify known properties, and '"mask-type"' does not exist in type 'SVGProps<SVGMaskElement>'. (js)
    ```
    Solution: replace `mask-type="alpha"` with `style="mask-type: alpha"`
    Maybe related: https://github.com/gregberge/svgr/issues/336
    Will also try to contact with figma team about this "feature" as all svgs where imported from figma. i guess this property exists only in css scope, not as html attribute.
2. lazy-loading for images
    ```
    Error: Argument of type '{ ... lazy: string; ... }' is not assignable to parameter of type 'HTMLProps<HTMLImageElement>'.
      Object literal may only specify known properties, and '"lazy"' does not exist in type 'HTMLProps<HTMLImageElement>'. (ts)
    ```
    Not sure how we got it in our codebase 😃 Thats good work for svelte-check.
    Replaced with `lazy="true"` with `loading="lazy"`

After resolving new errors I've listed above, I get same errors count as before upgrading transformation. This upgrade also removed some unwanted falsy hints for me (#1580). Thank you for levelling up svelte-check!

**Comment by dummdidumm** [comment] 2022-08-12 09:12
Thank you for the feedback! The `mask-type` is an interesting one, and after reading various threads on it I'm still a little confused whether or not this is (also) a valid attribute in the browsers (not in the final spec but still).

In general, the new transformation may give errors for attributes with hyphens in their name. Previously, we used TSX under the hood for the intellisense, which allows unknown hyphened attributes. The new transformation uses TS under the hood, so it's more strict in that regard.

**Comment by ZerdoX-x** [comment] 2022-08-30 07:14
I also found that we get `Error: Argument of type 'string' is not assignable to parameter of type 'never'. (ts)` error that @rgossiaux reported

**Comment by dummdidumm** [comment] 2022-08-30 12:35
Could you provide a reproducible in a new issue? Can't reproduce this.

**Comment by ZerdoX-x** [comment] 2022-08-30 13:26
<img width="870" alt="image" src="https://user-images.githubusercontent.com/49815452/187448243-007fe21f-8a5f-4cbb-938c-df82c916cd1a.png">
for me it appears "randomly". it even appears in empty file with span only

it's an vscode error only. it doesn't appear in check tool

**Comment by dummdidumm** [comment] 2022-08-30 14:03
This sounds like a bug which is fixed in the latest version which was released a few hours ago. Try updating the extension and then reload VS Code.

**Comment by ZerdoX-x** [comment] 2022-08-31 07:38
Hmm.. maybe yeah, it is fixed now. I will let you know if it will come back

**Comment by ZerdoX-x** [comment] 2022-09-09 11:57
So I've made an issue for some another issue appeared for me after upgrading to new transformation.
I've made it external because I thought it existed without using new transformation.

**Comment by jrmoynihan** [comment] 2022-09-14 00:48
### Destructured object props are incorrectly identified as constants in {#each} blocks
<img width="547" alt="CleanShot 2022-09-13 at 20 27 00@2x" src="https://user-images.githubusercontent.com/65916939/190032305-2e4822d7-79af-4db0-9e01-6790af8f4c15.png">
<img width="550" alt="CleanShot 2022-09-13 at 20 27 21@2x" src="https://user-images.githubusercontent.com/65916939/190032322-494e81dc-ff97-49b6-9e70-86741acf0086.png">

Seems to be correctly identified when I disable the new transformation setting:
<img width="332" alt="CleanShot 2022-09-13 at 20 47 23@2x" src="https://user-images.githubusercontent.com/65916939/190034176-47496007-7eeb-4159-8998-86e80d467d4f.png">

**Comment by samuelstroschein** [comment] 2022-09-15 17:46
With "svelte.plugin.svelte.useNewTransformation" set to `false`, defining custom web components works as follows: 

```ts
// app.d.ts
declare namespace svelte.JSX {
	interface IntrinsicElements {
		"example-element": {
			name: number;
		};
	}
}
```

<img width="682" alt="image" src="https://user-images.githubusercontent.com/35429197/190474136-e3aaafb6-6904-4d4a-9a62-9b8f32d65b13.png">

**Problem**

Setting useNewTransformations to `true` results in no type errors as if the namespace declaration is ignored. 

**Question**

Is this a bug or am I supposed to declare custom web components in a different manner?

**Comment by dummdidumm** [comment] 2022-09-15 18:02
You should be able to do the following:

```
// app.d.ts
declare namespace svelteHTML {
  interface IntrinsicElements: { .. }
}
```

That said, we probably should add backwards-compatibility for the typings. They exist for others, but not this case.

**Comment by aradalvand** [comment] 2022-09-15 21:03
Hi, I have this in my `app.d.ts`:
```ts
type Stringable = string | { toString(): string };

declare namespace svelte.JSX {
  interface HTMLAttributes {
    class?: Stringable;
  }
  interface SVGAttributes {
    class?: Stringable;
  }
}
```
This is so that the "class" attribute accepts any object with has a `toString` method — I have a custom class builder that is a fluent API, and has a `toString()` method that actually produces the class list, I don't want to have to call `toString()` all the time because that happens automatically when the object is being set as the value of the attribute, so I did this to get rid of the type errors; and it used to work prior to this change. Now it isn't, and I'm getting type errors:

![image](https://user-images.githubusercontent.com/26527405/190508225-b669be75-9640-4467-b7ad-7d60830ba09a.png)

What should I do?

**Comment by samuelstroschein** [comment] 2022-09-15 21:40
@aradalvand You seem to have the same problem I had. See https://github.com/sveltejs/language-tools/issues/1352#issuecomment-1248429583

Try changing `declare namespace svelte.JSX` to `declare namespace svelteHTML`.

**Comment by aradalvand** [comment] 2022-09-15 21:46
@samuelstroschein I did that and it makes no difference sadly.

**Comment by aradalvand** [comment] 2022-09-16 09:52
@dummdidumm Should I create a separate issue for this? Thanks.

**Comment by dummdidumm** [comment] 2022-09-16 19:18
Backwards compatibility should be better now, both these case should work without errors now, but you can also switch to the new `svelteHTML` namespace and it should work the same.

**Comment by amartens181** [comment] 2022-09-22 20:46
> Backwards compatibility should be better now, both these case should work without errors now, but you can also switch to the new `svelteHTML` namespace and it should work the same.

I have Svelte for VS Code v106.1.0 and neither my old `declare namespace svelte.JSX`  `export interface HTMLProps<T>` nor the new `declare namespace svelteHTML` worked with the new transformation.

**Comment by dummdidumm** [comment] 2022-09-22 20:49
Could you please share a code snippet so we can reproduce this?

**Comment by dummdidumm** [comment] 2022-12-22 15:43
`svelte-check` version 3 has been released which uses the new transformation

**Closed** 2024-07-31 12:45 UTC
