### ISSUE TITLE
The LSP doesn't format when using Svelte 5 features

### ISSUE THREAD

**Issue by gu5e** [sveltejs/language-tools#2426] opened 2024-07-01 11:55 UTC
### Describe the bug

The built in LSP formatter doesn't format the code if it detects Svelte 5 features, like snippets or runes.

### Reproduction

Write a .svelte file that is using one of the new features (like runes or snippets) and try to format the code.

### Expected behaviour

The LSP should format the code.

### System Info

- OS: macOS
- IDE: Neovim

Neovim with Conform and the Svelte LSP for fomatting.

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment] 2024-07-01 12:03
Duplicate of https://github.com/sveltejs/language-tools/issues/2338. Svelte 5 currently require a workspace version of prettier-plugin-svelte and a prettier config file. 

https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Bprettier/.prettierrc

**Closed by jasonlyu123** 2024-07-01 12:03 UTC
Labels: bug

**Comment by sebwib** [comment] 2024-10-08 10:50
When I add the following to the workspace .prettierrc file, prettier stops working for .svelte files.

	"plugins": ["prettier-plugin-svelte"],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
	
prettier-plugin-svelte is updated to the latest version.
I use typescript

**Comment by realguse** [comment] 2024-10-08 18:23
> When I add the following to the workspace .prettierrc file, prettier stops working for .svelte files.
> 
> ```
> "plugins": ["prettier-plugin-svelte"],
> "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
> ```
> 
> prettier-plugin-svelte is updated to the latest version. I use typescript

sorry @sebwib, but i think you should open a new issue, this ones closed
