### ISSUE TITLE
Can't save .svelte file and import lines start blinking, error marker show.

### ISSUE THREAD

**Issue by x4fingers** [sveltejs/language-tools#1712] opened 2022-11-05 08:45 UTC
### Describe the bug

After updating VS code to 1.73.0:
- I can't save any .svelte files and close the editor window normally, only force close work.
- Import lines start blinking.
- Error marker display anywhere for nothing. 

### Reproduction

Save any .svelte file that **has module import**.

### Expected behaviour

- I can't save the file, it will show an error marker for no reason and it starts blinking at import lines.
- I can't close the window normally because of the file-saving process still running.

### System Info

- OS: macOS Ventura 13.0.
- IDE: VS Code version: 1.73.0, commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f.

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

https://user-images.githubusercontent.com/19145304/200111134-630b8c06-e454-444a-908e-2bbdb4f369c3.mov

Uploading Screen Recording 2022-11-05 at 15.42.02.mov…

**Comment by jasonlyu123** [comment] 2022-11-05 08:50
Duplicate of #1703, #1710. The upstream issue seems to do with codeActionOnSave and not just organize import. I'll reopen it if it turns out to be a separate issue.

Until it's fixed in VSCode you can remove codeActionOnSave settings.

**Closed by jasonlyu123** 2022-11-05 08:50 UTC
Labels: bug
