### ISSUE TITLE
Autocompletion of imported variables from external SCSS Files

### ISSUE THREAD

**Issue by MarkTanashchuk** [sveltejs/language-tools#669] opened 2020-11-12 19:12 UTC
I really miss auto-completion of variables and other things I import from separate `.scss` files.

In standard (`.scss`) files it works, for example, there are extensions like `SCSS IntelliSense`, and it would be nice if in style tag in components with `lang="s(a/c)ss"` it could be possible to also have auto-completion from files located either in a certain directory or in workspace.

(Moved from https://github.com/sveltejs/svelte-preprocess/issues/279)

**Comment by dummdidumm** [comment] 2020-11-12 21:45
Duplicate of #241

**Closed by dummdidumm** 2020-11-12 21:45 UTC
